tensorflow/training/docker/2.2.0/py3/Dockerfile.cpu
tensorflow/training/docker/2.2.0/py3/Dockerfile.gpu
test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_mnist.py

use symlinking instead of env variables for ssl_certs_dir

---

mxnet/training/docker/1.6.0/py2/Dockerfile.cpu
mxnet/training/docker/1.6.0/py2/Dockerfile.gpu
mxnet/training/docker/1.6.0/py3/Dockerfile.cpu
mxnet/training/docker/1.6.0/py3/Dockerfile.gpu
pytorch/training/docker/1.4.0/py2/Dockerfile.cpu
pytorch/training/docker/1.4.0/py2/Dockerfile.gpu
pytorch/training/docker/1.4.0/py3/Dockerfile.cpu
pytorch/training/docker/1.4.0/py3/Dockerfile.gpu
tensorflow/training/docker/2.0.1/py2/Dockerfile.cpu
tensorflow/training/docker/2.0.1/py2/Dockerfile.gpu
tensorflow/training/docker/2.0.1/py3/Dockerfile.cpu
tensorflow/training/docker/2.0.1/py3/Dockerfile.gpu
test/sagemaker_tests/pytorch/inference/requirements.txt

*Description:*
Part of this is updating old Dockerfiles (i.e. 2.0.1) so that if people use these Dockerfiles they will not use the Pillow version with security update. The main issue we resolve is updating the test dependency for SM PT tests
*Tests run:*
mxnet 1.6, pt 1.4, tf 2.0.1
Resolving Pillow issue

[mxnet, tensorflow, pytorch] | [build, test] | [sagemaker] Update Pillow version

---

pytorch/buildspec-1-5.yml
pytorch/buildspec.yml
pytorch/training/docker/1.4.0/py3/example/Dockerfile.gpu
test/dlc_tests/container_tests/bin/pytorch_tests/testPyTorchRegression

[pytorch] | [build, test] | [ec2, ecs, eks, sagemaker] PT 1.4 patch release

---

tensorflow/training/docker/1.15.2/py2/Dockerfile.cpu
tensorflow/training/docker/1.15.2/py2/Dockerfile.gpu
tensorflow/training/docker/1.15.2/py3/Dockerfile.cpu
tensorflow/training/docker/1.15.2/py3/Dockerfile.gpu
tensorflow/training/docker/1.15.2/py36/Dockerfile.cpu
tensorflow/training/docker/1.15.2/py36/Dockerfile.gpu
tensorflow/training/docker/2.2.0/py3/Dockerfile.cpu
tensorflow/training/docker/2.2.0/py3/Dockerfile.gpu

*Description:*
We changed the versioning for sagemaker-tensorflow-training because the previous scheme relied on the assumption that we would stop supporting TF 1.x soon. That's no longer the case, so now the versions work out as:
TF version | toolkit version
---|---
1.x | >=10, <20
2.x | >=20
*Tests run:*
ran [our local SageMaker tests](https://github.com/aws/sagemaker-tensorflow-container/tree/master/test/integration/local) for CPU
* TF 1.15.2, all Python versions, CPU and GPU
* TF 2.2, all Python versions, CPU and GPU
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under …

[tensorflow, build] update sagemaker-tensorflow-training versions for TF 1.15.2 and 2.2

---

test/dlc_tests/conftest.py

*Description:*
If running in mainline context, add the instance type to ensure we are using unique ec2 key pairs.
*Tests run:*
Testing in personal account

[test]|[ec2] Add instance type to ec2 key pair

---

test/dlc_tests/eks/pytorch/training/test_eks_pytorch_training.py

*Description:*
It is a temp infra change to unblock PT14 release
*Tests run:*

[pytorch] [build, test] | [ec2, ecs, eks, sagemaker] Disable single-node pytorch training EKS for mainline pipeline

---

tensorflow/buildspec.yml
tensorflow/training/docker/2.2.0/py3/cu101/Dockerfile.gpu

for cuda 10.1, there's an issue when enable tensorboard profiling
Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/openmpi/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
*Description:*
With TensorBoard profiling turned on, we get this error on the new recently released TF2.2 container:
2020-06-03 01:47:51.923816: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcupti.so.10.1'; dlerror: libcupti.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/openmpi/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
By this PR, we add the libcupti.so to the LD_LIBRARY_PATH to …

[Tensorflow][Build]Resolve missing libcupti.so issue

---

src/send_status.py
src/utils.py

Local builds fail because of an import statement that doesn't need to be used: https://github.com/aws/deep-learning-containers/issues/263
*Description:*
Fixed this issue by moving the import statement into the only functions where it is used, rather than a generic import at the head of a file.
*Tests run:*
Built images for TensorFlow on a clone of the repository on my local setup.
- N/A
- N/A

[build] fix: Move dlc import statement to allow local builds

---

testspec.yml

*Description:*
Canary tests require log in to the prod repo, updating testspec to conditionally do so
*Tests run:*
- Tested on the PR in the revision marked "test"

[test] | [canary] Log into prod ECR for canary tests

---

README.md

*Description:*
- EKS tests no longer require a cluster spun up with the aforementioned name. Updating README to reflect these changes.

change: Remove outdated comment from README

---

src/utils.py

https://github.com/aws/deep-learning-containers/issues/265
*Description:*
- Add a default value for CodeBuild project name
*Testing*
- Ran `python src/main.py --buildspec mxnet/buildspec.yml --framework mxnet --image_types training --device_types gpu --py_versions py3`
Build succeeded and successfully pushed py3 gpu mxnet training images

[build] fix: Provide default value for CodeBuild project name to fix local builds

---

tensorflow/training/docker/1.15.3/py2/Dockerfile.cpu
tensorflow/training/docker/1.15.3/py2/Dockerfile.gpu
tensorflow/training/docker/1.15.3/py3/Dockerfile.cpu
tensorflow/training/docker/1.15.3/py3/Dockerfile.gpu
tensorflow/training/docker/1.15.3/py36/Dockerfile.cpu
tensorflow/training/docker/1.15.3/py36/Dockerfile.gpu
tensorflow/training/docker/2.0.2/py2/Dockerfile.gpu
tensorflow/training/docker/2.0.2/py3/Dockerfile.cpu
tensorflow/training/docker/2.1.0/py2/Dockerfile.cpu
tensorflow/training/docker/2.1.0/py2/Dockerfile.gpu
tensorflow/training/docker/2.1.0/py3/Dockerfile.cpu
tensorflow/training/docker/2.1.0/py3/Dockerfile.gpu
tensorflow/training/docker/2.1.1/py2/Dockerfile.cpu
tensorflow/training/docker/2.1.1/py2/Dockerfile.gpu
tensorflow/training/docker/2.1.1/py3/Dockerfile.cpu
test/sagemaker_tests/tensorflow/tensorflow1_training/integration/sagemaker/test_horovod.py
test/sagemaker_tests/tensorflow/tensorflow1_training/resources/hvdbasic/train_hvd_env_vars.py
test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_horovod.py
test/sagemaker_tests/tensorflow/tensorflow2_training/resources/hvdbasic/train_hvd_env_vars.py

*Description:*
- Adds test for changes consumed from aws/sagemaker-training-toolkit#68
- The above changes are automatically consumed by the [tensorflow-training-toolkit](https://github.com/aws/sagemaker-tensorflow-training-toolkit)
*Tests run:*
- Tested manually with TF2.2 (details in aws/sagemaker-training-toolkit#68)
- Ran integration tests in the SageMaker [TF1](https://github.com/aws/sagemaker-tensorflow-training-toolkit/pull/395) and [TF2](https://github.com/aws/sagemaker-tensorflow-training-toolkit/pull/396) training toolkits
- This relates to all Tensorflow 1 Dockerfiles that install `sagemaker-tensorflow-training>=10,<20` and all Tensorflow 2 Dockerfiles that install `sagemaker-tensorflow-training>=20`.
By …

[tensorflow]|[test]|[sagemaker] Add integration test for MPI env vars propagation

---

mxnet/inference/docker/artifacts/config.properties
pytorch/inference/docker/build_artifacts/config.properties

Some of the inference tests failing on certain instance type.
e.g. this test is succeeding on c5.4xlarge, but failed on m4.16xlarge.
```
ubuntu@ip-172-31-11-62:~$ docker run -it --name beta-mxnet-inference-1.6.0-cpu-py27-ubuntu16.04-2020-07-16-00-17-28-ec2-squeezenet -p 80:8080 -p 8081:8081 669063966089.dkr.ecr.us-west-2.amazonaws.com/beta-mxnet-inference:1.6.0-cpu-py27-ubuntu16.04-2020-07-16-00-17-28 multi-model-server --start --mms-config /home/model-server/config.properties --models squeezenet=https://s3.amazonaws.com/model-server/models/squeezenet_v1.1/squeezenet_v1.1.model
Warning: MMS is using non-default JVM parameters: -Xmx128m -XX:-UseLargePages -XX:+UseG1GC -XX:MaxMetaspaceSize=32M -XX:MaxDirectMemorySize=10m -XX:+ExitOnOutOfMemoryError …
```

[mxnet, pytorch] | [inference] | [build, test] Modify on MMS config

---

test/dlc_tests/eks/mxnet/training/test_eks_mxnet_multinode_training.py

```
==================================== ERRORS ====================================
___ ERROR collecting eks/mxnet/training/test_eks_mxnet_multinode_training.py ___
eks/mxnet/training/test_eks_mxnet_multinode_training.py:18: in <module>
@pytest.mark.skipif(is_pr_context(), reason=SKIP_PR_REASON)
E   NameError: name 'is_pr_context' is not defined
```

[mxnet] | [test] | [eks] Fix import error for EKS

---

release_images.yml

*Description:*
Forcing TF 2.2 Inference v1 release due to pipeline failure causing partial release
*Tests run:*
Local test
N/A
N/A

[release] [tensorflow] Force TF 2.2 inference release

---

release_images.yml

*Description:*
Force MXNet 1.6.0 Training GPU Py27 re-release to account for release issues
*Tests run:*
N/A
N/A
N/A

[release] [mxnet] Force release MXNet 1.6 Training gpu py2

---

test/dlc_tests/ec2/tensorflow/training/test_tensorflow_training.py
test/test_utils/ec2.py

*Description:*
Fix the shm issue for TF HVD GPU  teset.
*Tests run:*
Local test passed.

[tensorflow] | [build, test] | [ec2] Add extra shm for TF Hvd GPU test on p2.8xlarge

---

test/dlc_tests/sanity/test_pre_release.py

*Description:*
Temporarily remove canaries that use EC2 resources until we have added external cleanup measures.

[test]|[canary] Temporarily remove EC2 canaries

---

release_images.yml

*Description:*
CUDA 10.2 TF 2.2.0 Training images do not have SageMaker tags
*Tests run:*
N/A
N/A
N/A

[release] [tensorflow] Disable sm tagging on cu102 tf tr images

---

test/dlc_tests/sanity/test_generate_coverage_doc.py

*Description:*
The coverage doc test was skipped in order to unblock mainline pipelines. I believe this is due to git being used, but this will be addressed in PRs 361 and 363. Since those are both large reviews and may take some time to merge in, I wanted to ensure that we are at least running the coverage doc test in PR context so that we get utility from it.
*Tests run:*
- Manually run coverage doc test

[test]|[sanity] Enable the generate coverage doc test in PR context

---

release_images.yml
test/dlc_tests/ec2/test_smdebug.py
test/dlc_tests/eks/tensorflow/training/test_eks_tensorflow_multi_node_training.py

[Tensorflow][ec2,eks]Skipping the EKS test for multinode and smdebug for p2.8xlarge in TF1

---

test/dlc_tests/sanity/test_generate_coverage_doc.py

*Description:*
- Have coverage doc test run in canaries, push to s3 in one region for easy access to the current version of the file
*Tests run:*
- Tested locally, ensured that s3 file gets populated

[test]|[canary] Write out test coverage files in canaries and push them to s3

---

generate_dlc_image_release_information.py

*Description:*
Tested on images:
```
763104351884.dkr.ecr.us-west-2.amazonaws.com/tensorflow-training:2.2.0-gpu-py37-cu101-ubuntu18.04-v1.1
763104351884.dkr.ecr.us-west-2.amazonaws.com/tensorflow-training:2.2.0-cpu-py37-ubuntu18.04-v1.1
763104351884.dkr.ecr.us-west-2.amazonaws.com/aws-samples-tensorflow-training:2.2.0-gpu-py37-cu101-ubuntu18.04-example-v1.1
763104351884.dkr.ecr.us-west-2.amazonaws.com/tensorflow-inference:2.2.0-gpu-py37-cu102-ubuntu18.04-v1.0
763104351884.dkr.ecr.us-west-2.amazonaws.com/tensorflow-inference:2.2.0-cpu-py37-ubuntu18.04-v1.0
763104351884.dkr.ecr.us-west-2.amazonaws.com/tensorflow-training:2.2.0-gpu-py37-cu102-ubuntu1 …
```

[mxnet, tensorflow, pytorch] | [release] | Remove usage of environment variables in github publishing workflow

---

.release_templates/tensorflow1_release_images.yml
release_images.yml

*Description:*
Addition of Inference and Training py27 in releasespec

[Tensorflow][Release]Addition of Inference and Training py27 in releasespec

---

release_images.yml

*Description:*
Keeping SM tags for both py36 and py37 in TF1.15

[Tensorflow][Release]Keeping SM tags for both py36 and py37 in TF1.15

---

release_images.yml

*Description:*
Releasing GPU py27 and py37 Images for TF1.15

[Release][Tensorflow]GPU py27 and py37 Images

---

test/dlc_tests/sanity/test_generate_coverage_doc.py
test/test_utils/__init__.py

*Description:*
- Coverage test was previously failing in mainline, the issue is fixed 
- Publish the coverage file from mainline instead of canary
*Tests run:*
- Locally tested outside of PR context

[test] Enable coverage test in mainline, remove from canary

---

test/requirements.txt
test/testrunner.py

*Description:*
- Add global pytest timeout for ec2/ecs. I have kept the timeout at 81 minutes, to give 9 minutes for any pre-pytest setup or teardown
- For eks, it might make less sense to add a pytest timeout since we have to add one for training/inference/multinode, respectively since they use different pytest commands are are run sequentially. As of now, I have timed training/inference at 39 minutes each, as there is longer pytest setup associated with eks clusters
*Tests run:*
- Testing on this PR

[test]|[ec2, ecs, eks]Add pytest timeout for PR tests

---

test/dlc_tests/container_tests/bin/test_tf_dlc_telemetry_test.py
test/dlc_tests/ec2/tensorflow/training/test_tensorflow_training.py

*Description:*
The tensorflow telemetry test appears to be flaky, and requires more reruns than just the 1. While we dive into the flaky issues, I am marking this as flaky to a) ensure that failures are functional failures and b) avoid additional iteration cycles on PRs/pipelines

[test][tensorflow][ec2] Add flaky marker to telemetry test

---

test/dlc_tests/ec2/tensorflow/inference/test_tensorflow_inference.py
test/test_utils/ec2.py

*Description:*
Skipping the expensive p3dn instance for EIA Test as ideally the customer will not use such expensive GPU instances with EIA Instances.
*Tests run:*

[EIA]Skipping p3dn instance for EIA Instances

---

test/sagemaker_tests/mxnet/inference/requirements.txt
test/sagemaker_tests/mxnet/training/requirements.txt
test/sagemaker_tests/pytorch/inference/requirements.txt
test/sagemaker_tests/pytorch/training/requirements.txt
test/sagemaker_tests/tensorflow/tensorflow1_training/requirements.txt
test/sagemaker_tests/tensorflow/tensorflow2_training/requirements.txt

*Description:*
- SageMaker and sanity tests were failing due to breaking changes coming in from v2 of the pysdk. Updated the requirements.txt files to pin sagemaker package to <2 in order to fix this issue.
*Tests run:*
- Run sanity/sagemaker tests

[test][sanity, sagemaker] Pin sagemaker package to <2 to avoid breaking changes

---

tensorflow/inference/docker/2.2.0/py3/Dockerfile.cpu
tensorflow/inference/docker/2.2.0/py3/Dockerfile.gpu
test/dlc_tests/sanity/test_pre_release.py

*Description:*
Python3.7 was not build with libbz2 in TF serving containers. This causes module import issues for pandas. I updated the library, and also added in a sanity test to check that we can install and import pandas without issue, so that we can avoid this issue in the future.
*Tests run:*
- Sanity test added to this PR
- tensorflow/inference/docker/2.2.0/py3/Dockerfile.cpu
- tensorflow/inference/docker/2.2.0/py3/Dockerfile.gpu 

[build][test][tensorflow] Add libbz2 to TF inference containers

---

available_images.md

*Description:*
- Update available_images.md for TF-2.3 images
- Move the TF-2.2 training images to `Prior Version` section
- As TF-2.3 inference image is not released, keep the TF-2.2 inference image as it is. 

[Release][Tensorflow] update available_images.md for tf2.3

---

pytorch/training/docker/1.6.0/py3/Dockerfile.cpu
pytorch/training/docker/1.6.0/py3/cu101/Dockerfile.gpu

*Description:*
Sanity test for PyTorch training is failing:
```
archspec 0.1.1 requires click, which is not installed.
```

[pytorch] | [build, test] | [sanity] Install click for pytorch images

---

.yamllint
buildspec.yml
release_images.yml
src/requirements.txt
testspec.yml

*Description:*
Currently, we have no yaml linting process. Since changes to some top level yaml files do not result in builds/tests, added a pre-build step to run yaml linting.
Note: I did not add this for $FRAMEWORK/*.yml files because a) they require significant changes and would be better scoped to a different PR and b) they are exercised in the build process
*Tests run:*
- Ran tool locally
- See builds on "add a failure condition for testing purposes" for example failure.

[build] Add yaml linter step for all top level yml files

---

test/dlc_tests/sanity/test_dlc_labels.py

*Description:*
Restrict TF2.3 versioning conditions further, as we will not enforce the changes for inference or new python versions
*Tests run:*
Tested manually with TF2.3 inference

[test][sanity] Restrict TF2.3 version scheme to just training/py37/gpu images

---

test/dlc_tests/benchmark/bai/mxnet/training/test_performance_mxnet_training.py

*Description:*
- Skipping single node MXNet benchmarks due to timeouts. 
*Tests run:*
- Tested other benchmarks passed in the allotted time.

[test][benchmark][MXNet] Temporarily skip single node MXNet benchmarks

---

src/constants.py

*Description:*
1. Change the namespace of PR build metrics
*Tests run:*
N/A
All dockerfiles

[build] Change metrics namespace for PR builds

---

src/start_testbuilds.py
test/sagemaker_tests/mxnet/inference/conftest.py
test/sagemaker_tests/mxnet/inference/integration/__init__.py
test/sagemaker_tests/mxnet/training/conftest.py
test/sagemaker_tests/mxnet/training/integration/utils.py
test/sagemaker_tests/pytorch/inference/conftest.py
test/sagemaker_tests/pytorch/inference/utils/__init__.py
test/sagemaker_tests/pytorch/training/conftest.py
test/sagemaker_tests/pytorch/training/utils/__init__.py
test/sagemaker_tests/tensorflow/inference/test/integration/local/test_pre_post_processing.py
test/sagemaker_tests/tensorflow/inference/test/integration/local/test_pre_post_processing_mme.py
test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/conftest.py
test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/util.py
test/sagemaker_tests/tensorflow/tensorflow1_training/integration/__init__.py
test/sagemaker_tests/tensorflow/tensorflow1_training/integration/conftest.py
test/sagemaker_tests/tensorflow/tensorflow2_training/integration/__init__.py
test/sagemaker_tests/tensorflow/tensorflow2_training/integration/conftest.py

*Description:*
SageMaker Local tests are run on an EC2 instance where py35 is the default python version. Recent changes use the form `f"abc-{variable}-xyz` instead of `"abc-{}-xyz".format(variable)`, which is incompatible with python versions below 3.6.
This PR ensures that all code relevant to SageMaker Local tests conforms to py35 requirements.
*Tests run:*
Local tests
N/A
N/A

[test] [sagemaker] Make SM local tests py35 compatible

---

mxnet/training/docker/1.6.0/py3/Dockerfile.cpu
mxnet/training/docker/1.6.0/py3/cu101/Dockerfile.gpu
test/dlc_tests/eks/mxnet/training/test_eks_mxnet_training.py
test/dlc_tests/eks/pytorch/training/test_eks_pytorch_training.py

*Description:*
It appears the dgl team has cut a release branch for 0.5.x before the 0.5.x release. We will not rely on automatically getting the latest branch from now on and instead pin to a minor.x version so that breaking changes are not introduced. It appears that breaking changes are introduced in minor versions with dgl.
*Tests run:*
- EKS tests pass for mx and pt
- mxnet/training/docker/1.6.0/py3/Dockerfile.cpu
- mxnet/training/docker/1.6.0/py3/cu101/Dockerfile.gpu

[test][pytorch, mxnet][eks] Pin dgl branch to 0.4.x until new version is released

---

mxnet/training/docker/1.6.0/py3/Dockerfile.cpu
mxnet/training/docker/1.6.0/py3/cu101/Dockerfile.gpu

Training images shipped a separate version of GluonNLP than inference images;
the search-replace update in https://github.com/aws/deep-learning-containers/pull/498 missed the training images.
Thanks @TusharKanekiDey for noting the discrepancy

Update GluonNLP in mxnet training images

---

pytorch/buildspec.yml

*Description:*
Rebuild PyTorch 1.5.1 Inference DLC images
*Tests run:*
N/A
https://github.com/aws/deep-learning-containers/blob/master/pytorch/inference/docker/1.5.1/py3/Dockerfile.cpu
https://github.com/aws/deep-learning-containers/blob/master/pytorch/inference/docker/1.5.1/py3/cu101/Dockerfile.gpu
N/A

[build] [pytorch] Build only pytorch 1.5.1 inference images

---

release_images.yml

*Description:*
Set the CUDA version for TF 2.2 to be cu101, and enable CPU images, on release_images.yml
*Tests run:*
N/A
N/A
N/A

[release] Change TF 2.2 CUDA version to 10.1

---

src/send_status.py

*Description:*
The post_status() function did not consider repository name and user in the input to GithubHandler. Fixed by adding this information from CodeBuild Env Variables.
*Tests run:*

[build] Make post_status function generic for all URLs

---

src/send_status.py
test/dlc_tests/sanity/test_canary_integration.py
test/test_utils/__init__.py

*Description:*
The canary test assumes that at least one release tag exists for each framework. The test should be able to run when there are no tags, as well.
*Tests run:*
Tested locally.
N/A
N/A

[test] Pass canary tests when no release tags exist

---

test/dlc_tests/eks/eks_manifest_templates/kubeflow/install_kubeflow_custom_kfctl.sh
test/test_utils/eks.py

*Issues:*
- kfctl issue [5245](https://github.com/kubeflow/kubeflow/issues/5245)
- PR [kfctl/401](https://github.com/kubeflow/kfctl/pull/401)
*Description:*
- kfctl fails to install kubeflow as it is unable to download the kubeflow v1.0.2 tar file.
- Untill the PR [kfctl/401](https://github.com/kubeflow/kfctl/pull/401) is merged and the changes are released on kfctl repo, we will use the custom kfctl binary provided by @Jeffwan that consumes the PR [kfctl/401](https://github.com/kubeflow/kfctl/pull/401)

use custom binary for kfctl client

---

pytorch/buildspec.yml
pytorch/inference/docker/1.6.0/py3/Dockerfile.cpu
pytorch/inference/docker/1.6.0/py3/cu101/Dockerfile.gpu

**Bump version for Torchserve to 0.2.1**
This version of Torchserve has support for Naked Dirs which are required for MME support for SageMaker.
*Tests run:*
MME integration tests on SM.

[pytorch][inference] Bump version for Torchserve to 0.2.1

---

test/sagemaker_tests/mxnet/inference/conftest.py
test/sagemaker_tests/mxnet/training/conftest.py
test/sagemaker_tests/pytorch/inference/conftest.py
test/sagemaker_tests/pytorch/training/conftest.py
test/sagemaker_tests/tensorflow/tensorflow1_training/integration/conftest.py
test/sagemaker_tests/tensorflow/tensorflow2_training/integration/conftest.py

*Description:*
We are currently not using the framework version options, but it can be confusing in terms of defaults. Removing for now to avoid any confusion.
*Tests run:*
Run SM tests

[test][sagemaker] Remove defaults from fw version to avoid confusion

---

test/test_utils/__init__.py

*Description:*
- Future proof to ensure we are properly sorting versions (i.e. 2.15 > 2.3)
- Update the canary logic to a) grab latest framework version if only tagged as inf or tr, but never without that tag
*Tests run:*
- Canary sanity tests in PR

[test][canary] Improve canary logic to sort by package version

---

test/dlc_tests/container_tests/bin/testTensorBoard
test/dlc_tests/container_tests/bin/testTensorFlow

*Description:*
*Tests run:*
updated the scripts to handle tensorboard test failures on 2.1
The current tests look for all *.pb files in tf 2.*. The tensorboard profiler doesn't generated protobuf files in versions < 2.2

[tensorflow] [test] [ec2, ecs] update tensorboard tests to handle cases for tf < 2.2

---

tensorflow/buildspec.yml
tensorflow/training/docker/2.2.0/py3/Dockerfile.cpu
tensorflow/training/docker/2.2.0/py3/cu102/Dockerfile.gpu

*Description:*
*Tests run:*
`tensorflow/training/docker/2.3.0/py3/cu102/Dockerfile.gpu`
`tensorflow/training/docker/2.3.0/py3/Dockerfile.cpu`

[tensorflow]  | [build, test]  | [ec2, sagemaker]| bump smdebug version for tf2

---

test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/util.py

*Description:*
SM test: test_batch_transform times out after the set timeout of 300 sec. Increasing the timeout to 600 for longer running jobs.
*Tests run:*
- test_batch_transform

[test] increase timer for test_batch_transform test

---

release_images.yml

*Description:*
- Release TF-1.15 Training images for CPU/GPU and python version: py27, py36 and py37

[release] release tf-1.15 training images

---

release_images.yml

*Description:*
- Release MXNET-1.7 Training/Inference images for CPU/GPU with
- py36
- UL16.04 
- cu101

[release] release MXNET-1.7 training/inference images

---

test/dlc_tests/sanity/test_safety_check.py

*Description:*
- We need to whitelist the RSA failure for older images with older AWSCLI versions. When they are re-released, the condition can be removed.
*Tests run:*
- Run tests locally
*Additional Context:*
- Purposefully kept each image group in it's own condition in the if statement for ease of removal

[test][sanity, canary] Whitelist RSA safety failure for to-be-released images

---

test/dlc_tests/sanity/test_safety_check.py

*Description:*
- Update canary logic to add additional skips without updating the global IGNORE_SAFETY_IDS

[test][sanity] Update safety test to return empty list

---

release_images.yml
test/sagemaker_tests/mxnet/inference/integration/__init__.py
test/sagemaker_tests/mxnet/training/integration/__init__.py

*Description:*
- Adding PDX to no p2 regions due to low instance availability

[release][test][sagemaker] Update release images and no p2 regions

---

release_images.yml
test/sagemaker_tests/mxnet/inference/integration/__init__.py
test/sagemaker_tests/mxnet/training/integration/__init__.py

This reverts commit 0ebd61d2072889aa676ec7a37f94267480333e5c.
Reverting #596 in order to restore ability to run SM tests on p2 instances in PDX.

Revert "[release][test][sagemaker] Update release images and no p2 regions (#596)"

---

test/dlc_tests/ec2/test_smdebug.py

*Description:*
- SMDebug tests are failing due to timeout issue - skipping for interim to unblock

[test] Skip smdebug test on m4.16x due to infra timeouts

---

test/dlc_tests/ec2/tensorflow/training/test_tensorflow_training.py

*Description:*
Skip the TF mnist training test temporarily due to timeout on small instance types.

[test] Skip TF mnist training test temporarily

---

test/dlc_tests/ec2/test_smdebug.py

*Description:*
Test issue from #609 also observed on tf2.2, skipping smdebug on m4.16x for TF2 for now.

[test] Skip smdebug test on TF2 m4.16x

---

release_images.yml
test/dlc_tests/ec2/test_smdebug.py

*Description:*
Add tf2.2 cu102 images for release, as well as add back inference images to the release images yml
*Tests run:*
Locally ran linter

[release] Update release for TF2 cu102 images

---

release_images.yml

*Description:*
Add TF 2.1.1 to list of image types to be released on release_images.yml
*Tests run:*
Ran local yaml linting tool
N/A
N/A

[release] Add TF 2.1.1 training to release_images.yml

---

test/dlc_tests/sanity/test_safety_check.py

*Description:*
Removing safety-check tool from canary tests

[test][canary] Remove canary that uses safety-check tool

---

test/dlc_tests/sanity/test_pre_release.py

*Description:*
Dependency check is currently failing due to limit issue, blocking pipelines and PRs

[test] Temporarily skip dependency check due to limits

---

release_images.yml

*Description:*
Add TensorFlow 2.2.1 to release_images.yml, and remove TensorFlow 2.2.0
*Tests run:*
N/A
N/A
N/A

[release] [tensorflow] Add TF 2.2.1 training to release_images

---

test/dlc_tests/sanity/test_dlc_labels.py

*Description:*
Increase the major version number for TensorFlow 2 images on the `test_dlc_major_version_dockerfiles` test so that TensorFlow 2.3.1 images can be maintained alongside TensorFlow 2.3.0.
*Tests run:*
Tested by running
```
python -m pytest -s -rA sanity/test_dlc_labels.py::test_dlc_major_version_dockerfiles
```
locally with TensorFlow 2.3.1 image URIs
N/A
None

[test] [tensorflow] Increase minimum version for major version test

---

mxnet/training/docker/1.6.0/py2/Dockerfile.cpu
mxnet/training/docker/1.6.0/py2/cu101/Dockerfile.gpu
mxnet/training/docker/1.6.0/py3/Dockerfile.cpu
mxnet/training/docker/1.6.0/py3/cu101/Dockerfile.gpu
mxnet/training/docker/1.7.0/py3/Dockerfile.cpu
mxnet/training/docker/1.7.0/py3/cu101/Dockerfile.gpu
pytorch/inference/docker/1.4.0/py2/Dockerfile.cpu
pytorch/inference/docker/1.4.0/py2/cu101/Dockerfile.gpu

*Description:*
updated urllib3 to v1.25.10 because of security issue in v1.25.8
*Tests run:*
executed locally
mxnet/training/docker/1.6.0/py2/Dockerfile.cpu
mxnet/training/docker/1.6.0/py2/cu101/Dockerfile.gpu
mxnet/training/docker/1.6.0/py3/Dockerfile.cpu
mxnet/training/docker/1.6.0/py3/cu101/Dockerfile.gpu
mxnet/training/docker/1.6.0/py3/herring/cu101/Dockerfile.gpu
mxnet/training/docker/1.7.0/py3/Dockerfile.cpu
mxnet/training/docker/1.7.0/py3/cu101/Dockerfile.gpu
pytorch/inference/docker/1.4.0/py2/Dockerfile.cpu
pytorch/inference/docker/1.4.0/py2/cu101/Dockerfile.gpu
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute …

[mxnet][pytorch] Updated urllib3 to v1.25.10 because of security issue in v1.25.8

---

test/dlc_tests/ec2/test_smdebug.py

*Description:*
increasing the size of the /dev/shm in docker container since a lower amount of the shared memory leads to false failures of the smdebug tests
*Tests run:*
Executed locally for p2.8xl and p3.8xl

[smdebug][testing]Fixed smdebug memory issue

---

mxnet/buildspec.yml

*Description:*
- We had briefly updated mxnet buildspec to 1.6. This PR is to change it back.
*Tests run:*
PR tests

[mxnet][build] Return buildspec back to 1.7.0 for MXNet

---

release_images.yml

*Description:*
Set the CUDA version for TF 2.3.1 images to 11.0 in release_images.yml
*Tests run:*
N/A
https://github.com/aws/deep-learning-containers/blob/master/tensorflow/training/docker/2.3.1/py3/cu110/Dockerfile.gpu
https://github.com/aws/deep-learning-containers/pull/635

[release] [tensorflow] Set TF 2.3.1 cuda version to 11.0

---

test/dlc_tests/ecs/tensorflow/inference/test_ecs_tensorflow_inference.py
test/dlc_tests/ecs/tensorflow/training/test_ecs_tensorflow_training.py
test/dlc_tests/eks/tensorflow/inference/test_eks_tensorflow_inference.py
test/test_utils/__init__.py

*Description:*
- Add function for is_nightly_context
- Remove complete skips and add conditional skips for nightly tests

[test][tensorflow][ecs, eks] Enable BERT/FasterRCNN tests in nightly

---

test/sagemaker_tests/pytorch/inference/conftest.py
test/sagemaker_tests/pytorch/inference/integration/__init__.py

*Description:*
PyTorch Inference SageMaker Tests have a list of regions where P2 and P3 instance types are not available in enough capacity to run tests. This list was updated in the wrong place when it was originally changed.
Now updated these in the correct python script.
*Tests run:*
N/A
N/A
N/A

[pytorch][test][sagemaker] Update regions without gpu instances for PT SM tests

---

release_images.yml

*Description:*
Revert release-specific changes made to release_images.yml to make it more generic
*Tests run:*
Ran linting tool
N/A
N/A

[release] Reset release images to normal state

---

test/test_utils/__init__.py

*Description:*
TensorFlow 2 canary tests failed because GPU image tests were run twice, both times with the same container name, rather than once for GPU and once for CPU.
*Tests run:*
N/A
N/A
N/A

[test][canary] Use CPU and GPU images for TF2 canary tests

---

test/sagemaker_tests/mxnet/inference/requirements.txt
test/sagemaker_tests/mxnet/training/requirements.txt
test/sagemaker_tests/tensorflow/inference/requirements.txt
test/sagemaker_tests/tensorflow/tensorflow1_training/requirements.txt
test/sagemaker_tests/tensorflow/tensorflow2_training/requirements.txt

*Description:*
Tests fail because of libraries incompatibility. Updated requests version to the one requiring urllib2 > 1.25
*Tests run:*

[test][sagemaker] Updated requests version in tests/sagemaker_tests

---

release_images.yml

[pytorch][build] Removed "cpu" from pytorch 1.5.1 examples

---

test/dlc_tests/eks/tensorflow/training/test_eks_tensorflow_training.py

- [ x] I've prepended PR tag with frameworks/job this applies to : [mxnet, tensorflow, pytorch] | [ei/neuron] | [build] | [test] | [benchmark] | [ec2, ecs, eks, sagemaker]
*Description:*
examples were deleted from keras repository. Using different branch temporary
*Tests run:*

[tensorflow] [eks] [test] Temp fix for keras examples

---

pytorch/inference/docker/1.6.0/py3/Dockerfile.cpu
pytorch/training/docker/1.6.0/py3/Dockerfile.cpu
pytorch/training/docker/1.6.0/py3/cu110/Dockerfile.gpu

*Description:*
<3.2 versions of cryptography have a CVE (CVE-2020-25659) associated with it. For pytorch containers, the cryptography dependency comes from conda packages. However, the cryptography package has not been updated on conda (https://anaconda.org/anaconda/cryptography). Introducing this pip install to ensure that we get the latest version of cryptography and thus a package which mitigates the issue.
*Tests run:*
Built locally, ensured that no dependencies were broken.
PT 1.6 cu11 gpu/cpu training images, cpu inference images
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …

[pytorch] Update cryptography to latest version in pytorch containers

---

test/dlc_tests/benchmark/ec2/tensorflow/training/test_performance_tensorflow_training.py

*Description:*
Skip TF1 benchmark tests temporarily due to infrastructure issues

[test][tensorflow][benchmark][ec2] Skip TF1 ec2 benchmarks temporarily

---

release_images.yml

*Description:*
Add PyTorch 1.6.0 CPU Inference image back to the release_images.yml file
*Tests run:*

[release] Add PT 1.6 CPU image to release_images

---

release_images.yml

*Description:*
Release TensorFlow 2.3.1 cu102 Training and Inference images
*Tests run:*

[release] Release TF 2.3 cu102 images

---

available_images.md

*Description:*
Included MXNet 1.8.0 DLC image URIs on the available_images.md file, but accidentally set Python version to py36 instead of the correct value of py37.
Corrected this through this PR.
*Tests run:*

[doc] Fix typo in image URIs for MXNet 1.8 images on available_images.md

---

release_images.yml

*Description:*
Add PyTorch 1.5.1 EIA image to the image variants to be released on release_images.yml
*Tests run:*
N/A
https://github.com/aws/deep-learning-containers/blob/master/pytorch/inference/docker/1.5.1/py3/Dockerfile.eia

[pytorch][eia][release] Add PT 1.5.1 EI image to release_images

---

release_images.yml

*Description:*
Release validation code validates images if they are mentioned in the `release_images.yml` file regardless of whether they have actually been published in the current execution. This means that older images which followed older tagging conventions can no longer be validated correctly.
This is a short-term fix to enable the current release to proceed correctly.
*Tests run:*

[release] Remove PyTorch 1.5.1 CPU and GPU images from release_images

---

test/dlc_tests/sanity/test_safety_check.py

*Description:*
`safety check --json` recently started producing more output values per CVE than it did before.
We only need the first 5 values, which represent "package name", "affected versions", "installed version", "explanation", and "safety-db vulnerability ID".
*Tests run:*

[test] Fix after number of safety check json params increased

---

test/dlc_tests/eks/tensorflow/inference/test_eks_tensorflow_inference.py

#818 
*Description:*
Skipping the EKS TF inference test due to S3 permissions issue.

[test] skip tf inf eks test

---

test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_mnist.py

*Description:*
Enable TF versions 2.4 and above to run the SMD DataParallel+ModelParallel SageMaker test
*Tests run:*

[test][tensorflow] Enable smd dp-mp test on TF 2.4 and above

---

mxnet/buildspec-eia-1-5-1.yml
mxnet/inference/docker/1.7.0/py3/Dockerfile.eia
src/config/build_config.py
test/dlc_tests/ec2/mxnet/inference/test_mxnet_inference.py
test/dlc_tests/ecs/mxnet/inference/test_ecs_mxnet_inference.py
test/sagemaker_tests/mxnet/inference/integration/sagemaker/test_elastic_inference.py
test/sagemaker_tests/mxnet/inference/resources/default_handlers/model/code/eia_module.py
test/test_utils/__init__.py

*Description:*
Added MXNet 1.5.1 Dockerfile for Elastic Inference, and related test modifications to allow the use of `eimx` accelerator library.
Default framework version on buildspec-eia.yml is now 1.7.0.
*Tests run:*
GitHub Repo PR tests.
MXNet 1.7.0 Elastic Inference Dockerfile: `Dockerfile.eia`

[mxnet][eia][build]Add MXNet 1.7.0 for Elastic Inference

---

test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_smdataparallel.py

#852 
*Description:*
- remove ml.p3dn.24xlarge instance type from sagemaker test

[test] remove ml.p3dn.24xlarge instance type

---

test/dlc_tests/sanity/test_security_check.py

*Description:*
Skip the ECR Scan check on TF 2.4.1 docker images
*Tests run:*

[test] Skip ECR Scan on TF 2.4.1 images

---

available_images.md

*Description:*
- Add PyTorch 1.7.1 Inference DLC images for CPU and GPU
- Add TensorFlow 2.4.1 Training DLC images for CPU and GPU
*Tests run:*

[doc] Add PT 1.7.1 Inference and TF 2.4.1 Training to Available Images

---

available_images.md

*Description:*
Add newly released TF 1.15.5 and PT 1.5.1 Neuron DLC images to available_images.md
*Tests run:*
- https://github.com/aws/deep-learning-containers/releases/tag/v1.3-tf-1.15.5-inf-neuron-py37
- https://github.com/aws/deep-learning-containers/releases/tag/v1.1-pt-1.5.1-inf-neuron-py36

[doc] Add new TF and PT Neuron images to available_images

---

release_images.yml

*Description:*
Add TF 2.3.2 CUDA 11.0 to release_images.yml
*Tests run:*

[release] Add TF 2.3.2 cu110 to release images

---

test/sagemaker_tests/pytorch/training/resources/mnist/smdebug_mnist.py

*Description:*
- Workaround to fix 403 errors while downloading MNIST dataset. For context, refer https://github.com/pytorch/vision/issues/1938

[test] fix mnist dataset download for smdebug test

---

test/dlc_tests/ec2/mxnet/training/test_mxnet_training.py

#936 
*Description:*
- `test_mxnet_train_nlp_cpu` test fails on `t2.2xlarge` instance on mainline pipeline due to connection timeout. However, the test runs fine locally. Hence, skipping the test temporarily.

[test][mxnet] skip mxnet nlp cpu test

---

release_images.yml

*Description:*
Add TF 1.15.5 inference DLCs to release_images.yml
*Tests run:*

[release] Add TF 1.15.5 inference to release images

---

test/dlc_tests/ec2/tensorflow/inference/test_tensorflow_inference.py

#962 
*Description:*
- Skipping the test due to failure in [train_mnist_model](https://github.com/aws/deep-learning-containers/blob/8b2acdec54f0bf047dc9ab950a3c5221b7cd00f7/test/dlc_tests/ec2/tensorflow/inference/test_tensorflow_inference.py#L113) function. This failure is unrelated to EIA image and appears to be an issue with the `p4d` type instance.
- @andrewjguo confirmed that the test works with `p4d.24xlarge` instance.
- See #962 for more details.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that …

[test] Skip EIA GPU test for TF

---

release_images.yml

*Description:*
Add PyTorch 1.5.1 GPU and CPU Training and Inference DLCs to release_images.yml
*Tests run:*

[release] Add PT 1.5.1 to release images

---

release_images.yml

*Description:*
Add TF 2.3.2 CPU and GPU Training to release images
*Tests run:*

[release] Add TF 2.3.2 DLCs to release images

---

src/config/build_config.py
tensorflow/inference/docker/build_artifacts/sagemaker/serve.py

#985 
*Description:*
Sync https://github.com/aws/sagemaker-tensorflow-serving-container/pull/194
*Tests run:*

[tensorflow] [build,test] Fix python sdk repo localmode tfs tests failing issue

---

src/config/build_config.py
tensorflow/inference/docker/build_artifacts/sagemaker/serve.py

*Description:*
set OMP_NUM_THREAD default value to 1
Sync https://github.com/aws/sagemaker-tensorflow-serving-container/pull/195
Multiple customers have reported while trying TF Serving toolkits and containers that we will overload their CPUs. And we had to default the OMP_NUM_THREADs to 1 in those cases. 
It’s a tunable parameter so customers will always be able to change it if they need to
*Tests run:*
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that …

set OMP_NUM_THREAD default to 1

---

huggingface/pytorch/buildspec.yml
huggingface/tensorflow/buildspec.yml

… 4.5.0
*Description:*
This PRs updates the `transformers` version inside the `huggingface` PyTorch and TensorFlow DLC.
*Tests run:*
https://github.com/huggingface/transformers/tree/master/tests/sagemaker
| ID                                  | Description                                                       | Platform                   | #GPUS | Collected & evaluated metrics            |
|-------------------------------------|-------------------------------------------------------------------|-----------------------------|-------|------------------------------------------|
| …

[huggingface_tensorflow, huggingface_pytorch] update for Transformers to 4.5.0

---

test/sagemaker_tests/tensorflow/inference/test/integration/local/test_container.py
test/sagemaker_tests/tensorflow/inference/test/integration/local/test_multi_tfs.py

https://github.com/aws/deep-learning-containers/issues/985
*Description:*
We need to cover the test for not setting up SAGE_PORT ENV var scenario and multi-tfs.
Synced from TFS repo:
https://github.com/aws/sagemaker-tensorflow-serving-container/pull/201
https://github.com/aws/sagemaker-tensorflow-serving-container/pull/205
*Tests run:*
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the …

[tensorflow][test]Add non safe port set test and integration test for multi-tfs

---

src/deep_learning_container.py
test/dlc_tests/sanity/test_telemetry.py

*Description:*
- Modify deep_learning_container.py, and skip all tests
- Keep unit tests for feature accessibility enabled.
*Tests run:*

[build,test] Disable dedicated telemetry tests and tags

---

test/test_utils/__init__.py
test/testrunner.py

Force enable tests for training images only
*Description:*
*Tests run:*

[huggingface_pytorch, huggingface_tensorflow][test]Enabling canary tests for HF frameworks

---

test/dlc_tests/eks/tensorflow/training/test_eks_tensorflow_multi_node_training.py
test/testrunner.py

*Description:*
- remove efa marker from pytest command as the efa marker is not used for tests except sagemaker and pytest does not filter test based on multiple markers (-m) passed using command line (need to find a way to combine in a single -m flag).

[test] remove efa marker from pytest command

---

release_images.yml

[pytorch][release] Release pt1.6 Inference cpu, gpu and training cpu

---

pytorch/inference/docker/1.8/py3/Dockerfile.cpu
pytorch/inference/docker/1.8/py3/cu111/Dockerfile.gpu

[pytorch] [build][test] PT1.8 inference: update pillow to 8.2.0

---

release_images.yml

[tensforlow] Release TF2.3 cuda110 training cpu and gpu

---

test/dlc_tests/sanity/test_pre_release.py

Skip temporarily to revert it 

---

test/dlc_tests/conftest.py
test/sagemaker_tests/huggingface_pytorch/training/conftest.py
test/sagemaker_tests/huggingface_tensorflow/training/integration/conftest.py
test/sagemaker_tests/mxnet/inference/conftest.py
test/sagemaker_tests/mxnet/training/conftest.py
test/sagemaker_tests/pytorch/inference/conftest.py
test/sagemaker_tests/pytorch/training/conftest.py
test/sagemaker_tests/tensorflow/inference/test/integration/local/conftest.py
test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/conftest.py
test/sagemaker_tests/tensorflow/tensorflow1_training/integration/conftest.py
test/sagemaker_tests/tensorflow/tensorflow2_training/integration/conftest.py
test/test_utils/__init__.py

*Description:*
Enable remote override for all tests
*Tests run:*

[test] Add remote override for tests

---

pytorch/training/docker/1.8/py3/Dockerfile.cpu
pytorch/training/docker/1.8/py3/cu111/Dockerfile.gpu
tensorflow/training/docker/2.4/py3/Dockerfile.cpu
tensorflow/training/docker/2.4/py3/cu110/Dockerfile.gpu

*Description:*
Update all TF 2.4 and PT 1.8 DLC to use smdebug 1.0.9
*Tests run:*
All TF 2.4 and PT 1.8 DLC images

[tensorflow, pytorch][build] Update TF 2.4 and PT 1.8 DLC to use smdebug 1.0.9

---

test/dlc_tests/container_tests/bin/pytorch_tests/testPyTorchNcclVersion.py

*Description:*
The results of `find /usr -name libnccl.so.*` could be printed in any order. This caused the test script for NCCL version to sometimes fail based on chance.
*Tests run:*

[test][pytorch][ec2] Fix flakiness in NCCL Version test

---

release_images.yml

*Description:*
Add PT 1.6 cu110 Training DLC and PT 1.8 CPU/GPU Training/Inference DLCs to release_images.yml
*Tests run:*

[release] Add PT 1.6 GPU cu110 and PT 1.8 to release_images

---

test/sagemaker_tests/pytorch/training/integration/sagemaker/test_smdataparallel.py
test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_mnist.py

*Description:*
Undo fixture changes to force smddp+smdmp tests to run in us-east-1..
*Tests run:*

[test][sagemaker][pytorch] Run smddp_smdmp test on correct region

---

test/sagemaker_tests/pytorch/training/conftest.py

*Description:*
Added us-east-2 to NO_P3 regions because of a shortage of p3.16xlarge instances in the region
*Tests run:*

[test][sagemaker][pytorch] Add us-east-2 to no_p3 regions

---

test/dlc_tests/conftest.py
test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py

*Description:*
Skip PyTorch NCCL Version Test on DLCs PyTorch 1.6 and below
*Tests run:*

[test][ec2][pytorch] Run NCCL version test only on PT 1.7 or above DLCs

---

test/sagemaker_tests/huggingface_pytorch/inference/conftest.py
test/sagemaker_tests/huggingface_pytorch/training/conftest.py
test/sagemaker_tests/huggingface_tensorflow/inference/integration/sagemaker/conftest.py
test/sagemaker_tests/huggingface_tensorflow/training/integration/__init__.py
test/sagemaker_tests/mxnet/inference/integration/__init__.py
test/sagemaker_tests/mxnet/training/integration/__init__.py
test/sagemaker_tests/pytorch/inference/conftest.py
test/sagemaker_tests/pytorch/training/conftest.py
test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/conftest.py
test/sagemaker_tests/tensorflow/tensorflow1_training/integration/__init__.py
test/sagemaker_tests/tensorflow/tensorflow2_training/integration/__init__.py

*Description:*
Add ap-northeast-2 to NO_P3_REGIONS lists, due to ICE errors for p3 instances
*Tests run:*

[test][sagemaker] Add ap-northeast-2 to NO_PR_REGIONS

---

release_images.yml

*Description:*
Add HF PT 1.6.0 with Transformers 4.6.1 to release images
*Tests run:*

[release] Add PT 1.6 HF 4.6.1 to release images

---

test/sagemaker_tests/huggingface_pytorch/inference/conftest.py
test/sagemaker_tests/huggingface_pytorch/training/conftest.py
test/sagemaker_tests/huggingface_tensorflow/inference/integration/sagemaker/conftest.py
test/sagemaker_tests/huggingface_tensorflow/training/integration/__init__.py
test/sagemaker_tests/mxnet/inference/integration/__init__.py
test/sagemaker_tests/mxnet/training/integration/__init__.py
test/sagemaker_tests/pytorch/inference/conftest.py
test/sagemaker_tests/pytorch/training/conftest.py
test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/conftest.py
test/sagemaker_tests/tensorflow/tensorflow1_training/integration/__init__.py
test/sagemaker_tests/tensorflow/tensorflow2_training/integration/__init__.py

*Description:*
Add ap-northeast-1 to list of NO_P3_REGIONS so that ICE issues can be avoided in the region
*Tests run:*

[test][sagemaker] Add ap-northeast-1 to NO_P3_REGIONS

---

test/dlc_tests/conftest.py

*Description:*
Added parametrization for "huggingface" keyword and associated DLC images
*Tests run:*

[test] Add huggingface parametrization

---

test/dlc_tests/container_tests/bin/test_smclarify_bias_metrics.py
test/dlc_tests/ec2/test_smclarify.py

*Description:*
The current test checks for exact value match in smclarify tests. When run on different arch or OS, the values can be slightly different. We need to check for approximate values instead.
*Tests run:*
I ran the tests manually using @mansimane 's containers which used to fail this test.
```
PASSED ec2/test_smclarify.py::::test_smclarify_metrics_cpu[XXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/pr-pytorch-training:1.9.0-cpu-py38-ubuntu20.04-pr-1132-2021-06-08-05-36-47-test_smclarify_metrics_cpu-pt-tr-1-9-0-cpu-py38-ubuntu20-04-pr-1132-2021-06-08-05-36-47-XXXXXXXX_test-0-c4.2xlarge]
PASSED ec2/test_smclarify.py::::test_smclarify_metrics_gpu[XXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/pr-pytorch-training:1.9.0-g …
```

[test] Check approximate values in smclarify test

---

tensorflow/buildspec.yml
tensorflow/inference/docker/build_artifacts/sagemaker/python_service.py
tensorflow/inference/docker/build_artifacts/sagemaker/serve.py

*Description:*
Sync a new change already merged in tfs side:  [link](https://github.com/aws/sagemaker-tensorflow-serving-container/commit/6a51a604618e613d7c6d04d520c8264fe4e69d88) 
To elaborate changes in this pr:
- refactor naming of some variables
- modify the way port number passing
- some nit change(single quote to double quote)
*Tests run:*
- pass tfs git repo pr auto-test
- running inference against container locally succeed
- deployed to sagemaker: tested inference against the endpoint, multiple tfs functions well
By submitting …

[tensorflow][build] Modify the way port number passing

---

release_images.yml

*Description:*
Add MXNet 1.8.0 Neuron DLC to release_images.yml
*Tests run:*

[release] Add MX 1.8 Neuron to release_images

---

available_images.md

*Description:*
1. Add MXNet 1.8 Neuron DLC to available_images.md:
```
763104351884.dkr.ecr.us-east-1.amazonaws.com/mxnet-inference-neuron:1.8.0-neuron-py37-ubuntu18.04
```
2. Fix URI for PyTorch 1.7.1 Neuron DLC on available_images.md
```
763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference-neuron:1.7.1-neuron-py36-ubuntu18.04
```
*Tests run:*
https://github.com/aws/deep-learning-containers/releases/tag/v1.0-mx-1.8.0-inf-neuron-py37

[doc] Add MX 1.8 Neuron to available images

---

pytorch/training/docker/1.8/py3/Dockerfile.cpu
pytorch/training/docker/1.8/py3/cu111/Dockerfile.gpu

*Description:*
Set smdebug version on PT 1.8 DLCs back to 1.0.9
*Tests run:*
pytorch/training/docker/1.8/py3/Dockerfile.cpu
pytorch/training/docker/1.8/py3/cu111/Dockerfile.cpu

[build] Revert smdebug version on PT 1.8

---

release_images.yml

*Description:*
Add MXNet 1.8 CPU, GPU, Training, Inference images back to release_images.yml
*Tests run:*

[release] Add std MX 1.8 back to release images

---

release_images.yml

*Description:*
Include PT 1.5.1 eia only as a part of PT 1.5.1 entries in release_images
*Tests run:*

[release] Only release PT 1.5.1 EIA images

---

test/sagemaker_tests/huggingface_tensorflow/training/integration/__init__.py
test/sagemaker_tests/mxnet/inference/integration/__init__.py
test/sagemaker_tests/mxnet/training/integration/__init__.py
test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/conftest.py
test/sagemaker_tests/tensorflow/tensorflow1_training/integration/__init__.py
test/sagemaker_tests/tensorflow/tensorflow2_training/integration/__init__.py

*Description:*
Added `ap-northeast-3` to list of regions with no P2, P3, or P4 instance types
*Tests run:*

[test][sagemaker] Include ap-northeast-3 in NO_Px_REGIONS lists

---

release_images.yml

*Description:*
Changed `release_images.yml` file to add hf-pt-181-training entry

[pytorch] Change release_images yml to add hf-pt-181-training entry

---

dlc_developer_config.toml
src/parse_partner_developers.py

*Description:*
Add some additional useful info to logs for partner dev experience

[partner_devs]Add PR number for builds via github webhook env variable

---

.github/PULL_REQUEST_TEMPLATE.md
dlc_developer_config.toml
test/dlc_tests/sanity/test_dlc_developer_config.py

[tests][sagemaker] Disable SM tests (also EFA) by default on PR

---

test/sagemaker_tests/pytorch/inference/conftest.py
test/sagemaker_tests/pytorch/training/conftest.py

Allow `py38` as input python version on SM Tests for PT Training and PT Inference

[pytorch][test][sagemaker] Allow py38 option on PT SM tests

---

autogluon/training/docker/0.2/py3/Dockerfile.cpu
autogluon/training/docker/0.2/py3/cu102/Dockerfile.gpu
test/dlc_tests/conftest.py
test/dlc_tests/sanity/test_pre_release.py
test/dlc_tests/sanity/test_telemetry.py

[autogluon][test] Fixes for sanity tests

---

autogluon/training/docker/0.2/py3/Dockerfile.cpu
autogluon/training/docker/0.2/py3/cu102/Dockerfile.gpu
test/dlc_tests/conftest.py
test/dlc_tests/sanity/test_pre_release.py
test/dlc_tests/sanity/test_telemetry.py

[autogluon][test]Ag sanity fixes

---

dlc_developer_config.toml
pytorch/buildspec-neuron.yml
pytorch/inference/docker/build_artifacts/neuron_entrypoint.sh

For the pytorch DLC users have an option of running the provided the entrypoint function in /usr/loca/bin. This function starts the torchserve and also every 60 secs makes sure that the torchserve process is not dead. There was an bug in the way it was getting checked and so the container was getting killed after 6 secs.. torchserve when started properly saves the pid in a file and the fix is to use that pid to make sure that the process is running.
All the neuron related tests were run.
- [x ] I've prepended PR tag with frameworks/job this applies to : [mxnet, tensorflow, pytorch] | [ei/neuron] | [build] | [test] | …

[pytorch][neuron][build] - fix the ps command that checks for torchserve running.

---

.github/CODEOWNERS

Update CODEOWNERS with team ID for AutoGluon DLC images

[gitops] Add code owners for new frameworks

---

dlc_developer_config.toml
test/sagemaker_tests/pytorch/__init__.py
test/sagemaker_tests/pytorch/training/integration/sagemaker/__init__.py

PyTorch Training and Inference SageMaker Test logic was written to reupload images to other regions to get around ICE errors. However, this is run whenever the test region is not `"us-west-2"`.
This means that if the list of regions I want to test in is just `["eu-west-1"]`, and the input image I provide exists in ECR in "eu-west-1", the test logic still attempts to reupload the image.
This PR changes the logic so that it only reuploads the image when the region where the test is run is not the same as the region where the ECR image exists.
CI
By submitting this pull request, I confirm that my contribution is made under …

[pytorch][test][sagemaker] Fix PyTorch SM test retry logic

---

.github/CODEOWNERS
dlc_developer_config.toml
src/config.py
src/start_testbuilds.py
src/utils.py
test/dlc_tests/release_candidate_integration/test_sm_profiler.py
test/dlc_tests/sanity/quick_checks/test_dlc_developer_config.py
test/test_utils/__init__.py
test/testrunner.py

- Split "sagemaker_tests" config option into "sagemaker_remote_tests" and "sagemaker_local_tests"
- Provide option to run RC tests on "sagemaker_remote_tests"
Ran tests in CI to ensure that RC tests can run in the sagemaker jobs
N/A
This provides option for developers to run RC integration tests in CI before merge, or when updating RC integration tests. It also allows devs to switch on/off sagemaker-local tests independent of the remote tests. …

[dev][test] Add a config option to run RC integration tests & SM local tests in PR

---

release_images.yml

- Add hf pt 1.8.1 inference containers to release_images.yml

[release] Add huggingface_pytorch 1.8.1 inference containers

---

test/sagemaker_tests/pytorch/__init__.py

[test][SageMaker]Add af and me region support for SM test parser

---

test/dlc_tests/sanity/test_pre_release.py

- whitelist openssl [CVE-2021-3711](https://nvd.nist.gov/vuln/detail/CVE-2021-3711) vulnerability installed on DLC using apt 

[test][sanity] whitelist openssl cve vulnerability installed using apt

---

test/dlc_tests/sanity/test_pre_release.py

[tensorflow][test] Skipping dependency check for TF 2.5

---

release_images.yml

- Prep release for HF 2.4.3 transformers 4.10.2 
- Ran dependency check manually for inference images

[release] Prepare huggingface_tensorflow 2.4.3 transformers 4.10.2 release

---

tensorflow/training/docker/2.6/py3/Dockerfile.cpu
tensorflow/training/docker/2.6/py3/cu112/Dockerfile.gpu
test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_mnist.py

- bokeh 2.4 brings in a typing-extensions dependency that conflicts with TF2.6 binary dependency requirements. Bokeh 2.4 was released today. If we narrow the pinning, we can take in the latest patch version of 2.3 to avoid any dependency breaking changes.
- Ran container locally, installed package, ensured that the pip check failures went away
- TF 2.6 training/inference cpu/gpu images

[tensorflow] Narrow version pinning for bokeh package in TF2.6 training

---

release_images.yml

#1326 
- Update release images iml for new HF release
- HF PT 1.8.1 transformers 4.10.2 (training gpu, inference cpu/gpu)

[release] Update release images for HF PT1.8.1 transformers 4.10.2

---

.github/PULL_REQUEST_TEMPLATE.md
dlc_developer_config.toml
release_images.yml
src/config.py
test/dlc_tests/sanity/quick_checks/test_dlc_developer_config.py

- EFA tests are run on SM remote job in PR - so they should not be a separate option. Refactoring this to avoid confusion when it comes to the separate implementation of sm remote options and the efa option.
- Update PR template to indicate the changes, as well as the tests that should be run prior to new framework merge

[config] Remove efa_tests config option and include as sagemaker_remote_tests option

---

dlc_developer_config.toml
test/dlc_tests/sanity/test_pre_release.py
test/test_utils/ec2.py

- There are unbound variables in the dependency check test, so fixed this issue
- Add optional arg for setting entry point to /bin/bash in ec2 training tests - since we are running these on inference images as well, sometimes the entrypoint does not get appropriately overwritten
- This affects both HF inference and autogluon inference containers
- Running sanity tests on all images to verify success

[bug] Fix bugs in dependency check test

---

release_images.yml

#1355 
- prep release for these two framework version releases
- HF PT1.9 gpu training, cpu and gpu inference
- HF TF2.5 gpu training, cpu and gpu inference

[release] Prepare release for HF PT1.9 and TF2.5 transformers 4.10.2

---

test/dlc_tests/sanity/test_safety_check.py

- Safety checks seem to have been mistakenly enabled everywhere by #1352 - this also negates the safety mode config option. Adding back the logic in this PR

[test] Add back safety check skip conditions

---

release_images.yml

Update release_images.yml to add PyTorch 1.6.0 inference DLCs

[release] Add PT 1.6 inference to release images

---

release_images.yml

- Update release images yaml for TF 2.6.2 training release. Inference is currently set to TF2.6.0 - this will need to be added later when we build/release TF2.6.0

Release tf2.6.2

---

pytorch/training/docker/1.9/py3/cu111/Dockerfile.gpu

FOR PT1.9, getting below error and fix is added to PR
```
>           raise CommandTimedOut(result, timeout=timeout)
E           invoke.exceptions.CommandTimedOut: Command did not complete within 3000 seconds!
E           Command: "nvidia-docker exec --user root ec2_training_container /bin/bash -c '/test/bin/pytorch_tests/testPyTorchS3Plugin'"
E           Stdout:
E           INITIATING SHUFFLE TEST
E           [2021-11-23 19:19:20.529 0b52519bd68f:14 INFO utils.py:27] RULE_JOB_STOP_SIGNAL_FILENAME: None
E           [2021-11-23 19:19:20.572 0b52519bd68f:14 INFO profiler_config_parser.py:102] Unable to find config at …
```

[pytorch][training] PT 1.9.1 Fix package versions 

---

test/dlc_tests/conftest.py
test/dlc_tests/ec2/mxnet/inference/test_mxnet_inference.py
test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference.py
test/dlc_tests/ec2/tensorflow/inference/test_tensorflow_inference.py
test/dlc_tests/eks/mxnet/inference/test_eks_mxnet_inference.py
test/dlc_tests/eks/pytorch/inference/test_eks_pytorch_inference.py
test/dlc_tests/eks/tensorflow/inference/test_eks_tensorflow_inference.py
test/test_utils/ec2.py

- Add special env variable for different arch types
- Skip EKS tests for now, since infra is not ready

[graviton] Add arch_type-specific env variable for graviton EC2 tests

---

dlc_developer_config.toml
test/sagemaker_tests/autogluon/inference/conftest.py
test/sagemaker_tests/autogluon/training/conftest.py
test/sagemaker_tests/huggingface/inference/conftest.py
test/sagemaker_tests/huggingface_pytorch/training/conftest.py
test/sagemaker_tests/huggingface_tensorflow/training/integration/conftest.py
test/sagemaker_tests/mxnet/inference/conftest.py
test/sagemaker_tests/mxnet/training/conftest.py
test/sagemaker_tests/pytorch/inference/conftest.py
test/sagemaker_tests/pytorch/training/conftest.py
test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/conftest.py
test/sagemaker_tests/tensorflow/tensorflow1_training/integration/conftest.py
test/sagemaker_tests/tensorflow/tensorflow2_training/integration/conftest.py
test/test_utils/pytest_cache.py
test/test_utils/sagemaker.py
test/testrunner.py

Smart retry for sagemaker remote tests. We're executing SM remote tests in separate threads so we need additional handler for pytest cache …

[test][sagemaker] Adding smart retry to sagemaker remote tests

---

test/dlc_tests/sanity/test_pre_release.py

- ensure dep check is run on HF neuron images

Run dependency check on HF neuron images

---

test/dlc_tests/benchmark/sagemaker/mxnet/training/test_performance_mxnet_sm_training.py

- MX sagemaker benchmark tests require sagemaker only fixture to run correctly

[mxnet][test][sagemaker] Run MX sagemaker benchmarks on SM images

---

mxnet/buildspec.yml
mxnet/inference/docker/1.9/py3/Dockerfile.cpu
mxnet/inference/docker/1.9/py3/cu112/Dockerfile.gpu
mxnet/training/docker/1.9/py3/Dockerfile.cpu
mxnet/training/docker/1.9/py3/cu112/Dockerfile.gpu

- There are issues updating numpy to greater than or equal to 1.20 (see failed PR https://github.com/apache/incubator-mxnet/pull/20685)
- We cannot use <1.19, even though MX CI pins those requirements for v1.9; We are going to pin numpy to <1.20 for now, and follow up if decisions need to be made based on incompatibility
Test PR for numpy <1.20 in MX1.9: https://github.com/apache/incubator-mxnet/pull/20859/files
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …

Pin numpy to <1.20 in MX 1.9 images

---

test/test_utils/__init__.py

- TF2.8 maps to python 3.9, so update canaries in advance

[canary] Update python versions for TF canaries

---

test/sagemaker_tests/autogluon/inference/conftest.py
test/sagemaker_tests/autogluon/training/conftest.py

Add py38 as an option on autogluon SM test args

[autogluon][test][sagemaker] Add support for py38 version in tests

---

release_images.yml

- re-release TF 2.7 inference images as TF2.7.1

Re-release TF2.7 inference images as TF2.7.1

---

test/dlc_tests/container_tests/bin/testSmprofiler

The [test_pytorch[False-False]](https://github.com/awslabs/sagemaker-debugger/blob/v1.0.13/tests/zero_code_change/test_pytorch_integration.py#L29) included in [testSmproflier](https://github.com/aws/deep-learning-containers/blob/master/test/dlc_tests/container_tests/bin/testSmprofiler#L114) fails for Pytorch >=1.7. The test however works for [True-False] combination. The test needs revamp to be compatible with newer versions of PT.
See https://github.com/awslabs/sagemaker-debugger/issues/580
**NOTE: If you are creating a PR for a new framework version, please ensure success of the standard, rc, and efa sagemaker remote …

[test] disable incompatible test in testSmprofiler for PT>=1.7

---

huggingface/build_artifacts/inference/config.properties

The HF DLC container uses the sagemaker-huggingface-inference-toolkit to start MMS. When it starts MMS, it uses the default config.properties at: [link](https://github.com/aws/sagemaker-inference-toolkit/blob/master/src/sagemaker_inference/etc/default-mms.properties#L2) (HF toolkit consumes sagemaker-inference-toolkit).
This config sets enable_envvars_config=true, which means at MMS start-time (endpoint creation), a user can supply environment variables to SageMaker, when defining the PrimaryContainer in sm_client.create_model() call. The supported config options are: …

[huggingface] Enable overwritable MMS parameter

---

dlc_developer_config.toml
tensorflow/inference/docker/build_artifacts/sagemaker/nginx.conf.template
tensorflow/inference/docker/build_artifacts/sagemaker/serve.py
test/dlc_tests/sanity/test_pre_release.py
test/sagemaker_tests/tensorflow/inference/test/integration/local/test_nginx_config.py
test/sagemaker_tests/tensorflow/tensorflow2_training/integration/local/test_training.py

This adds support for the user to modify this NGINX [config variable](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout) in the TF SM inference images via an environment variable. 
I've tested the local TF inference SM tests.

[tensorflow] [sagemaker] Add nginx timeout

---

test/dlc_tests/sanity/test_anaconda.py

Disable anaconda removal test while working on emergency

[test] Disable anaconda test

---

release_images.yml

Add TF 2.6 Training DLCs to release_images.yml

[release] Add TF 2.6 to release_images

---

available_images.md

- Typo in description of HF neuron containers

Fix typo in available_images markdown file

---

release_buildspec.yml

After https://github.com/aws/deep-learning-containers/pull/1939 modified the `src/config.py` file to import functions from the local script `codebuild_environment`, the tests work fine, but release buildspec fails to import `src.config` because the PYTHONPATH for release_buildspec.yml is not the same as testspec.yml.
This PR now adds `export PYTHONPATH=$PYTHONPATH:$(pwd)/src` to the `release_buildspec.yml` file.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …

[release] Fix release buildspec testing after src config changes

---

test/dlc_tests/conftest.py

We encountered error when generate key pair like 
```
botocore.exceptions.ClientError: An error occurred (InvalidKeyPair.Duplicate) when calling the CreateKeyPair operation: The keypair 'test_dependency_check_cpu-tf-inf-2-9-0-cpu-py39-ubuntu20-04-ec2-pr-2250-2022-09-22-17-12-21-4d2b410b50ccc8a66e1a643a31453cbad1987bf4-1' already exists.
```
The problem is that the generated key name is not unique because it always append a non unique digit to it, this fix replace this non unique digit with a uuid string which will make it unique.
After adding the uuid string, the length of this key will be 169 characters, so we still have …

[Bug Fix] Fix key name generation

---

huggingface/pytorch/training/docker/1.11/py3/cu113/Dockerfile.trcomp.gpu.os_scan_allowlist.json

Fixing allowlist for HF PT 1.11 part 2

---

test/test_utils/ec2.py

SM local tests are failing to launch Base DLAMI due to volume size issues. Recommended storage size for Base DLAMI on EC2 console is 100 GB.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute …

Update volume size to accomodate new AMI

---

autogluon/buildspec.yml
available_images.md
release_images.yml

- Remove AG inference images from buildspec - these are now defined under "inference" specific buildspecs
- Add release info for DJL

Add release info for DJL; Fix AG buildspec

---

release_images.yml

This PR updates the release images file in order to release TF2.11 Training and Inference images for SM + EC2, along with AutoGluon Training images for version 0.6.1

[Release] Release TF2.11 + AG 0.6.1

---

test/dlc_tests/sanity/quick_checks/test_buildspecs.py

- Ensure that buildspec quick checks test runs only in PR
- Test is not supported in mainline context
- Test runs regularly in quick_checks

Make quick checks tests PR-only

---

release_images_training.yml

Release schema update for TF2.10.1 to release CVE patching efforts for the images (CPU, GPU EC2 + SageMaker, GPU Example Image)

[TensorFlow][Training] TF2.10.1 Release 

---

release_images_inference.yml

Update release_images_inference.yml for re-release of TensorFlow 2.9.1 Graviton
quick PR test for release on first commit

[graviton][release] TF 2.9.1 Graviton patch release

---

dlc_developer_config.toml
mxnet/inference/docker/1.9/py3/Dockerfile.cpu
mxnet/inference/docker/1.9/py3/cu112/Dockerfile.gpu

- Patch MXNet dockerfiles
- Upper bound pin matplotlib which has pip check issue with numpy version required for 1.9 images

Patch MX 1.9 inference images

---

test/testrunner.py

- Add reruns to canary pytest cmd to avoid flaky errors
- Tests will run in canary context

Add reruns statement to canary tests

---

dlc_developer_config.toml
testspec.yml

- Sometimes we get unexpected failures due to hiccups with pypi installation. Instead of failing the whole build, try to install requirements again.

[test] Retry requirements install on failure

---

test/test_utils/__init__.py

The regex for the HF canaries tends to pick up versions from the `hf-trcomp` images as well. This causes wrong image uris to be picked up and thus the failure of the canary jobs. This PR aims to fix this.
Locally ran the `parse_canary_images` function. …

[Huggingface][Test] Fix Huggingface Canaries

---

dlc_developer_config.toml
huggingface/tensorflow/inference/buildspec.yml
huggingface/tensorflow/inference/docker/2.11/py3/Dockerfile.cpu
huggingface/tensorflow/inference/docker/2.11/py3/cu112/Dockerfile.gpu
huggingface/tensorflow/inference/docker/2.11/py3/cu112/Dockerfile.gpu.os_scan_allowlist.json

Update HF TF to TF 2.11.1 patch version

Update HF TF images to TF 2.11.1

---

src/requirements.txt
test/requirements.txt
test/sagemaker_tests/autogluon/inference/requirements.txt
test/sagemaker_tests/autogluon/training/requirements.txt
test/sagemaker_tests/huggingface/inference/requirements.txt
test/sagemaker_tests/huggingface_pytorch/training/requirements.txt
test/sagemaker_tests/huggingface_tensorflow/training/requirements.txt
test/sagemaker_tests/mxnet/inference/requirements.txt
test/sagemaker_tests/mxnet/training/requirements.txt
test/sagemaker_tests/pytorch/inference/requirements.txt
test/sagemaker_tests/pytorch/training/requirements.txt
test/sagemaker_tests/tensorflow/inference/requirements.txt
test/sagemaker_tests/tensorflow/tensorflow1_training/requirements.txt
test/sagemaker_tests/tensorflow/tensorflow2_training/requirements.txt
test/test_utils/pytest_cache.py

**Note**: 
Temporarily disable remote caching on S3 of the pytest `lastfailed` file outside of PR context …

[test] Temporarily disable pytest failure remote caching

---

dlc_developer_config.toml
pytorch/inference/docker/2.0/py3/Dockerfile.cpu
pytorch/inference/docker/2.0/py3/Dockerfile.graviton.cpu
pytorch/inference/docker/2.0/py3/cu118/Dockerfile.gpu

**Note**: 
* Update PT 2.0 images (x86 and Graviton) to use TorchServe 0.8.0
* Disabling nvgpu metrics on PT 2.0 GPU SageMaker image.
Commit: [9ba7e9f](https://github.com/aws/deep-learning-containers/pull/3030/commits/9ba7e9fc7ead77b912e7732d4094b22ae8024c97)
* Build (x86)
* EC2 tests (x86) (CPU/GPU)
* ECS tests (x86) (CPU/GPU)
* EKS tests (x86) (CPU/GPU)
* Sanity tests (x86) (CPU/GPU)
* SM local Tests (x86) (CPU/GPU)
* SM remote tests (x86) (CPU/GPU)
Commit: [57f3a75](https://github.com/aws/deep-learning-containers/pull/3030/commits …

[pytorch] update TorchServe to 0.8.0 and disable nvgpu metrics on SM gpu

---

dlc_developer_config.toml
test/dlc_tests/ecs/conftest.py

**Note**: 
https://github.com/aws/deep-learning-containers/pull/2970 changed the scope of region from “session” to “function” to allow instances to be created in any region for EC2-instance based tests. This caused the `ecs_client` fixture to break, as it was defined to be a `"session"` fixture, but is still dependent on the `region` fixture that is now `"function"` scoped.
Fixing this by changing `ecs_client` to be a function scoped fixture similar to ec2_client
**NOTE: By default, docker builds are disabled. In order to build your …

[test][ecs] Fix bug that causes ecs_client creation failure

---

release_images_inference.yml

CVE patch for FasterTransformer DJL 0.21.0 LMI container

[djl-serving] cve patch on 0.21.0 fastertransformer lmi container

---

dlc_developer_config.toml
test/test_utils/__init__.py

**Note**: 
Remove  HuggingFace inference pre-install of packages for sagemaker benchmark to reduce benchmark overhead and failures.
**Additionally, please run the …

[HugginFace] Remove Installation Piece for HF Inference

---

test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_smtrcomp.py

[test] Skip test_BYOC_training Training Compiler test on TF DLCs

---

dlc_developer_config.toml
pytorch/inference/docker/2.0/py3/Dockerfile.cpu
pytorch/inference/docker/2.0/py3/cu118/Dockerfile.gpu

**Note**: 
Sanity test was failing due to mkl not found. After investigation, we found that mkl was somehow being downgraded to an older version, possibly due to a new cryptography release yesterday (08/01). The fix is to lower-pin the mkl version.
x86 tests successful at comimt [f891aea](https://github.com/aws/deep-learning-containers/pull/3219/commits/f891aea969832fff58160e6d6c649fc45db7abeb):
dlc-pr-pytorch-inference_dlc-pr-ec2-test
dlc-pr-pytorch-inference_dlc-pr-ecs-test
dlc-pr-pytorch-inference_dlc-pr-eks-test …

[PyTorch] [SM, EC2] Pin mkl version in x86 inference Dockerfiles

---

release_images_inference.yml

**Note**: 
Release image definitions for re-releasing PyTorch 2.0.1 inference with new torchserve version.
Related PRs: 
[#3199](https://github.com/aws/deep-learning-containers/pull/3199)
[#3219](https://github.com/aws/deep-learning-containers/pull/3219)

[PyTorch] [SM, EC2] Add release image definitions for PT 2.0.1 inference torchserve upgrade

---

dlc_developer_config.toml
test/dlc_tests/release_candidate_integration/test_sm_profiler.py
test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_smdataparallel.py

**Note**: 
* SM Data-Parallel is no longer supported, nor installed for TF 2.13 and above. Skipping the tests associated to it.
* SM Profiler (Part of SM Debugger) is no longer supported or installed on TF 2.13 and above. Skipping tests associated to it.
On Commit: [1346c13](https://github.com/aws/deep-learning-containers/pull/3232/commits/1346c13e06e3215f3829bd7b434b47cb57b69446)
* SM EFA Tests
* SM Local tests
On Commit: [7024bd0](https://github.com/aws/deep-learning-containers/pull/3232/commits/7024bd0d1d8fc41c5204b2c2322cc37261c3 …

[tensorflow][training] disable SM dataparallel tests for TF 2.13 and above

---

test/dlc_tests/release_candidate_integration/test_sm_profiler.py

**Note**: 
- SageMaker Profiler V1 is deprecated for PyTorch >= v2.0 and TensorFlow >= v2.11. See [release notes](https://docs.aws.amazon.com/sagemaker/latest/dg/debugger-release-notes.html). Skip the corresponding tests based on the framework versions. …

Skip sagemaker profiler test due to deprecation

---

pytorch/training/buildspec.yml

**Note**: 
Need to increase image size due to issues with [the build and test pipeline](https://us-west-2.console.aws.amazon.com/codesuite/codebuild/669063966089/projects/pytorch-training-latest-codebuild/build/pytorch-training-latest-codebuild%3A3c04843a-e9b2-4f4c-82e2-9393b5e74ebe/?region=us-west-2).
Error:
```
Successfully built fbe7e2f38a14
Successfully tagged 669063966089.dkr.ecr.us-west-2.amazonaws.com/beta-pytorch-training:2.0.1-gpu-py310-cu118-ubuntu20.04-ec2-2023-08-21-17-43-08-pre-push
[INFO] Completed Build for …
```

PyTorch 2.0.1 EC2 Fix: Increasing PyTorch Training EC2 DLC image size

---

test/dlc_tests/conftest.py
test/dlc_tests/ec2/test_efa.py

[PT20-training-gpu] [CUDA121] Fix typos

---

dlc_developer_config.toml
pytorch/inference/buildspec-graviton.yml
pytorch/inference/docker/2.0/py3/Dockerfile.ec2.graviton.cpu.os_scan_allowlist.json
pytorch/inference/docker/2.0/py3/Dockerfile.sagemaker.graviton.cpu.os_scan_allowlist.json

**Note**: 
Upgrading torchserve version from 0.8.1 to [0.8.2](https://github.com/pytorch/serve/releases/tag/v0.8.2) in PyTorch 2.0.1 inference DLCs for graviton for both SM and EC2. 
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute …

[PyTorch][Graviton][SM, EC2] Upgrade torchserve version from 0.8.1 to 0.8.2

---

dlc_developer_config.toml
pytorch/training/docker/2.0/py3/cu121/Dockerfile.gpu

**Note**: 
1. [Apex](https://github.com/NVIDIA/apex) recommends to add ninja to speed up its build from source.
- Without ninja, time is 2653.0ss ~ 44 mins
- With ninja, time is 1749.5s ~ 30 mins
2. Reduce image size from 22.5 GB to 14.4 GB = 8.1 GB reduction
- Install cuda packages in a separate command after pytorch package install to reduce size of layer
- Install needed packages instead of cudatoolkit to reduce size of image
- Use mamba clean after every mamba install to clear its cache
3. Revert SSH keys change
4. Update aws …

[PT20 CUDA121] Speed up Apex, reduce image size, update aws ofi nccl plugin

---

test/dlc_tests/ec2/test_efa.py
test/test_utils/ec2.py

**Note**: 
EFA Health Checks to run only on p4 instance types
* When …

[Pytorch][Test] PT2.0.1 Cu118 Training tests fast follow continued

---

release_images_inference.yml

**Note**: 
removed old TF 1.13 and PT 2.0.1 entries and added PT 1.13 x86_64 for release_images_inference.yml
Quick PR checks on initial commit.

[pytorch][release] Patch release PT 1.13 Inference x86_64

---

pytorch/inference/buildspec-graviton.yml
pytorch/inference/docker/2.1/py3/Dockerfile.graviton.cpu

**Note**: 
update Graviton buildspec to use the latest torchserve and sagemaker toolkit for PyTorch 2.1 DLCs
SageMaker Inference Recommender tests for hugging face models. …

[graviton] update PyTorch 2.1 buildspec to use the latest torchserve and sagemaker toolkit

---

dlc_developer_config.toml
test/sagemaker_tests/pytorch/training/conftest.py
test/sagemaker_tests/pytorch/training/integration/sagemaker/__init__.py
test/sagemaker_tests/pytorch/training/integration/sagemaker/test_distributed_operations.py
test/sagemaker_tests/pytorch/training/integration/sagemaker/test_gdrcopy.py
test/sagemaker_tests/pytorch/training/integration/sagemaker/test_pt_s3_plugin.py
test/sagemaker_tests/pytorch/training/integration/sagemaker/test_pytorchddp.py
test/sagemaker_tests/pytorch/training/integration/sagemaker/test_pytorchddp_inductor.py
test/sagemaker_tests/pytorch/training/integration/sagemaker/test_smdataparallel.py
test/sagemaker_tests/pytorch/training/integration/sagemaker/test_smppy.py
test/sagemaker_tests/pytorch/training/integration/sagemaker/test_training_smdebug.py

**Note**: 
Bug in retry logic causes same `job_name` to be passed to multiple attempts of the same training job in a region. SM Training requires each training job to have a unique name. Move `job_name` unique-suffix creation into helper function.
**NOTE: If you are creating a PR for a new framework version, please ensure success of the standard, rc, and …

[test][pytorch] Fix SM Training test retry bug

---

test/dlc_tests/ec2/test_efa.py

set cuda_home flag for Tensorflow EFA test

---

test/sagemaker_tests/pytorch/training/conftest.py

…fixture change. Fixing assumptions in cuda version specific fixtures.
**Note**: 
* When …

Updating SM training fixtures

---

huggingface/pytorch/inference/docker/2.0/py3/Dockerfile.cpu.os_scan_allowlist.json

Add temp ignore for HF PT inference 2.0

---

data/ignore_ids_safety_scan.json
huggingface/pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu.os_scan_allowlist.json

Add temp ignore for HF PT training 2.0

---

dlc_developer_config.toml
pytorch/training/docker/2.1/py3/Dockerfile.cpu
pytorch/training/docker/2.1/py3/cu121/Dockerfile.gpu

Increase the PyTorch Logging Verbosity to record activity in advanced modules involving graph capture, compilation and execution.  This should aide greatly in debugging compilation errors in PyTorch 2.X reducing the need to rerun jobs for troubleshooting purposes.
PyTorch uses static variables to track API usage and print the activity once in lifetime of the process. This should cause no additional overhead since we expect no more than 20 additional lines of logs and the prints from CPP layer have no performance impact. Ref: https://github.com/pytorch/pytorch/blob/main/c10/util/Logging.cpp#L93
PyTorch introduced a new logging mechanism to selectively increase verbosity for certain advanced modules like compiler. This greatly aides in the debugging of failures when using compilation. These …

[PyTorch] [Training] [2.1] [SageMaker] Enabling PyTorch Verbose Logging for advanced modules

---

pytorch/training/docker/2.1/py3/cu121/Dockerfile.gpu

This PR fixes installation of PyTorch since both EC2 and SM layer now use the same binary.
This PR also fixes issue of installing PyTorch in SM layer since `PYTORCH_VERSION_SM` variable is not declared and has since been installing the latest PyTorch version which worked with PT 2.1.0 currency but this will no longer work when PT 2.2.0 is released.

fix pytorch installation between ec2 and sm

---

pytorch/training/docker/2.1/py3/cu121/Dockerfile.gpu

Revert `aws-ofi-nccl` installation to `aws-ofi-nccl-dlc`.
This is because ec2 channel contains `aws-ofi-nccl-dlc` along with `torchtext` and `torchdata` that is installed in the SM DLC. 
Conda channel, however, contains only `aws-ofi-nccl` without `torchtext` and `torchdata`. Moving forward with PT 2.2.0 releases, the conda channel will include `torchtext` and `torchdata`.

Revert aws-ofi-nccl to aws-ofi-nccl-dlc

---

pyproject.toml

**Note**: 
Pytest remote caching was broken due to the introduction of pytest ini_options to the pyproject.toml file in the root folder of the repo: https://github.com/aws/deep-learning-containers/pull/3499#discussion_r1490387419
We can fix this by removing these marker definitions in pyproject.toml, and if needed, adding them to conftest or elsewhere. …

[test] Fix remote caching failures for pytest tests

---

test/sagemaker_tests/pytorch/training/integration/sagemaker/test_pytorchddp.py

This reverts commit 975de31b0711ad633ebf4838d698c500afa06275.
**Note**: 
<details> …

Revert "Updating pytorchddp test"

---

test/dlc_tests/conftest.py
test/sagemaker_tests/pytorch/training/conftest.py

**Note**: 
<details>
</details>
<details> …

Ensure _validate_pytorch_framework_version() only checks for pytorch

---

dlc_developer_config.toml
src/image_builder.py
test/dlc_tests/sanity/quick_checks/test_dlc_developer_config.py

**Note**: 
- Remove "datetime" tag option from toml
- If you want to disable builds, only one option to change (do_build --> False)
- Always add datetime when building an image.
- Still require at least one build before turning off "do_build"
- Test that do_build flag turned on tags both datetime and non-datetime([8787979](https://github.com/aws/deep-learning-containers/pull/3733/commits/878797916c936e4a49d372f853b6614b99fab5a9)), but test jobs look for datetime
- Test that do_build flag turned off looks for non-datetime image …

Remove datetime tag config option

---

dlc_developer_config.toml
test/sagemaker_tests/pytorch/training/conftest.py
test/sagemaker_tests/pytorch/training/integration/sagemaker/test_pytorchddp.py
test/sagemaker_tests/pytorch/training/integration/sagemaker/test_pytorchddp_inductor.py

**Note**: 
<details>
</details>
<details> …

Skip smdataparallel p5 tests

---

test/testrunner.py

**Note**: 
Due to issues with updating EKS worker nodes, we will temporarily disable EKS tests until the EKS GPU Optimized AMI is updated. Any images that need to be tested on EKS will fail their tests. …

[test] Temporarily force EKS tests to fail

---

pytorch/training/docker/2.0/py3/cu118/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
pytorch/training/docker/2.0/py3/cu121/Dockerfile.sagemaker.gpu.os_scan_allowlist.json

**Note**: 
<details>
</details>
<details> …

Adding new CVE for PT2.0

---

release_images_training.yml

**Note**: 
<details>
</details>
<details> …

[release] Add PT 2.1 to release images

---

test/testrunner.py

This reverts commit a84e2ba91dcf5b692f668e07725421c330ada6ac.
**Note**: 
<details> …

[test] Revert "Temporarily force EKS tests to fail"

---

available_images.md

**Note**: 
<details>
</details>
<details> …

Update available_images.md for pt 2.2.0 inference sm dlc

---

pytorch/training/buildspec-2-2-ec2.yml

**Note**: 
- Split out PT 2.2 EC2 into a separate buildspec
<details> …

Split out PT 2.2 training EC2 images

---

dlc_developer_config.toml
test/dlc_tests/conftest.py
test/test_utils/ec2.py

**Note**: 
- Sort priority - 1) available capacity, 2) total capacity; Do this to prioritize minimum instances required, to leave double openings open for heavier instance types
- Look through all reservations; return if we launch successfully
- Follow up from #3752 
- add function names to logs
- Execute without function name logs([462a956](https://github.com/aws/deep-learning-containers/pull/3756/commits/462a95603887eb219b7f56ecb7d347e8c7e0ef43))
- Execute with function name logs …

Look at all available reservations

---

available_images.md

**Note**: 
Add TF 2.14.1 EC2 and SM Training and Inference DLCs to available_images
<details>
**Additionally, please run the sagemaker local …

[doc] Add TF 2.14.1 DLCs to available_images

---

dlc_developer_config.toml
src/patch_helper.py
test/dlc_tests/sanity/test_ecr_scan.py
test/test_utils/security.py

**Note**: 
This PR solves 2 issues:
1. In case there was no vulnerability associated with the image, we did not end up removing the stale allowlist vulnerabilities. The changes on the test side help with this issue.
2. AutoPatch patches all the vulnerabilities above `LOW`. However, we will reduce the threshold to patch vulnerabilities above `UNDEFINED`. …

[Build][Test] Handle cases for ECR Scanning tests

---

dlc_developer_config.toml
src/start_testbuilds.py
test/dlc_tests/ec2/pytorch/training/common_cases.py
test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py
test/dlc_tests/ec2/pytorch/training/test_pytorch_training_2_1.py
test/dlc_tests/ec2/test_smclarify.py

**Note**: 
- Move PT 2.1 training tests into bins, similar to PT 2.2
<details> …

Refactor PT 2.1 tests

---

data/ignore_ids_safety_scan.json
huggingface/pytorch/inference/docker/1.13/py3/Dockerfile.cpu.os_scan_allowlist.json
huggingface/pytorch/inference/docker/1.13/py3/cu117/Dockerfile.gpu.os_scan_allowlist.json
huggingface/pytorch/training/docker/1.13/py3/cu117/Dockerfile.gpu.os_scan_allowlist.json

**Note**: 
<details>
</details>
<details> …

Add additional ignores

---

huggingface/pytorch/training/docker/1.13/py3/cu117/Dockerfile.gpu
release_images_training.yml

**Note**: 
<details>
</details>
<details> …

Fix build dependencies

---

data/ignore_ids_safety_scan.json
huggingface/pytorch/inference/docker/1.13/py3/cu117/Dockerfile.gpu.os_scan_allowlist.json
huggingface/pytorch/training/docker/1.13/py3/cu117/Dockerfile.gpu

Similar to https://github.com/aws/deep-learning-containers/pull/3130
This resolves test failures for diffusers.
**Note**: 
<details> …

Add diffusers support to PT 1.13 Training DLC

---

data/ignore_ids_safety_scan.json
huggingface/pytorch/inference/docker/1.13/py3/cu117/Dockerfile.gpu
huggingface/pytorch/training/buildspec-1-13.yml

**Note**: 
<details>
</details>
<details> …

Resolve build failures

---

test/sagemaker_tests/pytorch/training/integration/sagemaker/test_pytorchddp.py
test/sagemaker_tests/pytorch/training/integration/sagemaker/test_pytorchddp_inductor.py

**Note**: 
- use ml instance type for skip condition on p5
<details> …

Check ml instance type for skip condition

---

dlc_developer_config.toml
tensorflow/inference/buildspec-2-13-graviton.yml
tensorflow/inference/docker/2.14/py3/Dockerfile.graviton.cpu

**Note**: 
Add TF 2.14 graviton DLC dockerfiles
<details> …

[tensorflow] Add TF 2.14 Graviton DLC dockerfile

---

release_images_inference.yml
release_images_training.yml

**Note**: 
<details>
</details>
<details> …

Release HF PT 1.13 patches

---

huggingface/pytorch/training/docker/1.13/py3/cu117/Dockerfile.gpu

**Note**: 
<details>
</details>
<details> …

Patch huggingface pytorch training 1.13

---

dlc_developer_config.toml
huggingface/pytorch/inference/buildspec-4-34-1-neuronx.yml
huggingface/pytorch/inference/docker/1.13/py3/sdk2.15.0/Dockerfile.neuronx

**Note**: 
tests passed for [ca71f24](https://github.com/aws/deep-learning-containers/pull/3813/commits/ca71f2425b91c6e19f862edca40aed17861d3d5a)
<details> …

Resolve CVE-2023-47248 for huggingface-pytorch-inference-neuronx:1.13.1-transformers4.34.1-neuronx-py310-sdk2.15.0-ubuntu20.04

---

data/ignore_ids_safety_scan.json

**Note**: 
Adding data to the allowlist - there is no fix for the vuln as it is an intended feature and impacts all versions. Impacted package is already latest/upgraded. …

Adding data to the allowlist

---

dlc_developer_config.toml
pytorch/training/buildspec-2-2-ec2.yml
pytorch/training/buildspec.yml
pytorch/training/docker/2.2/py3/cu121/Dockerfile.gpu
src/config.py
test/dlc_tests/sanity/quick_checks/test_dlc_developer_config.py

**Note**: 
[623e329](https://github.com/aws/deep-learning-containers/pull/3839/commits/623e3293e4299fe29a6b4f5b3127e3d61fe6ccf4)
- Passed ec2 test
- Passed sanity test
- Passed eks test
- Passed ecs test …

Re-enable Autopatch for PyTorch 2.2 Training EC2

---

dlc_developer_config.toml
pytorch/inference/buildspec-graviton.yml
pytorch/inference/docker/2.2/py3/Dockerfile.ec2.graviton.cpu.core_packages.json
pytorch/inference/docker/2.2/py3/Dockerfile.ec2.graviton.cpu.py_scan_allowlist.json
pytorch/inference/docker/2.2/py3/Dockerfile.sagemaker.graviton.cpu.core_packages.json
pytorch/inference/docker/2.2/py3/Dockerfile.sagemaker.graviton.cpu.py_scan_allowlist.json

**Note**: 
**All tests (sanity, ec2, ecs, eks, sm remote, sm local, autopr) passing on [b4418b5](https://github.com/aws/deep-learning-containers/pull/3846/commits/b4418b526c6f7f2f1a7fbfc517f4689b9c52d7e2)**
**NOTE: If you are creating a PR for a new framework version, please ensure success of the standard, rc, and efa sagemaker remote tests by updating …

Onboard PyTorch 2.2 Graviton Inference images to autopatch

---

available_images.md
dlc_developer_config.toml
pytorch/inference/buildspec-2-1-ec2.yml
pytorch/inference/docker/2.1/py3/Dockerfile.cpu
pytorch/inference/docker/2.1/py3/Dockerfile.ec2.cpu.core_packages.json
pytorch/inference/docker/2.1/py3/cu118/Dockerfile.ec2.gpu.core_packages.json
pytorch/inference/docker/2.1/py3/cu118/Dockerfile.gpu
pytorch/training/buildspec-2-1-ec2.yml
pytorch/training/docker/2.1/py3/Dockerfile.cpu
pytorch/training/docker/2.1/py3/Dockerfile.ec2.cpu.core_packages.json
pytorch/training/docker/2.1/py3/cu121/Dockerfile.ec2.gpu.core_packages.json
pytorch/training/docker/2.1/py3/cu121/Dockerfile.gpu
test/dlc_tests/container_tests/bin/gdrcopy/test_gdrcopy_dev.sh
test/dlc_tests/ec2/test_gdrcopy.py

**Note**: 
[42f7839](https://github.com/aws/deep-learning-containers/pull/3847/commits/42f783938397499c0828aeeeb5fb88e44915b143) - Both Training and Inference DLCs
- Passed ec2 test
- Passed eks test
- Passed ecs test
- Passed benchmark test
- Passed sanity test
**NOTE: If you are creating a PR for a new framework version, please ensure success of the …

Onboard PyTorch 2.1 Training/Inference EC2 to Autopatch

---

release_images_inference.yml

**Note**: 
- Release Triton 24.03
<details>
</details>
<details>
Click the checkbox to enable a build to execute upon merge.
*Note: By default, pipelines are set to "latest". Replace with major.minor framework version if you do not want "latest".*
</details> …

Release Triton v24.03

---

release_images_inference.yml

**Note**: 
<details>
</details>
<details> …

Release PyTorch 2.1 Inference Autopatch

---

huggingface/pytorch/training/docker/1.13/py3/sdk2.15.0/Dockerfile.neuronx
huggingface/pytorch/training/docker/1.13/py3/sdk2.15.0/Dockerfile.neuronx.os_scan_allowlist.json

**Note**: 
<details>
</details>
<details> …

resolving idna vuln instead of ignoring

---

data/ignore_ids_safety_scan.json
huggingface/pytorch/training/docker/1.13/py3/sdk2.15.0/Dockerfile.neuronx

**Note**: 
<details>
</details>
<details> …

fixing safety scan ignore for neuronx

---

dlc_developer_config.toml
pytorch/inference/buildspec-graviton-2-1.yml
pytorch/inference/docker/2.1/py3/Dockerfile.ec2.graviton.cpu.core_packages.json
pytorch/inference/docker/2.1/py3/Dockerfile.ec2.graviton.cpu.py_scan_allowlist.json
pytorch/inference/docker/2.1/py3/Dockerfile.graviton.cpu
pytorch/inference/docker/2.1/py3/Dockerfile.sagemaker.graviton.cpu.core_packages.json
pytorch/inference/docker/2.1/py3/Dockerfile.sagemaker.graviton.cpu.py_scan_allowlist.json

**Note**: 
[543914a](https://github.com/aws/deep-learning-containers/pull/3859/commits/543914a8b2f1e72d19ec38ebb042a10e31165884) EC2 and SM Graviton DLC
- Passed ec2 test
- Passed eks test
- Passed ecs test
- Passed benchmark test
- Passed sanity test
- Passed sm test
- Passed sm local test
- Passed sm benchmark test
- Passed sm rc test
- Passed sm efa test
**NOTE: By default, docker builds are disabled. In order to build your container, please update dlc_developer_config.toml and specify the framework to build in …

Onboard PyTorch 2.1 Graviton DLC to Autopatch

---

available_images.md

**Note**: 
- Update documentation to note the changed Triton accounts for version 23.12 onwards
<details>
</details>
<details>
Click the checkbox to enable a build to execute upon merge.
*Note: By default, pipelines are set to "latest". Replace with major.minor …

[Doc] Update Triton doc

---

release_images_inference.yml

**Note**: 
<details>
</details>
<details> …

patch deepspeed 0.26.0

---

pytorch/training/docker/2.2/py3/cu121/Dockerfile.gpu

**Note**: 
<details>
</details>
<details> …

remove RDMA flag

---

test/dlc_tests/benchmark/ec2/pytorch/inference/test_performance_pytorch_inference.py
test/dlc_tests/benchmark/ec2/tensorflow/inference/test_performance_tensorflow_inference.py
test/test_utils/__init__.py

**Note**: 
- Remove PT benchmark test, as it was never completed and we run benchmarks at framework level
- Disable TF benchmark test until AMI is avalable
<details> …

Disable Graviton benchmark tests

---

dlc_developer_config.toml
tensorflow/inference/buildspec-2-13-graviton.yml
tensorflow/inference/docker/2.13/py3/Dockerfile.ec2.graviton.cpu.core_packages.json
tensorflow/inference/docker/2.13/py3/Dockerfile.ec2.graviton.cpu.py_scan_allowlist.json
tensorflow/inference/docker/2.13/py3/Dockerfile.sagemaker.graviton.cpu.core_packages.json
tensorflow/inference/docker/2.13/py3/Dockerfile.sagemaker.graviton.cpu.py_scan_allowlist.json

**Note**: 
Onboard TF 2.13 Graviton image to Autopatch
<details> …

Onboard TF 2.13 Graviton image to Autopatch

---

release_images_training.yml

**Note**: 
<details>
</details>
<details> …

Release PyTorch 2.1 Training Autopatch

---

release_images_inference.yml
release_images_training.yml

Add Pytorch 1.13.1 NeuronX Training release
**Note**: 
<details> …

Add Pytorch 1.13.1 NeuronX Training release

---

release_images_training.yml

Fixes the number in release training image.
**Note**: 
<details> …

fix: release_training_image version

---

release_images_inference.yml

**Note**: 
Patch release updating the LMI Neuron 2.18.1 NeuronSDK container.
<details> …

[djl-serving] 0.27.0 neuronx-sdk patch release

---

release_images_training.yml

fix: remove second release config for HF pytorch training
**Note**: 
<details> …

fix: remove second release config for HF pytorch training

---

autogluon/training/docker/1.1/py3/Dockerfile.cpu
dlc_developer_config.toml
release_images_inference.yml
release_images_training.yml

**Note**: 
<details>
</details>
Click the checkbox to enable a …

[AutoGluon] AutoGluon v1.1 Fix CPU training and release

---

release_images_inference.yml
release_images_training.yml

**Note**: 
<details>
</details>
<details> …

Release PT 1.13.1 training

---

pytorch/training/docker/1.13/py3/Dockerfile.ec2.cpu.core_packages.json
pytorch/training/docker/1.13/py3/Dockerfile.sagemaker.cpu.core_packages.json
pytorch/training/docker/1.13/py3/cu117/Dockerfile.ec2.gpu.core_packages.json
pytorch/training/docker/1.13/py3/cu117/Dockerfile.sagemaker.gpu.core_packages.json

**Note**: 
Adding packages to PT1.13 training images
<details> …

Adding packages to PT1.13 training images

---

release_images_training.yml

This PR is raised to force release HF Pytorch training image, because the github release info is not published last time. We need to do a force release to publish the info.
**Note**:  …

force release HF Training Neuronx image

---

dlc_developer_config.toml
pytorch/inference/buildspec.yml
test/sagemaker_tests/pytorch/inference/requirements.txt

**Note**: 
- New version of requests breaks docker-py and thus test requirements
- Tested with [e822f96](https://github.com/aws/deep-learning-containers/pull/3940/commits/e822f96a381c9b1eee60b1d53ebd0417c57dd869)
**NOTE: If you are creating a PR for a new framework version, please ensure success of the standard, rc, and efa sagemaker remote tests by …

Fix SM Endpoint Error

---

test/test_utils/__init__.py

**Note**: 
- PT 2.3 is now py311
<details>
</details>
<details> …

Fix PT 2.3 canary tests

---

dlc_developer_config.toml
pytorch/inference/docker/2.2/py3/cu118/Dockerfile.ec2.gpu.core_packages.json
pytorch/inference/docker/2.2/py3/cu118/Dockerfile.gpu
pytorch/inference/docker/2.2/py3/cu118/Dockerfile.sagemaker.gpu.core_packages.json

**Note**: 
pin triton version to 2.2.0 according to https://github.com/pytorch/pytorch/blob/v2.2.0/.ci/docker/triton_version.txt
[4c10b85](https://github.com/aws/deep-learning-containers/pull/3954/commits/4c10b85d6b0dee8f7ab134de63b90d4f8d25161f)
https://tiny.amazon.com/1cvco7lxh/IsenLink
**NOTE: If you are creating a PR for a new framework version, …

fix triton version in pt2.2 inference gpu images

---

available_images.md

**Note**: 
<details>
</details>
<details> …

Update PT 2.3.0 EC2 Training DLC to Available_images.md

---

available_images.md
src/buildspec.py

**Note**: 
- Filter buildspec warnings
- Remove out of support images from available images
<details>
**Additionally, please run the sagemaker …

Clean up available images and extraneous buildspec warnings

---

release_images_inference.yml
release_images_patches.yml
release_images_training.yml
test/dlc_tests/sanity/quick_checks/test_yml_config.py
test/dlc_tests/sanity/test_pre_release.py

**Note**: 
- Add remaining images to release yaml patches file
- Add additional test to ensure numbering is correct in release yaml files
<details> …

Update release yaml, add numbering test

---

tensorflow/training/docker/2.13/py3/Dockerfile.ec2.cpu.core_packages.json
tensorflow/training/docker/2.13/py3/Dockerfile.sagemaker.cpu.core_packages.json
tensorflow/training/docker/2.13/py3/cu118/Dockerfile.ec2.gpu.core_packages.json
tensorflow/training/docker/2.13/py3/cu118/Dockerfile.sagemaker.gpu.core_packages.json
tensorflow/training/docker/2.13/py3/example/Dockerfile.gpu.example.core_packages.json
tensorflow/training/docker/2.14/py3/Dockerfile.ec2.cpu.core_packages.json
tensorflow/training/docker/2.14/py3/Dockerfile.sagemaker.cpu.core_packages.json
tensorflow/training/docker/2.14/py3/cu118/Dockerfile.ec2.gpu.core_packages.json
tensorflow/training/docker/2.14/py3/cu118/Dockerfile.sagemaker.gpu.core_packages.json

**Note**: 
<details>
</details>
<details> …

add jinja2 to core pkgs

---

available_images.md

**Note**: 
<details>
</details>
<details> …

Update PT 2.3.0 SM Training DLC to available_images.md

---

dlc_developer_config.toml
test/dlc_tests/sanity/quick_checks/test_dlc_developer_config.py

**Note**: 
Updated the dveloper toml file to have the sagemaker local and remote test to true by default.
Updated quick check tests to reflect new defaults.
<details> …

Set sagemaker test to true by default

---

pytorch/training/buildspec-2-2-sm.yml

**Note**: 
- Re-enable autopatch
<details>
</details>
<details> …

Re-enable autopatch on PT 2.2 sm training

---

tensorflow/training/docker/2.13/py3/Dockerfile.ec2.cpu.core_packages.json
tensorflow/training/docker/2.13/py3/cu118/Dockerfile.ec2.gpu.core_packages.json
tensorflow/training/docker/2.14/py3/Dockerfile.ec2.cpu.core_packages.json
tensorflow/training/docker/2.14/py3/cu118/Dockerfile.ec2.gpu.core_packages.json

**Note**: 
Remove jinja from tf213 tf214 ec2 core packages
<details> …

Remove jinja from tf213 tf214 ec2 core packages

---

test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference_inductor.py

**Note**: 
- Inductor tests are hardcoding instances, which causes them to run on these instance types regardless of assigned type. 
- Updating tests to use logic to avoid repeating same test in multiple environments
**NOTE: If you are creating a PR for a new framework version, please ensure success of the standard, rc, and efa sagemaker remote tests by …

Remove hard coded instance types from inductor tests

---

data/ecr_scan_vulnerabilities.json

**Note**: 
Adding data to scan vulns for ECR
<details> …

Adding data to scan vulns for ECR

---

release_images_inference.yml

**Note**: 
<details>
</details>
<details> …

[0.28.0] TensorRT-LLM DLC release

---

release_images_inference.yml

**Note**: 
<details>
</details>
<details> …

[0.28.0] tnx dlc release

---

release_images_inference.yml

**Note**: 
<details>
</details>
<details> …

[0.28.0] cpu dlc release

---

release_images_inference.yml

**Note**: 
Release for 0.28.0 LMI container
<details>
</details> …

[djl-serving] 0.28.0 lmi release

---

dlc_developer_config.toml
pytorch/inference/buildspec-graviton-2-2.yml
pytorch/inference/docker/2.2/py3/Dockerfile.ec2.graviton.cpu.core_packages.json
pytorch/inference/docker/2.2/py3/Dockerfile.ec2.graviton.cpu.py_scan_allowlist.json
pytorch/inference/docker/2.2/py3/Dockerfile.graviton.cpu
pytorch/inference/docker/2.2/py3/Dockerfile.sagemaker.graviton.cpu.core_packages.json
pytorch/inference/docker/2.2/py3/Dockerfile.sagemaker.graviton.cpu.py_scan_allowlist.json

**Note**: 
- [3f2851e](https://github.com/aws/deep-learning-containers/pull/3985/commits/3f2851ebd44dcea698288d570f7a858343b75b60)
- Passed ec2, eks, ecs, benchmark, sm remote, sm local, sm efa, sm rc, sm benchmark tests
**NOTE: If you are creating a PR for a new framework version, please ensure success of the standard, rc, and efa sagemaker remote tests …

PyTorch 2.2 Graviton SM Inference Update inference toolkit to 2.0.24

---

release_images_patches.yml

**Note**: 
<details>
</details>
<details> …

Add PT2.3 Inference to release_images_patches.yml

---

test/sagemaker_tests/pytorch/inference/conftest.py

**Note**: 
<details>
</details>
<details> …

[Test][PyTorch][Inference] Add 311 to valid python versions

---

available_images.md

**Note**: 
<details>
</details>
<details> …

Add PT2.3 Inference x86 to available_images.md

---

release_images_inference.yml

**Note**: 
<details>
</details>
<details> …

[0.28.0] Tensorrt-llm dlc patch release

---

release_images_inference.yml

**Note**: 
<details>
</details>
<details> …

[0.28.0] tnx dlc patch release

---

release_images_inference.yml

**Note**: 
<details>
</details>
<details> …

[0.28.0] djl cpu release

---

src/prepare_dlc_dev_environment.py
test/dlc_tests/sanity/quick_checks/test_prepare_dev_env.py

**Note**: 
- Add "--buildspecs" feature, which allows a user to enter a path of a buildspec file, infer the build job associated with the buildspec, and update this key to the user provided value.
- Continue to support the tests options
- Add new quick checks unit tests to test the functionality of the script
- Execute unit tests
**NOTE: If you are …

Add "--buildspecs" feature to src/prepare_dlc_dev_environment.py

---

src/prepare_dlc_dev_environment.py

**Note**: 
- Add '--restore' feature to revert Toml file back to its original state.
- Add shorthand args to use, and long-version is still available.
- Execute unit tests
- Requires either Buildspec or Restore option
**NOTE: If you are creating a PR for a new framework version, please ensure success of the standard, rc, and efa sagemaker remote tests by …

Add restore feature to revert the toml file to original state

---

data/ecr_scan_vulnerabilities.json
dlc_developer_config.toml
tensorflow/inference/docker/2.14/py3/Dockerfile.ec2.cpu.core_packages.json
tensorflow/inference/docker/2.14/py3/Dockerfile.sagemaker.cpu.core_packages.json
tensorflow/inference/docker/2.14/py3/cu118/Dockerfile.ec2.gpu.core_packages.json
tensorflow/inference/docker/2.14/py3/cu118/Dockerfile.sagemaker.gpu.core_packages.json
tensorflow/training/docker/2.13/py3/Dockerfile.sagemaker.cpu.core_packages.json
tensorflow/training/docker/2.13/py3/cu118/Dockerfile.sagemaker.gpu.core_packages.json
tensorflow/training/docker/2.14/py3/Dockerfile.ec2.cpu.core_packages.json
tensorflow/training/docker/2.14/py3/Dockerfile.sagemaker.cpu.core_packages.json
tensorflow/training/docker/2.14/py3/cu118/Dockerfile.ec2.gpu.core_packages.json
tensorflow/training/docker/2.14/py3/cu118/Dockerfile.sagemaker.gpu.core_packages.json

**Note**: 
Remediation for PT and TF image build and tests.
Addition of previous DLC custom vulnerability was causing issues with PT images, so we had to make a targeted change for TF images.
Ran all the tests on TF2.14 and PT2.2 images.
**NOTE: If you are creating a PR for a new framework version, please ensure success of the standard, rc, and efa …

[Build][Test] Remediation for PT and TF image build and tests

---

data/ignore_ids_safety_scan.json
huggingface/pytorch/inference/docker/2.1/py3/Dockerfile.cpu

**Note**: 
<details>
</details>
<details> …

fix: apt-get update linux-libc-dev in HF PT image

---

data/ignore_ids_safety_scan.json

**Note**: 
<details>
</details>
<details> …

fix: remove trailing comma

---

release_images_inference.yml

**Note**: 
<details>
</details>
<details> …

[djl-serving] 0.28.0 lmi patch

---

release_images_inference.yml

**Note**: 
<details>
</details>
<details> …

[0.28.0] tensorrt llm dlc patch release

---

release_images_inference.yml

**Note**: 
<details>
</details>
<details> …

[0.28.0] lmi dlc patch release

---

test/testrunner.py

**Note**: 
- Temporarily remove reruns for debugging purposes
<details> …

deep_canary: temp remove rerun argument

---

test/dlc_tests/sanity/test_canary_integration.py
test/testrunner.py

**Note**: 
- Re-enable retries, but also do not run pull test in us-west-2 which is running functional tests
<details>
- Enable specific tests for a buildspec or set of …

Re-enable retries in deep canary

---

dlc_developer_config.toml
test/sagemaker_tests/huggingface/inference/requirements.txt

```
if i >= HEALTH_CHECK_TIMEOUT_LIMIT:
>               raise RuntimeError("Giving up, endpoint didn't launch correctly")
E               RuntimeError: Giving up, endpoint didn't launch correctly
```
Fix this for HF pytorch image building
**Note**: 
<details>
Assuming your …

fix endpoint failures for HF pytorch image

---

data/ignore_ids_safety_scan.json
huggingface/pytorch/training/docker/1.13/py3/cu117/Dockerfile.gpu

- Upgrade sagemaker version.
- Add to ignore list for transformers, torch non critical vulnerabilties
**Note**: 
<details>
- Run default builds and tests for a particular buildspec - also …

[huggingface][pytorch-training] patch

---

data/ignore_ids_safety_scan.json
huggingface/pytorch/training/docker/1.13/py3/cu117/Dockerfile.gpu

- Add 2 non critical vulnerabilities to ignore list that require new image
**Note**: 
<details>
- Run default builds and tests for a particular buildspec - also commits and pushes changes …

[huggingface][pytorch-training] Patch 2024 08 01

---

dlc_developer_config.toml
huggingface/pytorch/training/docker/2.1/py3/cu121/Dockerfile.gpu
huggingface/pytorch/training/docker/2.1/py3/cu121/Dockerfile.gpu.os_scan_allowlist.json
test/sagemaker_tests/huggingface_pytorch/training/integration/sagemaker/test_smdp.py
test/sagemaker_tests/huggingface_pytorch/training/integration/sagemaker/test_smmp.py

**Note**: 
* HF PT tests failing in release pipeline due to ModuleNotFound for smprocessing.modelparallel (SMMP). After syncing with the SMMP team, I learned the following:
* SMP v1 is supported only on PyTorch <2.0 and CUDA 11.
* SMP v2 will work on PyTorch 2.1 and CUDA 12, but this version of SMP is used specifically on SMP distributed containers (not DLC), and therefore do not require coverage in this repo.
* Despite a lengthly investigation, I cannot confirm why these tests were passing 5 months ago.
*  HF PT tests for …

HuggingFace PyTorch Training 2.1.0 GPU Test Fix

---

test/dlc_tests/sanity/test_pre_release.py

**Note**: 
- Sanity check test is failing in the BuildRC pipeline, blocking the vulnerability resolution patch for one of the neuronx image container 
- the reason is the code expect transformers-neuronx to have 4 components in the version number, like the more recent ones ("name":"transformers-neuronx","version":"0.10.0.21") but version 0.9 still uses the old 3 components versioning ("name":"transformers-neuronx","version":"0.9.474")
- Updating the logic to create version_list to deal with this situation so that it would do 'keep …

fix: Fix neuronx buildRC pipeline sanity check failure

---

dlc_developer_config.toml
test/dlc_tests/sanity/test_pre_release.py

**Note**: 
Handle pip check that raises exception due to platform not-supported check introduced with latest pip
<details>
- Run default builds and tests for a particular buildspec - also …

[Test] PT2.3 training image - Handle pip check that raises exception due to platform not-supported check introduced with latest pip

---

eks_infrastructure/create_cluster.sh

**Note**: 
EKS cluster create script fails on OSX due to "-P" option not being available. Adding condition to enable OSX usage

Update EKS create cluster script

---

src/image_builder.py

**Note**: 
- Shorten huggingface in initiator to circumvent breaching long tag names
<details>
Fill out the template and click the checkbox of the builds you'd like to execute
*Note: Replace with <X.Y> with the major.minor framework version (i.e. 2.2) you would like to start.*
</details>
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …

Shorten initiator name for HF builds

---

huggingface/pytorch/inference/docker/2.1/py3/sdk2.19.1/Dockerfile.neuronx.os_scan_allowlist.json

**Note**: 
Following errors failed in pipeline, because the already ignored vulnerabilities are under a different `release` number. Thus adding what's missed to ignore list.
```
AssertionError: Total of 1 vulnerabilities need to be fixed on 669063966089.dkr.ecr.us-west-2.amazonaws.com/beta-huggingface-pytorch-inference-neuronx:2.1.2-transformers4.41.1-neuronx-py310-sdk2.19.1-ubuntu20.04-2024-08-21-02-53-32:
--
543 | E             {"linux": [{"description": "In the Linux kernel, the following vulnerability has been resolved: …
```

chore: add vulnerbility scans from a different release to ignore list

---

huggingface/pytorch/inference/docker/2.1/py3/sdk2.19.1/Dockerfile.neuronx.os_scan_allowlist.json

**Note**: 
Another vulnerability shows up in pipeline with the same CVE but different release. This commit adds it
```
{"linux": [{"description": "In the Linux kernel, the following vulnerability has been resolved: greybus: Fix use-after-free bug in gb_interface_release due to race condition. In gb_interface_create, &intf->mode_switch_completion is bound with gb_interface_mode_switch_work. Then it will be started by gb_interface_request_mode_switch. Here is the relevant code. if (!queue_work(system_long_wq, &intf->mode_switch_work)) …
```

fix: ignore another vulnerability with same CVE but different release

---

huggingface/pytorch/inference/docker/2.1/py3/sdk2.19.1/Dockerfile.neuronx.os_scan_allowlist.json

**Note**: 
Add one more vuln scan result to ignore for neuronx image.
<details> …

chore: add one more vuln scan to ignore for neuronx image

---

dlc_developer_config.toml
miscellaneous_scripts/dockerfile_patch_script.sh
test/test_utils/__init__.py

**Note**: 
(@sallyseok taking over this PR)
Added a change to replace underscores with hyphens for all package names in `get_installed_python_packages_with_version`. https://github.com/aws/deep-learning-containers/pull/4179 changed the mechanism to get package names and versions from `pkg_resources` to `pip list`, which caused inconsistencies with the package names where the same package would sometimes use hyphens and sometimes underscores. `pkg_resources` handles this already …

Upgrade sagemaker-training package

---

dlc_developer_config.toml
test/dlc_tests/sanity/test_ecr_scan.py

**Note**: 
- If available, read value from env variable
- This code is used in both sanity test and build - though a bit unconventional as it involves importing a test module into src; looks like the workaround was to use lazy imports (https://github.com/aws/deep-learning-containers/blob/ac36c40c7fa9a3a0c2b7c4a5b09b25a3cf9931a5/src/patch_helper.py#L78) …

 Update autopatch storage account in ecr test 

---

test/test_utils/__init__.py

**Note**: 
Troubleshoot graviton canary issues
<details>
`python …

[Test] Troubleshoot graviton canary issues

---

test/dlc_tests/sanity/quick_checks/test_prepare_dev_env.py

**Note**: 
- Remove the xfail test from the dev env quick checks suite; currently, they cause more confusion than provided value
- Update tests to only run in PRs
- tests are executed as part of quick checks

Update prepare_dlc_dev_environment tests

---

pytorch/inference/docker/2.4/py3/Dockerfile.graviton.cpu
pytorch/inference/docker/2.4/py3/cu124/Dockerfile.graviton.gpu

[PyTorch][Inference][Graviton] Add nvgpu to graviton gpu image

---

test/dlc_tests/container_tests/bin/transformerengine/testPTTransformerEngine

**Note**: 
- Tested TE locally on p5. All tests on TE passed except onnx due to lack of TE prioritization.
<details>
- Run default builds and tests for a particular buildspec - also …

Disable TE onnx export test

---

test/test_utils/__init__.py

**Note**: 
Fix HF utility function - if env is not present, assume false

Fix builds that do not have buildspec env

---

huggingface/pytorch/training/docker/2.1/py3/cu121/Dockerfile.gpu.os_scan_allowlist.json

Pipeline blocked behind detected `linux` vulnerabilities that are not in the allowlist [isenlink](https://tiny.amazon.com/325qtpa4/IsenLink). Updated the allowlist based on the output of that failing test

fix: pt 2.1 training scan allowlist

---

huggingface/pytorch/training/docker/2.1/py3/sdk2.19.1/Dockerfile.neuronx

patch apparmor vulnerability

---

available_images.md

**Note**: 
- End of support for PT 2.1 CPU/GPU/Graviton images

Remove PT 2.1 CPU/GPU/Graviton images from available images

---

eks_infrastructure/upgrade_operation.sh

Allow EKS upgrade operations to continue after a nodegroup failed

---

dlc_developer_config.toml
huggingface/pytorch/inference/docker/2.1/py3/sdk2.19.1/Dockerfile.neuronx

Pinning `libneuronxla` as it was getting bumped to `2.0.4115.0` which is only compatible with neuron 2.20 not 2.19
**Note**: 
<details>
- Run default builds and tests for a particular buildspec - also commits and pushes …

fix: pin libneuronxla version for hf pt inf neuron

---

.github/CODEOWNERS
release_images_patches.yml

**Note**: 
- Return codeowners to its original state for release yaml
- Remove PT 2.1 and TF 2.14 from patches yaml

Add codeowners back, remove PT 2.1 and TF 2.14 from yaml

---

release_images_patches.yml

**Note**: 
Add back TF 2.16 graviton images to patches yaml

Re-enable TF 2.16 graviton images

---

release_images_patches.yml

**Note**: 
Add back TF 2.16 inference ec2 to release patches file

Re-enable TF 2.16 inference EC2

---

available_images.md

Add triton v24.09 DLC version to available images

---

test/dlc_tests/conftest.py
test/dlc_tests/ec2/test_telemetry.py

Minor fix on telemetry fixture and update skip logging

---

dlc_developer_config.toml
test/sagemaker_tests/huggingface/inference/integration/local/test_serving.py

**Note**: 
- hf_pt-inference-latest-dlc-sagemaker-local-test is constantly failing due to 
```
Failed to launch via g5.12xlarge reservation - An error occurred (ReservationCapacityExceeded) when calling the RunInstances operation: The requested reservation does not have sufficient compatible and available capacity for this request.
```
- We use a common instance type across many different tests in the DLC repo ([example](https://github.com/aws/deep-learning-containers/blob/31ea42c3540dabb6f5b9bc61b93ec5433ef4e4a3/test/test_utils/sage …

skip hf_pt-inference-latest-dlc-sagemaker-local-test temporarily for HF PT Inference latest image

---

autogluon/inference/docker/1.2/py3/Dockerfile.cpu.os_scan_allowlist.json
autogluon/inference/docker/1.2/py3/cu124/Dockerfile.gpu.os_scan_allowlist.json
autogluon/training/docker/1.2/py3/Dockerfile.cpu.os_scan_allowlist.json
autogluon/training/docker/1.2/py3/cu124/Dockerfile.gpu.os_scan_allowlist.json
dlc_developer_config.toml

**Note**: 
Add exception for LightGBM vulnerability for AutoGluon training and inference images as autogluon uses LightGBM versions >=4.5.0
<details>
- Run default builds and tests for a …

Fix vulnerabilities AutoGluon v1.2

---

available_images.md
release_images_inference.yml
release_images_training.yml

Release AutoGluon v1.2

---

release_images_patches.yml

Add PT2.6 x86 Inf EC2 to release

---

dlc_developer_config.toml
huggingface/pytorch/training/docker/2.3/py3/cu121/Dockerfile.gpu

**Note**: 
- Patch CVE-2024-47685 vulnerability related to `linux-libc-dev`
- Patch CVE-2022-48337 vulnerability related to `emacs` and `emacs-common`
<details>
- Run default builds and …

chore: patch emacs and libc vulnerabilities for HF pytorch training

---

dlc_developer_config.toml
tensorflow/training/buildspec-2-18-sm.yml
tensorflow/training/docker/2.18/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
tensorflow/training/docker/2.18/py3/cu125/Dockerfile.sagemaker.gpu.os_scan_allowlist.json

Enable TF 2.18 SM autopatch

---

release_buildspec.yml

Remove qemu for arm64/graviton release
**Note**: 
<details>
`python …

Remove qemu for arm64/graviton release

---

test/sagemaker_tests/huggingface_pytorch/training/conftest.py

**Note**: 
Fixes test for huggingface-pytorch-training since the infra isn't setup in eu-west-1
<details>
- Run default builds and tests for a particular buildspec - also commits and …

remove eu-west-1 from test regions

---

src/image_builder.py

fix common stage build

---

src/image.py
src/image_builder.py

remove cache_from_tag

---

dlc_developer_config.toml
miscellaneous_scripts/dockerfile_patch_script.sh
pytorch/training/docker/2.7/py3/Dockerfile.sagemaker.cpu.core_packages.json
pytorch/training/docker/2.7/py3/Dockerfile.sagemaker.cpu.py_scan_allowlist.json
pytorch/training/docker/2.7/py3/cu128/Dockerfile.sagemaker.gpu.core_packages.json
pytorch/training/docker/2.7/py3/cu128/Dockerfile.sagemaker.gpu.py_scan_allowlist.json

**Note**: 
- [e8062aa](https://github.com/aws/deep-learning-containers/pull/4976/commits/e8062aa4533e8b50d08bb05eb6c12abd2a02be4e) Passed all tests
<details>
- Run default builds and tests …

Patch PyTorch 2.7 sagemaker package

---

release_images_general.yml

Add cu128 ul22 base image to release

---

test/testrunner.py
test/vllm/eks/eks_test.py

**Note**: 
Enable vLLM test for EC2 and EKS platforms on pipeline context.
<details>
- Run default builds and tests for a particular …

enable vLLM EKS EC2 test on pipeline

---

release_images_general.yml
vllm/CHANGELOG.md
vllm/buildspec.yml
vllm/x86_64/gpu/Dockerfile

update vllm to v0.10.1
<details>
`python …

update vllm to v0.10.1

---

dlc_developer_config.toml
test/testrunner.py
test/vllm/trigger_test.py

Add condition to check instance type for VLLM EC2

---

dlc_developer_config.toml
pytorch/training/buildspec-2-7-sm.yml
pytorch/training/docker/2.7/py3/Dockerfile.cpu
pytorch/training/docker/2.7/py3/Dockerfile.sagemaker.cpu.core_packages.json
pytorch/training/docker/2.7/py3/cu128/Dockerfile.gpu
pytorch/training/docker/2.7/py3/cu128/Dockerfile.sagemaker.gpu.core_packages.json
src/image.py

**Note**: 
- Disable autopatch for PT 2.7 and enable Buildx for PT Training
- Passed efa tests [1a668bb](https://github.com/aws/deep-learning-containers/pull/5184/commits/1a668bb62494c33d01148bf4cba6f540df544ff6)
- Passed all tests [7a1924a](https://github.com/aws/deep-learning-containers/pull/5184/commits/7a1924a8513555a5df737ba7fd933fcdb30851dc)
2. Using this PR description (currently only supported for …

Disable PT 2.7 Autopatch and Onboard BuildX

---

test/vllm/trigger_test.py

add pr context and modify condition

---

release_images_general.yml
vllm/CHANGELOG.md
vllm/buildspec.yml

change vllm release version

---

base/x86_64/gpu/cu128/ubuntu22.04/Dockerfile
dlc_developer_config.toml

Build Base cu128 with sqlite

---

dlc_developer_config.toml
test/requirements.txt

Pin boto3 and awscli versions in test

---

dlc_developer_config.toml
test/requirements.txt

Pin pytest-rerunfailures versions

---

available_images.md

add PT 2.8 images to available images

---

dlc_developer_config.toml
vllm/buildspec.yml
vllm/x86_64/gpu/Dockerfile

update vllm x86 to 0.10.2

---

release_images_training.yml

add huggingface pytorch training 2.7.1 release config

---

available_images.md

[djl] update available_images.md with LMI V16

---

release_images_training.yml

Release HF PT Training 2.8
