aws/deep-learning-containers

- mxnet/inference/docker/1.6.0/py2/Dockerfile.cpu
- mxnet/inference/docker/1.6.0/py2/Dockerfile.gpu
- mxnet/inference/docker/1.6.0/py3/Dockerfile.cpu
- mxnet/inference/docker/1.6.0/py3/Dockerfile.gpu
- mxnet/training/docker/1.6.0/py2/Dockerfile.cpu
- mxnet/training/docker/1.6.0/py2/Dockerfile.gpu
- mxnet/training/docker/1.6.0/py3/Dockerfile.cpu
- mxnet/training/docker/1.6.0/py3/Dockerfile.gpu
MXNet build is failing for PY2 due to setuptools packages
Sanity test is failing due to various outdated packages
*Description:*
*Tests run:*
> [MXNet][Sanity Test]Updated packages for MXNet

- test/dlc_tests/container_tests/bin/pytorch_tests/testPyTorchRegression
> [pytorch] | [test] | [ec2]Remove the temp patch for PT example tests

- test/dlc_tests/container_tests/bin/benchmark/get_mxnet_avg_throughput.py
> [pytorch] | [test] | [sanity] nit for mxnet benchmark helper script

- release_images.yml
Making changes to release PT 1.4.0 
*Description:*
*Tests run:*
> Release Images Changes for PyTorch 1.4.0

- pytorch/buildspec.yml
- pytorch/inference/docker/1.4.0/py3/Dockerfile.cpu
- pytorch/inference/docker/1.4.0/py3/Dockerfile.gpu
- pytorch/training/docker/1.4.0/py3/Dockerfile.cpu
- pytorch/training/docker/1.4.0/py3/Dockerfile.gpu
> [pytorch] | [build, test] | [ec2, ecs, eks, sagemaker] Update py36 version to python3.6.10 for PT1.4 Images

- release_images.yml
*Description:*
Release logic change for PT14 patch release
*Tests run:*
> [pytorch] Release logic change for PT14 patch release

- test/dlc_tests/eks/mxnet/training/test_eks_mxnet_multinode_training.py
- test/dlc_tests/eks/tensorflow/training/test_eks_tensorflow_multi_node_training.py
> [mxnet, tensorflow] | [build, test] | [eks] Remove assertion for EKS multinode training

- test/dlc_tests/benchmark/sagemaker/tensorflow/training/test_performance_tensorflow_sm_training.py
> [tensorflow] [build] [sanity] Disable SM benchmark

- tensorflow/training/docker/2.2.0/py3/Dockerfile.cpu
- tensorflow/training/docker/2.2.0/py3/cu101/Dockerfile.gpu
> [tensorflow,] | [build, test] | [sanity, ec2, ecs, eks, sagemaker]Upgrade Horovod for TF22 CUDA10.1 and CPU Images

- release_images.yml
*Description:*
Release logic change
*Tests run:*
> [tensorflow] | [release] TF22 CUDA10.1 release logic

- test/dlc_tests/conftest.py
> [tensorflow] | [test] | [ec2] Add instance space for TF horovod ec2 test working instance

- tensorflow/inference/docker/2.0.2/py2/Dockerfile.cpu
- tensorflow/inference/docker/2.0.2/py2/Dockerfile.gpu
- tensorflow/inference/docker/2.0.2/py3/Dockerfile.cpu
- tensorflow/inference/docker/2.0.2/py3/Dockerfile.gpu
- tensorflow/training/docker/2.0.2/py2/Dockerfile.cpu
- tensorflow/training/docker/2.0.2/py2/Dockerfile.gpu
- tensorflow/training/docker/2.0.2/py3/Dockerfile.cpu
- tensorflow/training/docker/2.0.2/py3/cu100/Dockerfile.gpu
> [tensorflow] | [build, test] | [sanity, ec2, eks, ecs, sagemaker] Upgrade openssl to 1.1.1g for TF202 and Fix Tensorboard Issue

- test/dlc_tests/sanity/test_pip_check.py
> [test] | [sanity] change: Re-enable TF inference pip check test

- release_images.yml
*Description:*
Release for Tf2.0.2
*Tests run:*
> [tensorflow][release]Release For TF2.0.2

- pytorch/buildspec.yml
- pytorch/inference/docker/1.5.1/py3/Dockerfile.cpu
- pytorch/inference/docker/1.5.1/py3/Dockerfile.gpu
- pytorch/training/docker/1.5.1/py3/Dockerfile.cpu
- pytorch/training/docker/1.5.1/py3/Dockerfile.gpu
- pytorch/training/docker/1.5.1/py3/example/Dockerfile.gpu
> [pytorch] [release] Updating PT binaries for 1.5.1

- test/dlc_tests/benchmark/sagemaker/tensorflow/training/test_performance_tensorflow_sm_training.py
> Enable TF SM Benchmark

- README.md
*Description:*
1. Add steps to run the sagemaker tests in local or dev desktops 
*Tests run:* 
> update readme with steps to run sagemaker tests in local

- mxnet/training/docker/1.6.0/py2/Dockerfile.cpu
- mxnet/training/docker/1.6.0/py2/Dockerfile.gpu
- mxnet/training/docker/1.6.0/py2/example/Dockerfile.gpu
- mxnet/training/docker/1.6.0/py3/Dockerfile.cpu
- mxnet/training/docker/1.6.0/py3/Dockerfile.gpu
- mxnet/training/docker/1.6.0/py3/example/Dockerfile.gpu
*Description:*
Updating horovod version in MXNet
*Tests run:*
> [MXNet][Build,Test]Horovod version update

- test/dlc_tests/eks/mxnet/training/test_eks_mxnet_multinode_training.py
- test/test_utils/__init__.py
*Description:*
Skipping the EKS multinode for temporary basics.
*Tests run:*
> [MXNet][Test][EKS]Skipping multinode EKS test

- mxnet/inference/docker/1.6.0/py2/Dockerfile.cpu
- mxnet/inference/docker/1.6.0/py2/Dockerfile.gpu
- mxnet/inference/docker/1.6.0/py3/Dockerfile.cpu
- mxnet/inference/docker/1.6.0/py3/Dockerfile.gpu
- mxnet/training/docker/1.6.0/py2/Dockerfile.cpu
- mxnet/training/docker/1.6.0/py2/Dockerfile.gpu
- mxnet/training/docker/1.6.0/py3/Dockerfile.cpu
- mxnet/training/docker/1.6.0/py3/Dockerfile.gpu
> [mxnet] [build, test] [ec2, ecs, eks, sagemaker] Upgrade openssl for MXNet 1.6.0

- tensorflow/training/docker/1.15.2/py3/Dockerfile.cpu
- tensorflow/training/docker/1.15.2/py3/Dockerfile.gpu
- tensorflow/training/docker/1.15.2/py36/Dockerfile.cpu
- tensorflow/training/docker/1.15.2/py36/Dockerfile.gpu
- tensorflow/training/docker/1.15.3/py3/Dockerfile.cpu
- tensorflow/training/docker/1.15.3/py3/Dockerfile.gpu
- tensorflow/training/docker/1.15.3/py36/Dockerfile.cpu
- tensorflow/training/docker/1.15.3/py36/Dockerfile.gpu
*Description:*
Upgrade pillow for TF1 PY3 Training images
> [tensorflow] | [build, test] Upgrade pillow for TF1 PY3 Training images

- mxnet/buildspec-eia.yml
- tensorflow/buildspec-eia.yml
- tensorflow/buildspec-tf1-eia.yml
> [mxnet, tensorflow] | [eia] fix device_type for eia

- test/dlc_tests/eks/pytorch/inference/test_eks_pytorch_inference.py
- test/dlc_tests/eks/tensorflow/inference/test_eks_tensorflow_inference.py
- test/dlc_tests/sanity/test_generate_coverage_doc.py
> Minor syntax correction 

- test/dlc_tests/eks/mxnet/training/test_eks_mxnet_multinode_training.py
> [MXNet][EKS]Skipping of EKS Multinode for temporary basis

- release_images.yml
*Description:*
Release of TF2.2 with Training 10.1 and Inference 10.2
*Tests run:*
> [Tensorflow][Release]Release of training 10.1 and Inference 10.2

- tensorflow/buildspec.yml
> [Build][Tensorflow]Change for buildspec in TF2.2 CUDA 10.2

- release_images.yml
> [release] | [mxnet] Release logic for MX16

- release_images.yml
*Description:*
Release logic for tf22 cu102
> [tensorflow] | [release] Release logic for tf22 cu102

- release_images.yml
*Description:*
Release need to re-trigger because we encountered an issue during training images release. We should merge this PR in once training image release stage finish.
> [tensorflow] [release] Update release_images.yml with only inference images

- tensorflow/buildspec-tf1.yml
- tensorflow/inference/docker/1.15.3/py3/Dockerfile.cpu
- tensorflow/inference/docker/1.15.3/py3/Dockerfile.gpu
- tensorflow/inference/docker/1.15.3/py36/Dockerfile.cpu
- tensorflow/inference/docker/1.15.3/py36/Dockerfile.gpu
*Description:*
Allowing the creation of Tf1 Inference Images.
> [Tensorflow][Build]buildspec Tf1 Inference Changes

- test/dlc_tests/ec2/test_smdebug.py
> [tensorflow] | [test] | [ec2] Disable SMDebug tests for TF1 temp

- .github/PULL_REQUEST_TEMPLATE.md
- src/config/build_config.py
- src/main.py
*Description:*
Setup the PR environment for EIA. 
Provide with a manual switch for building system. 
Add related items in PR template.
*Tests run:*
> [ei] Setup EIA PR context related work env

- release_images.yml
> [Tensorflow]Indentation issue

- release_images.yml
> [release] | [pytorch] Update release logic in favor of PT 1.6 release

- available_images.md
*Description:*
Update available.md for PT1.6 training images
> [readme] | [pytorch] update available.md for PT1.6 training images

- available_images.md
*Description:*
update available_images.yml for pytorch
> [readme] update available_images.yml for pytorch

- release_images.yml
*Description:*
- TF 2.3 release
- TF2.3 py3 gpu cu102 training image
- TF2.3 py3 cpu training image
> [release] tf2.3 release

- test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py
> [testing] skip PT AMP test for g3.4xlarge with 1 GPU

- release_images.yml
*Description:*
tf2.2 cu101 release
> [tensorflow] | [release]  tf2.2 cu101 release

- tensorflow/buildspec.yml
*Description:*
build and test tensorflow2.2 cuda10.2 training images with SMDebug 0.9.2
> [tensorflow] | [build, test] build and test tensorflow2.2 cuda10.2 training images with SMDebug 0.9.2

- bjs_release_buildspec.yml
- extended_release_buildspec.yml
*Description:*
buildspecs needed for BJS releases
*Tests run:*
Tested on personal setup
N/A
N/A
> [release] Add new buildspecs for releases

- mxnet/inference/docker/1.6.0/py3/Dockerfile.cpu
- mxnet/inference/docker/1.6.0/py3/cu101/Dockerfile.gpu
*Description:* Update to https://github.com/dmlc/gluon-nlp/releases/tag/v0.10.0
*Tests run:*
> [mxnet] Update to GluonNLP 0.10

- test/dlc_tests/ec2/mxnet/inference/test_mxnet_inference.py
- test/dlc_tests/ec2/mxnet/training/test_mxnet_training.py
*Description:*
We are noticing performance test failure occasionally , have asked the required team to have a look at it. Meanwhile, increasing the rerun of this test
*Tests run:*
> [MXNet][ec2]Having reruns for telemetry in MXNet

- mxnet/inference/docker/1.5.1/py2/Dockerfile.eia
- mxnet/inference/docker/1.5.1/py3/Dockerfile.eia
- src/config/build_config.py
> [MXNet][EIA]Update EIA wheel in MXNet

- tensorflow/buildspec.yml
*Description:*
This is a PR to set TF buildspec to build TF 2.2.0 Training DLC images for CPU, and GPU with CUDA 10.1
*Tests run:*
N/A
N/A
N/A
> [build] [tensorflow] Build TF 2.2 cu101

- src/deep_learning_container.py
*Description:*
Adding Telemetry Script in the main repo.
Will Create a seperate PR to make use of this script in all the dockerfile 
*Tests run:*
> [Telemetry][Build]Addition of Telemetry script

- release_images.yml
*Description:*
Adding Pytorch EIA in ReleaseSpec
*Tests run:*
> [EIA][Pytorch][Release]Addition of pytorch EIA in releaseSpec

- release_images.yml
*Description:*
Removing PT EIA from buildspec
> [Cleanup][Post Release]Removing PT EIA from buildspec

- test/dlc_tests/eks/eks_manifest_templates/kubeflow/install_kubeflow.sh
- test/test_utils/eks.py
*Description:*
- Cleanup kfctl code as it is used in install_kubeflow.sh script.
- Remove echo statement.
> cleanup kubeflow components

- release_images.yml
*Description:*
- PT 1.6 inference with torchserve release
- PT-1.6 py3 gpu cu101 inference image
- PT-1.6 py3 cpu inference image
> [release] PT-1.6 inference release

- release_images.yml
*Description:*
- MXNET-1.7 release: Fix the incorrect indentation on #588 
> [release] fix indentation for mx-1.7 release images

- tensorflow/buildspec.yml
*Description:*
- Update buildspec to build TF2.3 images
> [tensorflow] Update TF2 buildspec to build TF2.3 images

- tensorflow/buildspec.yml
*Description:*
- Build TF2.2 images in order to build/test TF2.2 with smdebug 0.9.3
> [tensorflow] Build TF2.2 images

- release_images.yml
*Description:*
- Updating release yaml
*Tests run:*
- linted release yaml manually
> [release] complete the TF2.3 Inference release

- release_images.yml
*Description:*
- Removing force release from all locations
*Tests run:*
- ran linter locally
> [release] Set force_release to false in release images yml file

- test/dlc_tests/container_tests/bin/testSmdebug
*Description:*
- TF 2.x doesn't clear GPU memory unless the process is completely killed.
- When running multiple tests with pytest all the GPU memory is held by the parent pytest process and hence the likelihood that GPU runs OOM is high.
- This PR assigns a different pytest runner for each test file, thereby reducing the chance of a GPU OOM
*Tests run:* …
>  [mxnet, tensorflow, pytorch] [test]Run Smdebug Tests In a Loop

- tensorflow/buildspec.yml
*Description:*
- Update buildspec back to TF 2.3 for re-release
> [build][tensorflow] Update buildspec to tf2.3

- release_images.yml
*Description:*
- Update in order to release TF 2.3 images
*Tests run:*
- ran linter locally
> [release] Update TF2.3 release images

- release_images.yml
- tensorflow/buildspec.yml
*Description:*
- Update buildspec for TF2.2, set force release back to false
*Tests run:*
local yaml linter
> [build][tensorflow] Update buildspec for TF2.2

- test/sagemaker_tests/pytorch/inference/integration/__init__.py
- test/sagemaker_tests/pytorch/training/integration/__init__.py
- test/sagemaker_tests/pytorch/training/integration/local/test_single_machine_training.py
Use existing fixture instead of manual check in PT SM test
*Description:*
*Tests run:*
> [pytorch] [sagemaker] [test] drop py3 manual check in favor of fixture

- tensorflow/buildspec.yml
- tensorflow/training/docker/2.1.1/py3/Dockerfile.cpu
- tensorflow/training/docker/2.1.1/py3/cu101/Dockerfile.gpu
*Description:*
Updated buildspec.yml for tf 2.1.1 and py 3.6
*Tests run:*
Executed locally
> [tensorflow][build] Updated buildspec.yml for tf 2.1.1 and py 3.6

- post_release_buildspec.yml
*Description:*
Invoke a post-release step to validate the DLC tags on released images in the post_release_buildspec.yml file
*Tests run:*
Script tested locally after releases for multiple frameworks and versions
N/A
N/A
> [release] Add post-release validation step

- post_release_buildspec.yml
*Description:*
Added `start-dockerd` to list of pre-build commands to be run on post_release_buildspec.yml to prevent the error:
```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
*Tests run:*
N/A
N/A
> [release] Update post_release_buildspec.yml

- release_images.yml
*Description:*
Change release_images.yml to release TF 2.2.1 images
*Tests run:*
N/A
N/A
N/A
> [release] [tensorflow] Release TensorFlow 2.2.1

- release_images.yml
*Description:*
- Update release images to release tf 2.2.1 cu102 images.
*Tests run:*
- Ran local linter tool
> [release] Release TF2.2.1 cu102 images

- release_images.yml
*Description:*
Update release for TF 2.3.1 training containers (gpu is cu102)
*Tests run:*
Ran local linter tool
> [release] Release TF 2.3.1 training containers

- test/dlc_tests/sanity/test_safety_check.py
*Description:*
Move security checks to 'mainline' pipelines
*Tests run:*
> [test] Move safety checks to mainline builds

- available_images.md
*Description:*
Minor documentation fix. GPU and CPU were swapped.
> Fixed minor documentation bug

- test/dlc_tests/container_tests/bin/testSmdebug
*Description:*
- Changing the way mxnet tests are run due to a state error. 
- Pinning the version of tensorflow_datasets for tf 1.x
*Tests run:*
> [test] Fix smdebug mxnet tests

- release_images.yml
*Description:*
Update release_images.yml to include force_release on PyTorch Inference GPU image
*Tests run:*
N/A
N/A
N/A
> [release] Update PyTorch 1.6 images to be released

- pytorch/buildspec.yml
*Description:*
Change buildspec to build PyTorch 1.5.1 images
*Tests run:*
N/A
N/A
N/A
> [build] Build PyTorch 1.5.1 images

- test/sagemaker_tests/pytorch/inference/requirements.txt
- test/sagemaker_tests/pytorch/training/requirements.txt
*Description:*
Upgraded requests==2.24 to resolve urllib3 versions compatibility conflict
*Tests run:*
executed locally
> [test][pytorch] Updated requests version

- test/dlc_tests/benchmark/ec2/pytorch/training/test_performance_pytorch_training.py
- test/dlc_tests/ec2/tensorflow/training/test_tensorflow_training.py
- test/dlc_tests/ecs/pytorch/inference/test_ecs_pytorch_inference.py
- test/dlc_tests/ecs/pytorch/training/test_ecs_pytorch_training.py
- test/dlc_tests/ecs/tensorflow/inference/test_ecs_tensorflow_inference.py
- test/dlc_tests/ecs/tensorflow/training/test_ecs_tensorflow_training.py
- test/test_utils/ec2.py
- test/test_utils/sagemaker.py
*Description:*
Adding skips to flaky tests
> [test][tensorflow, pytorch] Skip flaky pytorch performance test and flaky TF1 functional tests

- release_images.yml
*Description:*
Update release images yaml file for cuda11 releases
*Tests run:*
Ran local linter
> [release] Prepare cuda11 pytorch and tf1 releases

- release_images.yml
*Description:*
Update release_images.yml to rekease MXNet 1.6.0 images
*Tests run:*
> [release] Release MX 1.6 on release_images

- release_images.yml
> [tensorflow][release] Added tf 2.3.1. cuda11 into release_images.yml

- release_images.yml
*Description:*
Set force_release to `False` for mxnet 1.6 images
*Tests run:*
> [release] Update release_images.yml

- release_images.yml
*Description:*
Release PyTorch 1.5.1 images with force release
*Tests run:*
> [release] Release PT 1.5.1 images

- test/dlc_tests/conftest.py
- test/dlc_tests/sanity/test_security_check.py
- test/requirements.txt
- test/test_utils/ecr.py
*Description:*
Add a test for all images that uses the ECR Scan tool to determine if there are any vulnerabilities to be addressed on the packages installed in an image.
*Tests run:*
> [test] Add test to get ECR scan findings

- release_images.yml
> [release] Set TF 1.15 to CUDA 10.0 on release_images

- release_images.yml
*Description:*
Set TF 1.15 cu100 images to be force released
*Tests run:*
> [release] Set release for TF 1.15 cu100

- release_images.yml
*Description:*
Change release_images.yml to release TF 2.2.1 cu102 images
*Tests run:*
> [release] Release TF 2.2.1 cu102 images

- test/test_utils/__init__.py
> [test][mxnet, tensorflow, pytorch] A fix for canaries regex.

- release_images.yml
> [tensorflow][release]Update release_images.yml to release tf 2.1.2

- test/sagemaker_tests/tensorflow/tensorflow1_training/integration/local/test_training.py
> [tensorflow][sagemaker][test]Skipping tf1.15 sagemaker local  test

- release_images.yml
> [tensorflow][release] release_images.yml for releasing tf 1.15 cu11

- tensorflow/buildspec.yml
- tensorflow/training/docker/2.0/py3/Dockerfile.cpu
- tensorflow/training/docker/2.0/py3/cu100/Dockerfile.gpu
- test/dlc_tests/sanity/test_safety_check.py
*Description:*
Updated Pillow version to 7.2.0 on TF 2.0 Training dockerfiles to resolve Safety Check vulnerabilities
*Tests run:*
https://github.com/aws/deep-learning-containers/blob/master/tensorflow/training/docker/2.0/py3/Dockerfile.cpu
https://github.com/aws/deep-learning-containers/blob/master/tensorflow/training/docker/2.0/py3/cu100/Dockerfile.gpu
> [tensorflow] [build] Upgrade Pillow to 7.2 on TF 2.0

- release_images.yml
> [tensorflow][release]Tf 1.15 release

- release_images.yml
> [tensorflow] [release] Release TF 1.15.4 cu100 images

- release_images.yml
*Description:*
Force releasing an example image to match the training image version
*Tests run:*
> [tensorflow][relase]Force release for tf1.15 example image

- release_images.yml
*Description:*
Removed py36 from the list of released images to release py37 only
*Tests run:*
> [release] Removed py36 from the TF 1.15.4 released images

- release_images.yml
*Description:*
Add TF 1.15 Neuron image to release_images.yml
*Tests run:*
> [release] [neuron] Add TF 1.15 neuron to release_images

- release_images.yml
*Description:*
Disable SM tags on Neuron images in release_images.yml
*Tests run:*
> [release] Disable sm tag on Neuron release

- available_images.md
*Description:*
Update available_images.md to reflect latest DLC releases
*Tests run:*
> [doc] Update available_images to latest

- LICENSE
- README.md
*Description:*
Add specific information about new SageMaker features to README and LICENSE
*Tests run:*
> [doc] Add DLC license updates

- available_images.md
*Description:*
Add new available images for Neuron-based Inference to available_images.md
*Tests run:*
N/A
N/A
https://github.com/aws/deep-learning-containers/releases/tag/v1.1-tf-1.15.4-inf-neuron-py37
> [doc] Add new Neuron inference images to Available Images

- available_images.md
*Description:*
Update available_images.md file with PyTorch 1.5.1 EI DLC image
*Tests run:*
N/A
N/A
https://github.com/aws/deep-learning-containers/releases/tag/v1.0-pt-1.5.1-inf-eia-py36
> [doc] Update available_images with PyTorch 1.5.1 EI

- release_images.yml
*Description:*
Update release_images.yml to release TF 2.3.1 CPU and GPU CU110 images
*Tests run:*
> [release][tensorflow] Update to release TF 2.3.1

- pytorch/training/docker/1.7.1/py3/cu110/Dockerfile.gpu
*Description:*
Add SMDDP library corresponding to PT 1.7.1
*Tests run:*
smddp sm tests specific to PT
> [pytorch][sagemaker] PT1.7.1 - Sagemaker distributed dataparallel integration

- pytorch/training/docker/1.7.1/py3/cu110/Dockerfile.gpu
- test/sagemaker_tests/pytorch/training/integration/sagemaker/test_distributed_operations.py
- [ X] I've prepended PR tag with frameworks/job this applies to : [mxnet, tensorflow, pytorch] | [ei/neuron] | [build] | [test] | [benchmark] | [ec2, ecs, eks, sagemaker]
- [X ] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ X] (If applicable) I've documented below the tests I've run on the DLC image
- [ X] (If applicable) I've reviewed the licenses of updated and new binaries and their dependencies to make sure all licenses are on the Apache Software Foundation Third Party License Policy Category A or Category B license list.  See [https://www.apache.org/legal/resolved.html](https://www.apache.org/legal/resolved.html).
- [X ] (If applicable) I've scanned the updated and new binaries to make sure they do not have …
> [pytorch] [build] | [test] SMD MP PT 1.7.1 changes

- tensorflow/buildspec.yml
- test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_smdataparallel.py
> [build][tensorflow] Build TF 2.3.1 CUDA 10.2

- release_images.yml
- test/dlc_tests/sanity/test_safety_check.py
*Description:*
Release TF 2.3 CUDA 10.2 image
*Tests run:*
> [release] Release TF 2.3 cu102

- release_images.yml
*Description:*
Set force release to true for TF 2.3.1 cuda 10.2
*Tests run:*
> [release] Force TF 2.3 cuda 10.2 release

- release_images.yml
> [tensorflow][release]Releasing tf 1.15.4 gpu

- available_images.md
*Description:*
Update available_images.md with the latest PyTorch 1.7.1 DLC Image URIs
*Tests run:*
> [doc] Update available images with PT 1.7.1

- tensorflow/training/docker/2.4/py3/Dockerfile.cpu
- tensorflow/training/docker/2.4/py3/cu110/Dockerfile.gpu
- test/dlc_tests/ec2/tensorflow/training/test_tensorflow_training.py
- test/dlc_tests/ec2/test_smclarify.py
- test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_smdataparallel.py
*Description:*
Address nit comments from https://github.com/aws/deep-learning-containers/pull/783
*Tests run:*
> [tensorflow][build,test] Update TF 2.4 dockerfile and tests

- release_images.yml
*Description:*
- Release configuration for PT-1.7.1 inference CPU/GPU candidates.
> [release] release config for PT-1.7.1 inference

- release_images.yml
> [release] PT 1.7 inf release: remove example training image config

- tensorflow/buildspec.yml
- tensorflow/training/docker/2.3/py3/Dockerfile.cpu
- tensorflow/training/docker/2.3/py3/cu102/Dockerfile.gpu
- tensorflow/training/docker/2.3/py3/cu110/Dockerfile.gpu
*Description:*
- Bumping the version of the smdebug to `1.0.3`
*Tests run:*
```
763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-training:2.3.1-cpu-py37-ubuntu18.04
763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-training:2.3.1-gpu-py37-cu110-ubuntu18.04
763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-training:2.3.1-gpu-py37-cu102-ubuntu18.04
```
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and …
> [tensorflow][build] Update smdebug version to 1.0.3

- release_images.yml
*Description:*
- Force release example image for TF 1.15.4
> [release] modify force release tag for TF1.15.4

- release_images.yml
*Description:*
- Release MXNET EIA v1.7.0 Inference container
> [release] mxnet-1.7.0 EIA release

- release_images.yml
*Description:*
- remove old candidates from release_images.yml
> [release] remove old candidates from release_images.yml

- release_images.yml
*Description:*
Release candidates for
- TF 2.3.1 - CU102 - Training/Inference - CPU/GPU/Example
- TF 1.15.4 - CU100 - Training/Inference - CPU/GPU/Example
- TF 1.15.4 - Inference - Neuron
- TF 1.15.0 - Inference - EIA
- MX 1.7.0 - CU101 - Training/Inference - CPU/GPU/Example
*Tests run:*
> [release] release TF2.3, MX1.7 and TF1.15

- release_images.yml
> [release] fix quote

- release_images.yml
*Description:*
- TF 2.2.1 - CUDA 102 - Training/Inference - CPU/GPU/Example
- TF 2.0.0 - Inference - EIA
- Remove TF 1.15 neuron entry.
> release tf2.2 cu102

- release_images.yml
*Description:*
Release candidates for
- TF 2.3.1 - CU110 - Training- GPU/Example
> [release] release TF2.3 cu110

- release_images.yml
*Description:*
Release candidates for
TF 1.15.4 - CU110 - Training- GPU/Example
TF 2.2.1 - CU101 - Training- GPU/Example
> [release] Update release config for TF1.15, TF 2.2

- release_images.yml
*Description:*
- Release PT v1.7.1 Training/Inference image.
> [release] release PT1.7.1 images

- available_images.md
*Description:*
Add the Image URI for the MXNet 1.7.0 EI DLC
*Tests run:*
> [doc] Add MX 1.7.0 EI DLC to available_images.md

- release_images.yml
- test/dlc_tests/sanity/test_security_check.py
- [x ] I've prepended PR tag with frameworks/job this applies to : [mxnet, tensorflow, pytorch] | [ei/neuron] | [build] | [test] | [benchmark] | [ec2, ecs, eks, sagemaker]
*Description:*
Update for release_images.yml to release pt 1.6 images
*Tests run:*
> [pytorch][release]Update for release_images.yml to release pt 1.6 images

- release_images.yml
*Description:*
Add TensorFlow 2.4.1 to release_images.yml
*Tests run:*
> [release] [tensorflow] Add TF 2.4.1 to release_images

- test/sagemaker_tests/pytorch/training/integration/sagemaker/test_distributed_operations.py
*Description:*
Enable the SMDDP PT test and enable smdebug for the test.
*Tests run:*
> [pytorch][test] Enable PT SMDDP sagemaker test with smdebug

- test/dlc_tests/ec2/tensorflow/training/test_tensorflow_training.py
*Description:*
Fix keypair name collisions on TF training tests
*Tests run:*
> [test][tensorflow] Resolve keypair name collisions on tf train EC2 tests

- release_images.yml
*Description:*
Add TF 1.15.5 Neuron and PT 1.5.1 Neuron DLCs to release_images.yml
*Tests run:*
> [release] Add TF 1.15.5 and PT 1.5.1 to release_images

- release_images.yml
*Description:*
Make corrections to TF 1.15.5 and PT 1.5.1 release_images spec for TF and PT Neuron
*Tests run:*
> [release] Correct TF 1.15.5 and PT 1.5.1 neuron release_images spec

- release_images.yml
*Description:*
Add TF 2.4.1 Inference DLCs to release_images.yml
*Tests run:*
> [release] Add TF 2.4.1 inference to release_images

- test/dlc_tests/ec2/mxnet/inference/test_mxnet_inference.py
- test/dlc_tests/ec2/mxnet/training/test_mxnet_training.py
- test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference.py
- test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py
- test/dlc_tests/ec2/tensorflow/inference/test_tensorflow_inference.py
- test/dlc_tests/ec2/tensorflow/training/test_tensorflow_training.py
- test/dlc_tests/ec2/test_curand.py
- test/dlc_tests/ec2/test_smdebug.py
- test/test_utils/__init__.py
- [x ] I've prepended PR tag with frameworks/job this applies to : [mxnet, tensorflow, pytorch] | [ei/neuron] | [build] | [test] | [benchmark] | [ec2, ecs, eks, sagemaker]
*Description:*
Fix test skip logic for p4d instances with CUDA 10 images
*Tests run:*
Tested by running a `test_tensorflow_train_mnist_gpu` with a CUDA 10 DLC on a p4d instance as well as a p3.2xlarge instance, and a CUDA 11 DLC on a p4d instance as well as a p3.2xlarge instance
> [test][ec2] Fix p4d test skip logic

- release_images.yml
*Description:*
Add TF 2.3.2 to release_images.yml
*Tests run:*
> [release] Add TF 2.3.2 to release images

- release_images.yml
*Description:*
- release TF1.15.5 CU100 images 
> [release] release TF1.15.5 CU100 images 

- release_images.yml
*Description:*
- Release MX 1.6.0 images
> [release] release MX 1.6.0 images

- release_images.yml
*Description:*
-  Release TF1.15.5 CU110 Training images
> [release] release TF1.15.5 CU110 Training images

- release_images.yml
*Description:*
- Release TF v2.2.2 CU101 Training images
> [release] release TF2.2.2 CU101 Training images

- release_images.yml
*Description:*
Add all TF 2.4.1 DLC images to release_images.yml
*Tests run:*
> [release] Add all TF 2.4.1 to release images

- release_images.yml
*Description:*
- Release TF2.2.2 CU102 Training images
> [release] release TF2.2.2 CU102 Training images

- release_images.yml
*Description:*
-  Release TF 2.0.4 Training images
> [release] release TF 2.0.4 Training images

- test/sagemaker_tests/pytorch/training/resources/mnist/smdataparallel_mnist.py
> [PyTorch][Test][SageMaker] Fixed Dataset not found error on PyTorch MNIST dataset

- tensorflow/buildspec-tf1.yml
- tensorflow/inference/docker/1.15/py36/Dockerfile.cpu
- tensorflow/inference/docker/1.15/py36/cu100/Dockerfile.gpu
*Description:*
Add TF 1.15 Inference DLCs to buildspec
*Tests run:*
> [tensorflow][build] Build TF 1.15 inference DLCs

- release_images.yml
*Description:*
Add TF 2.2.2 inference CPU and GPU images to release_images.yml
*Tests run:*
> [release] Release TF 2.2.2 inference DLCs

- release_images.yml
*Description:*
Add TF 2.1.3 to release_images.yml
*Tests run:*
> [release] Release TF 2.1.3 DLC images

- release_images.yml
*Description:*
Add TF 2.0.4 inference DLCs to release_images.yml
*Tests run:*
> [release] Release TF 2.0.4 inference

- available_images.md
*Description:*
Update available_images.md to add new patch versions for TF 2.3, 2.2, 2.0, 1.15
*Tests run:*
> [doc] Update latest available images

- release_images.yml
*Description:*
Add PT 1.3.1 EI DLC to release_images.yml
*Tests run:*
> [release] Release PT 1.3.1 EI DLC

- release_images.yml
*Description:*
- Release PT v1.4.0 images
> [release] release PT v1.4.0 images

- test/test_utils/__init__.py
*Description:*
- Disable test for p2 instance type with cu11 on MXNET framework
> [test] disable test for p2 instance type with cu11 on mxnet framework

- src/config/build_config.py
- test/dlc_tests/container_tests/bin/pytorch_tests/testPTHVDHelper
- test/dlc_tests/container_tests/bin/testMXNetHelper
- test/dlc_tests/eks/mxnet/training/test_eks_mxnet_training.py
- test/dlc_tests/eks/pytorch/training/test_eks_pytorch_training.py
- test/sagemaker_tests/pytorch/training/resources/mnist/mnist.py
- test/sagemaker_tests/pytorch/training/resources/mnist/smdataparallel_mnist.py
- test/sagemaker_tests/pytorch/training/resources/mnist/smdebug_mnist.py
https://github.com/pytorch/vision/issues/3549
*Description:*
- Downloading MNIST dataset gives HTTP Error 503 for Pytorch and MXNET. See https://github.com/pytorch/vision/issues/3549
> [test][pytorch][mxnet] fix mnist dataset download 503 issue

- release_images.yml
*Description:*
-  release PT1.5.0 images
> [release] release PT1.5.0 images

- pytorch/buildspec.yml
- pytorch/training/docker/1.7.1/py3/cu110/Dockerfile.gpu
> [pytorch] [build] [sagemaker] SMP 1.3 for PT 1.7

- release_images.yml
*Description:*
Add PT 1.8.0 to release_images.yml
*Tests run:*
> [release] Add PT 1.8.0 to release_images

- release_images.yml
*Description:*
- Release TF2.3.0 EIA image
- Cleanup configs for old frameworks.
> [release] release TF2.3.0 EIA image

- available_images.md
*Description:*
Add PT 1.8.0 to available_images.md
*Tests run:*
> [doc] Update available images

- pytorch/buildspec.yml
- pytorch/training/docker/1.6.0/py3/cu110/Dockerfile.gpu
*Description:*
Add DGL 0.6.x to PT 1.6 CUDA 11.0 DLC
*Tests run:*
> [pytorch][build] Re-enable DGL on PT 1.6 CUDA 11

- available_images.md
*Description:*
- update TF2.3.0 EIA image to available images
> [doc] update TF2.3.0 EIA image to available images

- available_images.md
- buildspec.yml
- huggingface/pytorch/buildspec.yml
- huggingface/pytorch/training/docker/1.6/py3/cu110/Dockerfile.gpu
- huggingface/pytorch/training/docker/1.7/py3/cu110/Dockerfile.gpu
- huggingface/tensorflow/buildspec.yml
- huggingface/tensorflow/training/docker/2.3/py3/cu110/Dockerfile.gpu
- huggingface/tensorflow/training/docker/2.4/py3/cu110/Dockerfile.gpu
- release/resources/important_dlc_packages.yml
- release_images.yml
- src/buildspec.py
- src/constants.py
- src/image_builder.py
- src/utils.py
- test/dlc_tests/sanity/test_dlc_labels.py
- test/dlc_tests/sanity/test_pre_release.py
- test/test_utils/__init__.py
- test/testrunner.py
*Description:*
Initial PR foe HF containers
*Tests run:*
> [huggingface-tensorflow, huggingface-pytorch][build, test, release]HF containers

- release_images.yml
*Description:*
- Release PT1.5.0 inference images
> [release] release PT1.5.0 inference images

- src/config/build_config.py
- tensorflow/inference/docker/build_artifacts/sagemaker/python_service.py
- tensorflow/inference/docker/build_artifacts/sagemaker/serve.py
- tensorflow/inference/docker/build_artifacts/sagemaker/tfs_utils.py
*Description:*
Sync PR from https://github.com/aws/sagemaker-tensorflow-serving-container/pull/192/files
*Tests run:*
> Wait tfs before starting gunicorn

- huggingface/pytorch/buildspec.yml
- huggingface/pytorch/training/docker/1.6/py3/cu110/Dockerfile.gpu
- huggingface/pytorch/training/docker/1.7/py3/cu110/Dockerfile.gpu
- huggingface/tensorflow/buildspec.yml
- huggingface/tensorflow/training/docker/2.3/py3/cu110/Dockerfile.gpu
- huggingface/tensorflow/training/docker/2.4/py3/cu110/Dockerfile.gpu
- src/image_builder.py
- src/main.py
> [huggingface_tensorflow, huggingface_pytorch][build] Pass arguments into dockerfile at buildtime

- tensorflow/buildspec-2-3.yml
*Description:*
Add a buildspec template for TensorFlow 2.3 for future reference.
*Tests run:*
Copied from https://github.com/aws/deep-learning-containers/blob/tf-2.3/tensorflow/buildspec.yml, which is already known to work.
> [doc][tensorflow][build] Add TF 2.3 buildspec file

- src/config/build_config.py
- test/dlc_tests/container_tests/bin/pytorch_tests/testPTHVDHelper
- test/dlc_tests/container_tests/bin/testMXNetHelper
- test/dlc_tests/eks/mxnet/training/test_eks_mxnet_training.py
- test/dlc_tests/eks/pytorch/training/test_eks_pytorch_training.py
- test/sagemaker_tests/pytorch/training/resources/mnist/mnist.py
- test/sagemaker_tests/pytorch/training/resources/mnist/smdataparallel_mnist.py
- test/sagemaker_tests/pytorch/training/resources/mnist/smdebug_mnist.py
*Description:*
Test failures are seen on downloading mnist dataset from `ossci-datasets` s3 bucket. Hosted the mnist dataset on one of our s3 bucket `dlinfra-mnist-dataset`.
> [test] change mnist dataset s3 bucket location

- test/dlc_tests/eks/eks_manifest_templates/ssm/install_ssm.yaml
- test/test_utils/eks.py
- test/testrunner.py
*Description:*
- Install SSM agent on EKS worker nodes in form of k8s daemonsets.
> [test][eks] install ssm on EKS worker nodes

- pytorch/inference/docker/1.5.1/py3/Dockerfile.neuron
- tensorflow/inference/docker/1.15/py3/Dockerfile.neuron
- tensorflow/inference/docker/1.15/py36/Dockerfile.cpu
- tensorflow/inference/docker/1.15/py36/cu100/Dockerfile.gpu
> [tensorflow, pytorch] [build] Fix for gunicorn vulnerability

- pytorch/inference/docker/1.8/py3/Dockerfile.cpu
- pytorch/inference/docker/1.8/py3/cu111/Dockerfile.gpu
> [pytorch] [build] Upgrading ruamel_yaml version for inference containers

- pytorch/training/docker/1.8/py3/cu111/Dockerfile.gpu
*Description:*
Fix brackets on PT 1.8 GPU training dockerfile
*Tests run:*
> [pytorch][build] Fix bad bracket close on PT 1.8 dockerfile

- tensorflow/training/docker/2.4/py3/cu110/Dockerfile.gpu
*Description:*
Updating SM data parallel library binary to 1.1.2 for TF 2.4.1 training GPU dockerfile
*Tests run:*
MNIST, MaskRCNN
Tensorflow 2.4.1 training gpu
> [tensorflow][build][sagemaker] SMDDP upgrade verion to 1.1.2 for TF2.4.1

- tensorflow/inference/docker/1.15/py36/Dockerfile.cpu
- tensorflow/inference/docker/1.15/py36/cu100/Dockerfile.gpu
- tensorflow/inference/docker/2.4/py3/Dockerfile.cpu
- tensorflow/inference/docker/2.4/py3/cu110/Dockerfile.gpu
- tensorflow/training/docker/1.15/py3/Dockerfile.cpu
- tensorflow/training/docker/1.15/py3/cu100/Dockerfile.gpu
- tensorflow/training/docker/1.15/py3/cu110/Dockerfile.gpu
- tensorflow/training/docker/1.15/py36/Dockerfile.cpu
- tensorflow/training/docker/1.15/py36/cu100/Dockerfile.gpu
- tensorflow/training/docker/2.4/py3/Dockerfile.cpu
- tensorflow/training/docker/2.4/py3/cu110/Dockerfile.gpu
- test/dlc_tests/sanity/test_pre_release.py
*Description:*
Added a comma on a line in test_pre_release.py
*Tests run:*
> [test] Fix test_pre_release imports

- huggingface/pytorch/training/docker/1.6/py3/cu110/Dockerfile.gpu
- huggingface/pytorch/training/docker/1.7/py3/cu110/Dockerfile.gpu
- huggingface/tensorflow/training/docker/2.3/py3/cu110/Dockerfile.gpu
- huggingface/tensorflow/training/docker/2.4/py3/cu110/Dockerfile.gpu
- mxnet/inference/docker/1.5.1/py3/Dockerfile.eia
- mxnet/inference/docker/1.6.0/py3/Dockerfile.cpu
- mxnet/inference/docker/1.6.0/py3/cu101/Dockerfile.gpu
- mxnet/inference/docker/1.7.0/py3/Dockerfile.cpu
- mxnet/inference/docker/1.7.0/py3/Dockerfile.eia
- mxnet/inference/docker/1.7.0/py3/cu101/Dockerfile.gpu
- pytorch/inference/docker/1.3.1/py3/Dockerfile.eia
- pytorch/inference/docker/1.4.0/py3/Dockerfile.cpu
- pytorch/inference/docker/1.4.0/py3/cu101/Dockerfile.gpu
- pytorch/inference/docker/1.5.0/py3/Dockerfile.cpu
- pytorch/inference/docker/1.5.0/py3/cu101/Dockerfile.gpu
- pytorch/inference/docker/1.5.1/py3/Dockerfile.cpu
- pytorch/inference/docker/1.5.1/py3/Dockerfile.eia
- pytorch/inference/docker/1.5.1/py3/Dockerfile.neuron
- pytorch/inference/docker/1.6.0/py3/Dockerfile.cpu
- pytorch/inference/docker/1.6.0/py3/cu101/Dockerfile.gpu
- pytorch/inference/docker/1.7/py3/Dockerfile.cpu
- pytorch/inference/docker/1.7/py3/cu110/Dockerfile.gpu
- test/sagemaker_tests/pytorch/inference/requirements.txt
- test/sagemaker_tests/pytorch/training/requirements.txt
> More files for license attribution

- available_images.md
> [doc] Fixed a typo in available_images.md

- pytorch/inference/docker/1.6.0/py3/Dockerfile.cpu
- pytorch/inference/docker/1.6.0/py3/cu101/Dockerfile.gpu
- pytorch/inference/docker/1.7/py3/Dockerfile.cpu
- pytorch/inference/docker/1.7/py3/cu110/Dockerfile.gpu
- pytorch/training/docker/1.6.0/py3/Dockerfile.cpu
- pytorch/training/docker/1.6.0/py3/cu101/Dockerfile.gpu
- pytorch/training/docker/1.6.0/py3/cu110/Dockerfile.gpu
- pytorch/training/docker/1.7/py3/Dockerfile.cpu
- pytorch/training/docker/1.7/py3/cu110/Dockerfile.gpu
> [pytorch] [build] [test] Fixes for PR 1.6 and 1.7 dockerfiles (test_oss_compliance())

- release_images.yml
> trigger 1.15.5 tf release for py36

- release_images.yml
> release py1.6.0 wave 1

- release_images.yml
> [release] fix release spec typo

- release_images.yml
> [release] release pt-1.6.0 wave2

- huggingface/pytorch/training/docker/1.6/py3/cu110/Dockerfile.gpu
- huggingface/pytorch/training/docker/1.7/py3/cu110/Dockerfile.gpu
- huggingface/tensorflow/training/docker/2.3/py3/cu110/Dockerfile.gpu
- huggingface/tensorflow/training/docker/2.4/py3/cu110/Dockerfile.gpu
*Description:*
-  Add automatic yes to prompts for apt
> [huggingface][build] Add automatic yes to prompts for apt

- tensorflow/buildspec-tf1-neuron.yml
*Description:*
- Add the `deep_learning_container` to the context for TF1 neuron buildspec to align with #973 changes.
> [build] fix tf1 neuron buildspec

- test/test_utils/__init__.py
> [huggingface_pytorch, huggingface_tensorflow] [test] Canary test fix

- release_images.yml
*Description:*
- Release HF with transformer version v4.5.0
> [release][huggingface] release HF with transformer version v4.5.0

- pytorch/buildspec-eia.yml
- pytorch/inference/docker/1.5.1/py3/Dockerfile.eia
- pytorch/inference/docker/1.5.1/py3/Dockerfile.neuron
- src/config/build_config.py
*Description:*
- update EIA buildspec 
- upgrade ruamel_yaml package
- Add python ENV var
> [build] update EIA buildspec and upgrade ruamel_yaml package

- available_images.md
*Description:*
- HF transformer version update
> [doc] HF transformer version update

- available_images.md
*Description:*
Make minor corrections to available_images.md
*Tests run:*
> [doc] Minor corrections on available_images

- test/test_utils/__init__.py
- test/testrunner.py
> [huggingface_tensorflow][test]A small fix for canary tests for HF tensorflow

- pytorch/buildspec.yml
> [pytorch][build] PT1.6: Build just CPU

- test/test_utils/sagemaker.py
> [sagemaker] Fix typo

- test/dlc_tests/benchmark/sagemaker/tensorflow/training/resources/tf_sm_benchmark.py
- test/sagemaker_tests/huggingface_pytorch/training/conftest.py
- test/sagemaker_tests/huggingface_tensorflow/training/integration/conftest.py
- test/sagemaker_tests/mxnet/inference/conftest.py
- test/sagemaker_tests/mxnet/training/conftest.py
- test/sagemaker_tests/pytorch/inference/conftest.py
- test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/conftest.py
- test/sagemaker_tests/tensorflow/tensorflow1_training/integration/conftest.py
- test/test_utils/sagemaker.py
> [benchmark][efa][sagemaker] Fix TF2 SM benchmark and add EFA configs to all SM remote tests

- release_images.yml
> [pytorch][tensorflow] Release PT1.8.1 and TF2.4.1 training gpu

- release_images.yml
*Description:*
Release TF 2.3.2 DLC with updates.
*Tests run:*
> [release] release tf2.3.2 dlc images

- release_images.yml
> tf 2.3.2 release wave 2

- test/sagemaker_tests/huggingface_pytorch/training/integration/sagemaker/test_smdp.py
> Deriving version for transormers SMDP test script from ecr image

- release_images.yml
> [release] Change transformer versions in HF TF2.4.1 and PT1.7.1

- pytorch/inference/docker/1.8/py3/Dockerfile.cpu
- pytorch/inference/docker/1.8/py3/cu111/Dockerfile.gpu
- test/dlc_tests/sanity/test_safety_check.py
> update TS to 0.4.0 for inference PT1.8.1

- release_images.yml
*Description:*
PR to release this PR https://github.com/aws/deep-learning-containers/pull/1101/files
*Tests run:*
> [release] Release PT 1.7.1 for Neuron UL18 

- huggingface/pytorch/buildspec.yml
- huggingface/tensorflow/buildspec.yml
*Description:*
Build only inference DLCs for HF TF and HF PT
*Tests run:*
> [build] Build HF Inference DLCs

- available_images.md
*Description:*
Update PyTorch 1.7.1 Neuron DLC on available_images.md
*Tests run:*
> [doc] Update available_images

- release_images.yml
*Description:*
Release https://github.com/aws/deep-learning-containers/pull/1146
*Tests run:*
> [release] Release HF PT1.7.1 and TF2.4.1 inference

- release_images.yml
Reverts aws/deep-learning-containers#1168
> Revert "[release] Release HF PT1.7.1 and TF2.4.1 inference"

- release_images.yml
*Description:*
Fix error in release_images.md config for MXNet 1.8 Neuron
*Tests run:*
> [release] Correction on MX 1.8 Neuron config

- huggingface/pytorch/inference/docker/1.7/py3/Dockerfile.cpu
- huggingface/pytorch/inference/docker/1.7/py3/cu110/Dockerfile.gpu
- huggingface/tensorflow/inference/docker/2.4/py3/Dockerfile.cpu
- huggingface/tensorflow/inference/docker/2.4/py3/cu110/Dockerfile.gpu
> Bumped up the SM HF Toolkit in HF inference containers

- release_images.yml
Reverts aws/deep-learning-containers#1171
> Revert "Revert "[release] Release HF PT1.7.1 and TF2.4.1 inference""

- release_images.yml
> [release][tensorflow2] update release details for TF2.5

- mxnet/training/docker/1.8.0/py3/Dockerfile.cpu
- mxnet/training/docker/1.8.0/py3/cu110/Dockerfile.gpu
- tensorflow/training/docker/2.4/py3/Dockerfile.cpu
- tensorflow/training/docker/2.4/py3/cu110/Dockerfile.gpu
- test/sagemaker_tests/pytorch/training/integration/__init__.py
*Description:*
Revert smdebug version upgrades
*Tests run:*
> [build][test] Downgrade smdebug version and revert test changes

- test/sagemaker_tests/huggingface/inference/conftest.py
> [test][sagemaker][huggingface] fix hugging face conftest.py

- test/sagemaker_tests/huggingface/inference/requirements.txt
- test/sagemaker_tests/huggingface_pytorch/training/requirements.txt
- test/sagemaker_tests/huggingface_tensorflow/training/requirements.txt
- test/sagemaker_tests/mxnet/inference/requirements.txt
- test/sagemaker_tests/mxnet/training/requirements.txt
- test/sagemaker_tests/pytorch/inference/requirements.txt
- test/sagemaker_tests/pytorch/training/requirements.txt
- test/sagemaker_tests/tensorflow/tensorflow1_training/requirements.txt
- test/sagemaker_tests/tensorflow/tensorflow2_training/requirements.txt
*Description:*
Add TOML as a dependency to sagemaker tests
*Tests run:*
> [test] Update SM test requirements to include toml dependency

- dlc_developer_config.toml
- src/config/__init__.py
- test/test_utils/test_reporting.py
*Description:*
Ensure sanity test fails if we are missing requirements in SM tests
*Tests run:*
Run sanity tests
> [reporting][sagemaker] Update test reporting to catch any missed requirements in SM tests

- test/testrunner.py
Interim skip on quick-checks stages - make sure they're not failing for everyone in PR context. They will be fully enabled with PR #1225
> [test] Placeholder early return for quick_checks stage

- dlc_developer_config.toml
- test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_smmodelparallel.py
Change instance type for SMMP TF sagemaker tests from ml.p3.16xlarge to ml.g4dn.24xlarge due to the capacity issue
> [test][sagemaker]change smmp tf non-efa test instance

- release_images.yml
Add PT 1.9 DLC image spec to release_images.yml
N/A
N/A
N/A
> [release] Add PT 1.9 to release_images

- release/resources/important_dlc_packages.yml
> [autogluon][release] Adding packages for autogluon container release notes

- .github/CODEOWNERS
- Add some new entries to codeowners, add aws tag to a couple places
> [gitops] Add updates to CODEOWNERS file

- autogluon/buildspec.yml
- autogluon/training/docker/0.3/py3/Dockerfile.cpu
- autogluon/training/docker/0.3/py3/cu102/Dockerfile.gpu
> [autogluon][build] Building AG 0.3.0

- autogluon/buildspec.yml
- autogluon/training/docker/0.2/py3/Dockerfile.cpu
- autogluon/training/docker/0.2/py3/cu102/Dockerfile.gpu
- autogluon/training/docker/0.3/py3/Dockerfile.cpu
- autogluon/training/docker/0.3/py3/cu102/Dockerfile.gpu
> [autogluon][build] Autogluon 0.3.0

- buildspec.yml
- dlc_developer_config.toml
- mxnet/buildspec-graviton.yml
- mxnet/inference/docker/1.8/py3/Dockerfile.graviton
- pytorch/buildspec-graviton.yml
- pytorch/inference/docker/1.9/py3/Dockerfile.graviton
- src/constants.py
- src/main.py
- tensorflow/buildspec-graviton.yml
- tensorflow/inference/docker/2.5/py3/Dockerfile.graviton
- tensorflow/training/docker/1.15/py3/cu110/Dockerfile.gpu
- test/dlc_tests/sanity/quick_checks/test_dlc_developer_config.py
- test/test_utils/__init__.py
Add buildspec parsing for Graviton buildspecs and dockerfiles
> [build][graviton] Add buildspec parsing for Graviton buildspecs and dockerfiles

- autogluon/buildspec.yml
> [autogluon][build] Building AG 0.2.1

- autogluon/buildspec.yml
- release_images.yml
> [autogluon][release] Autogluon 021

- available_images.md
> [autogluon][doc] Adding autogluon into available images

- test/sagemaker_tests/pytorch/__init__.py
- test/test_utils/__init__.py
- PT 1.9 does not have generic "py3" tag, so we need to make these changes in order to run canaries on the images
- Run sanity test in PR
- N/A
> [canary] Update canary logic to pull PT1.9 images

- dlc_developer_config.toml
- huggingface/pytorch/buildspec.yml
- test/dlc_tests/conftest.py
- test/dlc_tests/release_candidate_integration/test_sm_profiler.py
> [test] Add 'huggingface' pytest fixture

- available_images.md
- Update available images for PT 1.9, HF PT 1.8.1
> Update available_images.md for recent releases

- autogluon/build_artifacts/inference/config.properties
- autogluon/build_artifacts/inference/mms-entrypoint.py
- autogluon/training/docker/0.2/py3/cu102/Dockerfile.gpu
- autogluon/training/docker/0.3/py3/cu102/Dockerfile.gpu
- release_images.yml
Addressing CVN + added missing files
> [Autogluon] Container security fixes + added missing files

- autogluon/inference/docker/0.3/py3/Dockerfile.cpu
https://github.com/awslabs/autogluon/pull/1320
> [Autogluon] Pillow patch to min 8.3.2

- dlc_developer_config.toml
- test/sagemaker_tests/huggingface_tensorflow/training/integration/sagemaker/test_smdataparallel.py
The `TensorFlow` tested had constrained which skipped test where cuda was `!=` to `110`.  We removed this completely. Since there were never TensorFlow container < 2.3.1 and cuda < 110
- Relates to issue #1355 
> [huggingface_tensorflow] Fix Tensorflow smd test 

- available_images.md
Updating information on released images
> [Autogluon] Updated images docs

- release_images.yml
#1387 
- prep release for HF 2.5 transformers 4.11
HF TF 2.5 transformers 4.11 images
> [huggingface_tensorflow] Update release for TF2.5 HF transformers 4.11

- release_images.yml
#1387 
- Add release config for HF PT1.9/transformers 4.11
- HF PT 1.9 transformers 4.11
> [huggingface_pytorch] Release HF PT1.9 transformers 4.11

- tensorflow/buildspec-diy-sm-2-5.yml
- test/test_utils/__init__.py
- Update the tag from "diy" to "ec2-ecs-eks"
> [diy] Change DIY tag to ec2-ecs-eks

- dlc_developer_config.toml
- src/main.py
- src/utils.py
- Saw @junpuf comment in #1395 and realized we didn't have the option to skip by TF1 or TF2. Adding in this option, as it Is useful for iterating on TF1 or TF2, respectively
- Tested on 2 revisions in this PR
> [config] Add option to skip by tensorflow-1 or tensorflow-2

- available_images.md
- Updating available images for PT1.10 e3 releases
> [pytorch] Add e3 PT1.10 images to available_images.md

- dlc_developer_config.toml
- test/sagemaker_tests/mxnet/inference/integration/sagemaker/test_batch_transform.py
- test/sagemaker_tests/mxnet/inference/integration/sagemaker/test_elastic_inference.py
- test/sagemaker_tests/mxnet/inference/integration/sagemaker/test_gluonnlp.py
- test/sagemaker_tests/mxnet/inference/integration/sagemaker/test_hosting.py
- test/sagemaker_tests/mxnet/inference/integration/sagemaker/test_neuron_hosting.py
Fixes MXNet neuron tests from always running even when there is no neuron container. Problem related to using pytest fixtures as markers to skip tests which does not work. 
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, …
> [mxnet][neuron][test][sagemaker] Fix neuron tests skipping fixtures

- release_images.yml
#1475 
- Update release images yaml for latest HF transformers release
> [huggingface][release] Prepare release_images.yml for transformers 4.12.3 release

- release_images.yml
Release PT1.9.1, TF1.15.5, Tf2.5.1, MX:1.8.0
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> [release] Release Neuron Images for sdk1.16.0

- dlc_developer_config.toml
- src/image_builder.py
- src/utils.py
- Tested on draft PR
- Make sure images is populated when do_build is set to false, to preserve old behavior
> [config] Fix `do_build` config option

- available_images.md
> move tf1.15 images to prior list

- dlc_developer_config.toml
- pytorch/inference/docker/1.10/py3/Dockerfile.graviton
- pytorch/training/docker/1.9/py3/Dockerfile.cpu
fix graviton pytorch 1.10 libtinfo.so.6 issue
> [graviton][pytorch][build]fix libtinfo.so.6 issue

- release_images.yml
> [release] Neuron release image to not have sm abbreviated tags

- release_images.yml
Add PT 1.5.1 inference CPU, GPU to release_images.yml
> [release] Add PT 1.5.1 inference

- dlc_developer_config.toml
- test/dlc_tests/conftest.py
- test/dlc_tests/ec2/mxnet/inference/test_mxnet_inference.py
- test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference.py
- test/dlc_tests/ecs/mxnet/inference/test_ecs_mxnet_inference.py
- test/dlc_tests/ecs/pytorch/inference/test_ecs_pytorch_inference.py
- test/dlc_tests/eks/mxnet/inference/test_eks_mxnet_inference.py
- test/dlc_tests/eks/pytorch/inference/test_eks_pytorch_inference.py
- test/dlc_tests/sanity/test_pre_release.py
- remove `graviton_only` fixture
> [graviton] fix pytest fixture

- dlc_developer_config.toml
- src/image_builder.py
- test/dlc_tests/sanity/test_safety_check.py
- test/dlc_tests/sanity/test_safety_report_file.py
Uncomment the build code and remove test skips to allow the Common Stage Build to take place. The Common Stage Build will run the safety scan on the images while building and embed the reports in the images itself. …
> [build] Start Embedding Safety Scan Reports

- dlc_developer_config.toml
- test/dlc_tests/ecs/mxnet/inference/test_ecs_mxnet_inference.py
- test/dlc_tests/ecs/pytorch/inference/test_ecs_pytorch_inference.py
- test/dlc_tests/ecs/tensorflow/inference/test_ecs_tensorflow_inference.py
- test/test_utils/__init__.py
- test/test_utils/ec2.py
- test/test_utils/ecs.py
> [NEURON][TEST][ECS] - Add ecs test for neuron

- src/utils.py
> [bug] Fix get_root_folder_path bug

- release_images.yml
Add PT 1.7.1 to release_images.yml
> [release] Add PT 1.7.1 to release images

- release_images.yml
- update release spec for pt 1.10 sagemaker images
> Release PT1.10 SageMaker images

- autogluon/inference/docker/0.3/py3/Dockerfile.cpu
- autogluon/training/docker/0.3/py3/Dockerfile.cpu
- autogluon/training/docker/0.3/py3/cu102/Dockerfile.gpu
Autogluon containers security patching: GDAL and dask upgraded
> [Autogluon][build][security] Dask and GDAL security patch

- release_images.yml
- Release SM inference PT1.10 images
> [release] Release SM inference PT1.10 images

- release_images.yml
- Reset PT 1.10 SM inference release yaml
> [release] Reset PT1.10 SM inference release yaml

- release_buildspec.yml
- release_images.yml
- Add support for architecture type in `release_images.yml`
- Configure release docker image to setup `qemu` emulator for graviton images …
> release compatibility for architecture type

- test/dlc_tests/sanity/quick_checks/test_generate_coverage_doc.py
- test/test_utils/__init__.py
skip generate test coverage doc test as the test is incompatible with ARM architecture image
> [graviton] skip generate test coverage doc for graviton

- available_images.md
- Add available images updates for latest PT and tensorflow releases
> [pytorch][tensorflow] Update available images markdown file for new releases

- available_images.md
- Put e3/SM up top, since these are latest framework versions
> [docs] Reorder available_images.md

- available_images.md
> Added sagemaker training compiler to available images

- release_images.yml
- Release configuration for pytorch 1.10.0 and tensorflow 2.7.0 graviton
> [graviton]pytorch 1.10.0 and tensorflow 2.7.0 release

- release_images.yml
- Release PT1.10 and TF2.7 graviton images
> [graviton] release PT1.10 and TF2.7

- release_images.yml
- Remove TF2.7 and PT1.10 x86 images for graviton release.
> [graviton] remove TF2.7 and PT1.10 x86 configuration from release_images.yml

- available_images.md
> [graviton][doc]add pytorch 1.10.0 and tensorflow 2.7.0 image

- release_images.yml
Release training images for PT1.9.1 and TF2.6.2.
> [Tensorflow][Pytorch] Release images for PT1.9.1 and TF2.6.2

- test/dlc_tests/sanity/quick_checks/test_generate_coverage_doc.py
> [bug] Fix graviton skip condition for coverage doc test

- buildspec.yml
- Buildspec support for HF neuron PR builds
> Add buildspec support for Huggingface Neuron

- test/dlc_tests/sanity/test_utility_installation.py
> [test] fix typo

- release_images.yml
- set params back to original value
> Update release images yaml

- test/test_utils/__init__.py
- Add canary tests for huggingface inference
> [canary] Add huggingface inference canaries

- test/dlc_tests/sanity/test_pre_release.py
> [canary] Temporarily unskip dependency check on canaries

- test/test_utils/__init__.py
> [canary] Update huggingface canary logic

- release_images.yml
> [pytorch][release] pytorch 1.8 training image relase set force_release to true

- test/dlc_tests/sanity/test_pre_release.py
> Re-enable canary skip conditions on dependency check

- release_images.yml
> [Pytorch][release] revert force release

- huggingface/pytorch/inference/docker/1.8/py3/Dockerfile.cpu
> [huggingface][pytorch] Update MMS version to latest for HF PT 1.8

- dlc_developer_config.toml
- mxnet/buildspec.yml
- mxnet/inference/docker/1.8/py3/Dockerfile.cpu
- mxnet/inference/docker/1.8/py3/cu110/Dockerfile.gpu
> [mxnet] Update MMS version in MXNet 1.8 inference images

- huggingface/pytorch/buildspec.yml
- huggingface/pytorch/inference/docker/1.8/py3/cu111/Dockerfile.gpu
- huggingface/pytorch/inference/docker/1.9/py3/Dockerfile.cpu
- huggingface/pytorch/inference/docker/1.9/py3/cu111/Dockerfile.gpu
- Update GPU inference images as well
> Update MMS for HF PT

- release_images.yml
- release MX 1.8 inference images with updated MMS version
> [mxnet] Release mxnet 1.8 inference containers

- release_images.yml
> [huggingface][pytorch] Release HF pytorch 1.9.1 images

- release_images.yml
> [pytorch][release] release pt1.8.1

- test/dlc_tests/sanity/test_pre_release.py
Currently dependency-check test is failing due to "CVE-2021-42550". Affected software is located at File Path: `dependency-check/lib/logback-core-1.2.3.jar`. This file path indicated that it is a dependency of dependency-check tool which is not part of the DLC, so we can safely ignore it.
By submitting this pull …
> [Fix] ignore dependency-check dependency

- release_images.yml
> release pt-1.10.0

- dlc_developer_config.toml
- mxnet/buildspec-graviton.yml
- pytorch/buildspec-graviton.yml
change buildspec to adapt new build logic, fix graviton "not build" issue
> [build][graviton][mxnet][pytorch] fix graviton image build

- release_images.yml
- update release images for MX 1.9 release
> Update release images for MX1.9

- test/sagemaker_tests/mxnet/inference/conftest.py
- test/sagemaker_tests/mxnet/training/conftest.py
- Support py38 flag for mxnet sagemaker test
> support py38 flag for mxnet sagemaker test

- release_images.yml
> Update MX 1.9 example images

- mxnet/inference/docker/1.9/py3/Dockerfile.cpu
- mxnet/inference/docker/1.9/py3/cu112/Dockerfile.gpu
- mxnet/training/docker/1.9/py3/Dockerfile.cpu
- mxnet/training/docker/1.9/py3/cu112/Dockerfile.gpu
> Update numpy version in MX images

- release_images.yml
- Update release images yml file
> Release MX inference images for MXNet 1.9

- .release_images_template.yml
- release_images.yml
> [Tensorflow][release] add TF2.8 in release images

- release_images.yml
Habana release v1.2 images for TF and PT
> Habana release v1.2 images for TF and PT

- dlc_developer_config.toml
- huggingface/pytorch/buildspec-neuron.yml
- huggingface/pytorch/inference/docker/1.9/py3/sdk1.17.0/Dockerfile.neuron
> [NEURON][BUILD][HF] - use ubuntu18

- release_images.yml
> Release neuron sdk 1.17.1 version

- available_images.md
> Update available images for neuron sdk release 1.17.1

- release_images.yml
> pt1.10.2 release images

- release_images.yml
> update pt1.10.2 release images

- release_images.yml
- tensorflow/buildspec-2-7.yml
> [release][tensorflow] add TF27 release images

- tensorflow/inference/docker/2.8/py3/Dockerfile.cpu
- tensorflow/inference/docker/2.8/py3/cu112/Dockerfile.gpu
- tensorflow/training/docker/2.8/py3/Dockerfile.cpu
- tensorflow/training/docker/2.8/py3/cu112/Dockerfile.gpu
start from Python39, a xxx.pem file will be generated under /tmp folder during installation. remove it for sanity check
if python upstream remove the xxx.pem file, image build will fail. will need to remove `&& rm /tmp/*.pem` then
> [Tensorflow] add comment on py39 installation on TF 2.8 dockerfiles

- release_images.yml
- update release images yaml for TF2.8
> Release TF2.8 e3 images

- release_images.yml
re-release Tensorflow 2.7 sagemaker cpu training image to fix sagemaker-tensorflow version from 2.8.x to 2.7.x
> [Tensorflow] re-releas TF27 sagemaker cpu training

- tensorflow/inference/docker/2.8/py3/Dockerfile.cpu
- tensorflow/inference/docker/2.8/py3/cu112/Dockerfile.gpu
- tensorflow/training/docker/2.8/py3/Dockerfile.cpu
- tensorflow/training/docker/2.8/py3/cu112/Dockerfile.gpu
- tensorflow/training/docker/2.8/py3/example/Dockerfile.gpu
- Update license file
- Correct env variables
> [tensorflow] Bug fixes to TF2.8 E3 images

- dlc_developer_config.toml
- test/test_utils/ec2.py
- test/testrunner.py
Habana is not yet supported on SM local or standard tests. This PR aims to skip those tests for Habana. Additionally, it slightly modifies the `execute_asynchronus_testing_using_s3_bucket` API because it was needed while running the tests for SynapseAI1.3 release. …
> [Habana] [test] [ec2, sagemaker]  Fix to skip SM tests for Habana and modify async testing API

- tensorflow/inference/docker/2.8/py3/cu112/Dockerfile.gpu
- tensorflow/training/docker/2.8/py3/cu112/Dockerfile.gpu
- use upgrade instead of install
> TF 2.8: Move sasl to upgrade instead of install

- available_images.md
- update available images md file
> Update available images for TF2.7 SM and TF2.8 E3

- release_images.yml
Add TF 2.8 SM DLCs to release_images.yml
> [release] Add TF 2.8 SM DLCs to release images

- release_images.yml
Fix AutoGluon 0.3.2 release spec
> [release] Remove customer_type from AG spec

- test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference.py
- test/test_utils/__init__.py
Fix EC2 test issues on PT 1.11 tests on p2 instances, and fix conditions to run torchaudio tests
> [ec2][test] Fix PT 1.11 test issues

- dlc_developer_config.toml
- huggingface/tensorflow/inference/docker/2.6/py3/cu112/Dockerfile.gpu
- test/dlc_tests/sanity/test_safety_check.py
Use GPU binary instead of CPU binary in Hugging Face TensorFlow 2.6 Inference GPU dockerfile
Hugging Face TensorFlow 2.6 Inference
> [huggingface_tensorflow][build] Fix TF 2.6.3 binary source in dockerfile

- release_images.yml
> [Release][Tensorflow] release HF TF 2.6.3

- release_images.yml
Add PyTorch 1.11.0 DLCs to release_images.yml file
> [release] Add PT 1.11.0 to release_images

- dlc_developer_config.toml
- test/test_utils/ec2.py
Use `CODEBUILD_RESOLVED_SOURCE_VERSION` to get the commit id
> [Habana] Get commit using env variables

- dlc_developer_config.toml
- habana/tensorflow/training/docker/2.8/py3/synapseai1.3.0/Dockerfile.hpu
- test/testrunner.py
License file for Habana 1.3 was fixed to older TF version i.e. TF2.7. This PR fixes it and changes the code to prevent this issue in future.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute …
> [Habana] Fixing license file for Tensorflow

- .release_images_template.yml
- release_images.yml
Release for Habana PT1.10.1 and Tf2.8.0.
> Habana PT1.10.1 and TF2.8.0 release

- available_images.md
AutoGluon 0.4.0 available images update
> [Autogluon][doc] AutoGluon 0.4.0 available images update

- release_images.yml
Add MXNet 1.9 CPU to release images.
> Add MXNet 1.9 CPU to release images

- eks_infrastructure/eks_cleanup/eks_cleanup_job.py
Fix import for logging on eks cleanup workflow
> [eks] fix import for logging on eks cleanup workflow

- pytorch/buildspec.yml
- pytorch/inference/docker/1.11/py3/Dockerfile.cpu
- pytorch/inference/docker/1.11/py3/cu115/Dockerfile.gpu
- pytorch/training/docker/1.11/py3/Dockerfile.cpu
- pytorch/training/docker/1.11/py3/cu115/Dockerfile.gpu
Reduce PyTorch GPU Train image size by moving `torchnet` installation to each `AWS-PyTorch` installation layer, avoid redundant official PyTorch installation stored in the previous `pip install` layer.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I …
> [pytorch] [build] PT1.11.0 - reduce PyTorch GPU Train image size 

- release_images.yml
re-release pytorch 1.10.2 inference to get the latest sm-pt-inference-toolkit
> [release][pytorch] re-release PT1.10.2

- available_images.md
update Huggingface Training compiler image uri in available_images.md
> [Doc]Update HF Trcomp image uri

- available_images.md
update PT1.11 e3 image URIs in available_images.md
> [Doc] update PT1.11 image uri in available_images

- dlc_developer_config.toml
- eks_infrastructure/build_param.json
- test/dlc_tests/eks/mxnet/inference/test_eks_mxnet_inference.py
- test/dlc_tests/eks/pytorch/inference/test_eks_pytorch_inference.py
- test/dlc_tests/eks/tensorflow/inference/test_eks_tensorflow_inference.py
1. Perform upgrade nodegroup operation on the EKS cluster
2. Enable EKS test for Graviton DLC
> [eks] Upgrade EKS nodegroups and enable eks test for graviton

- data/common-ecr-scan-allowlist.json
- dlc_developer_config.toml
- test/dlc_tests/sanity/test_security_check.py
> [test] Add a common file to ignore vulnerabilities affecting all containers

- dlc_developer_config.toml
- test/dlc_tests/sanity/test_safety_check.py
- test/dlc_tests/sanity/test_safety_report_file.py
- test/dlc_tests/sanity/test_security_check.py
> [test] Remove redundant scans on the canary

- test/test_utils/__init__.py
> [e3] Fix e3 image adding logic

- dlc_developer_config.toml
- test/dlc_tests/sanity/test_security_check.py
- test/test_utils/security.py
Allowlist feature was getting activated for MxNet1.9. This PR restricts the image coverage for the allowlist feature.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under …
> [test] Restrict image coverage for allowlist feature

- dlc_developer_config.toml
- test/dlc_tests/sanity/test_utility_installation.py
- test/test_utils/__init__.py
> [canary] Update canary regex

- release_images.yml
- Update release images for HF PT 1.10.2 and TF 2.6.3
> [release] Release HF image updates from #1777

- dlc_developer_config.toml
- test/test_utils/security.py
This PR ensures that the order in which we store the packages in the `apt-upgrade-list` is always ascending. The union function of 2 `set`s does not return the resultant set that can be directly converted to a list in ascending order using the `list` command. …
> [test] Fix sorted package order for apt-upgrade-list

- .release_images_template.yml
- release_images.yml
Release PT1.11 SM CPU/GPU TRAIN/INF images
> Release PT1.11 SM CPU/GPU TRAIN/INF images

- available_images.md
Modified available images to add PT1.11 SM images
> Modified available images to add PT1.11 SM images

- release_images.yml
> empty release images

- release_images.yml
Add TF 2.8 inference DLC images to release images yml file
> [release] Add TF 2.8 inference DLCs to release

- release_images.yml
> Release neuron sdk 1.19.0. Update release images.

- autogluon/inference/docker/0.4/py3/Dockerfile.cpu
- autogluon/training/docker/0.4/py3/Dockerfile.cpu
- autogluon/training/docker/0.4/py3/cu112/Dockerfile.gpu
- dlc_developer_config.toml
- test/dlc_tests/sanity/test_pre_release.py
- pip check failure regarding pytorch lightning version
- update version pins to resolve
> Update autogluon tests to resolve pip check issue

- dlc_developer_config.toml
- pytorch/inference/docker/1.11/py3/cu113/Dockerfile.gpu
- pytorch/inference/docker/1.11/py3/cu115/Dockerfile.gpu
- pytorch/training/docker/1.11/py3/cu113/Dockerfile.gpu
- pytorch/training/docker/1.11/py3/cu115/Dockerfile.gpu
Since NVIDIA has released images with the GPG key rotation fix, this PR is made to undo the changes that DLC made for  NVIDIA GPG Key fix.  …
> [pytorch][build] Undo NVIDIA GPG Key Fix

- test/test_utils/__init__.py
The canaries did not scale properly for AG images. The logic of fetching the AG images was not able to handle the python version correctly. This PR helps handle that. Additionally, it makes the logic scalable for every other framework, so that we do not have to make changes every time.
By submitting this pull …
> [test] Make the canary image pull logic scalable

- test/test_utils/__init__.py
Need to test if the different test suite condition is prevented on canary. 
> [test][canary] Sort the parsed canary images to prevent diff test failure

- available_images.md
- release_images.yml
> [NEURON][DOC] - Update available images

- test/test_utils/__init__.py
This PR reintroduces the get_canary_default_tag_py3_version method and restricts regex based python version extraction for just AutoGluon images.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and …
> [test][Canary] Restrict regex based python version extraction for just AutoGluon images

- release_images.yml
Add PT 1.10 E3 and SM DLCs to release images yml file
> [release] Add PT 1.10 E3 and SM DLCs to release

- release_images.yml
> [release] Fix release images

- pytorch/buildspec.yml
- test/dlc_tests/sanity/test_pre_release.py
Upate PT 1.11 buildspec to prepare for release of E3 images
> update PT 1.11 buildspec to prepare for release of E3 images

- .release_images_template.yml
- release_images.yml
Release configuration for TF2.9 E3 Training DLC
> [release] Release configuration for TF2.9 E3 Training DLC

- available_images.md
Add TF2.9 E3 training images to `available_images.md`
> Add TF2.9 E3 training images to `available_images.md`

- .release_images_template.yml
- release_images.yml
Changes in release_images.yml file to release HF PT1.10 inference DLC.
> [release]Release configuration for HF PT1.10 inference DLC

- release_images.yml
Changes in release_images.yml file to release HF PT1.10 training DLC.
> [release]Release config changes for HF PT1.10 training DLC

- release_images.yml
Add PT 1.10 SM and E3 DLCs to release_images
> [release] Release PT 1.10.2 DLCs

- dlc_developer_config.toml
- test/dlc_tests/sanity/test_pre_release.py
- test/dlc_tests/sanity/test_safety_check.py
Disable dependency checks from canaries.
> [test] Disable dependency checks from canaries

- release_images.yml
Add TF 2.8 DLCs to release_images.yml
> [release] Add TF 2.8 DLCs to release images

- tensorflow/buildspec.yml
- tensorflow/training/docker/2.9/py3/Dockerfile.cpu
- tensorflow/training/docker/2.9/py3/cu112/Dockerfile.gpu
> [tensorflow][build][e3] Bump TF version to 2.9.1

- test/dlc_tests/sanity/test_anaconda.py
previous condition will find conda files under `References/PyTorch/nlp/finetuning/huggingface/bert/transformers/.github/conda`, which is not an actual conda installation. exclude `.github` folder to correctly skip test
> [Test] update conda test to exclude .github directory

- release_images.yml
Remove older images from release_images.yml
> [release] Add AG 0.4 to release spec

- dlc_developer_config.toml
- test/dlc_tests/ec2/tensorflow/inference/test_tensorflow_inference.py
- test/dlc_tests/sanity/test_pre_release.py
Fix inference and security test for TF graviton
> Fix inference and security test for TF graviton 

- release_images.yml
Add AG 0.3.2 to release_images.yml
> [release] Add AG 0.3.2 to release images

- dlc_developer_config.toml
- mxnet/buildspec.yml
- mxnet/inference/docker/1.9/py3/Dockerfile.cpu
- mxnet/inference/docker/1.9/py3/cu112/Dockerfile.gpu
Should fix image build and prevent issues we were seeing with tests failing.
> [mxnet] [build] Fix mxnet gpu inference build

- .release_images_template.yml
- release_images.yml
> TF2.7 Graviton release

- release_images.yml
Add MXNet 1.9 DLCs to release_images.yml
> [release] Add MX 1.9 to release images

- dlc_developer_config.toml
- tensorflow/buildspec-neuron.yml
> [TF][NEURON][BUILD] - For sdk 1.17.1 release use the right tf 2.5.2 version in tag

- release_images.yml
Add all Neuron SDK 1.17.1 DLCs to release_images.yml
> [release] Add Neuron SDK 1.17.1 DLCs to release images

- release_images.yml
> [Release][huggingface_pytorch] Release huggingface_pytorch 1.9.1 inference images

- data/ignore_ids_safety_scan.json
- test/dlc_tests/sanity/test_safety_check.py
skip safety failure for TF estimator
> skip safety failure for TF estimator

- dlc_developer_config.toml
- pytorch/inference/docker/1.10/py3/Dockerfile.graviton.e3.cpu
Upgrading TorchServe from 0.5.2 to 0.5.3 for security vulnerability.
> [pytorch][graviton][build] Upgrade torchserve to 0.5.3

- release_images.yml
- release TF2.7 e3 and sagemaker images
> Release TF 2.7 e3 and sagemaker images

- .release_images_template.yml
- release_images.yml
Add AG 0.4.2 images to release_images.yml
> [release] Add AG 0.4.2 to release_images

- available_images.md
AutoGluon 0.4.2 available images update
> [Autogluon][doc] AutoGluon 0.4.2 available images update

- release_images.yml
> [release] update Habana SynAI1.2 release pipeline pytorch version

- release_images.yml
Release TF2.9 SM training images
> release TF2.9 SM training images

- release_images.yml
> Release Pt 1.11 inference

- available_images.md
update available_images.md with TF2.9.1 training images
> update available_images.md with TF2.9.1 training images

- available_images.md
Related to https://github.com/aws/deep-learning-containers/pull/2009
update available_images.md with TF2.9.1 trcomp training images …
> update available_images.md with TF2.9.1 trcomp training images

- release_images.yml
release TF2.5.3 training and TF2.5.1 inference
> release TF2.5.3 training and TF2.5.1 inference

- release_images.yml
fix intendation in release_images.yml
> fix intendation in release_images.yml

- .release_templates/tensorflow2_release_images.yml
- release_images.yml
re-release huggingface tensorflow 2.6
> [release][huggingface][tensorflow] release HF tf2.6

- dlc_developer_config.toml
- tensorflow/buildspec.yml
- tensorflow/inference/docker/2.9/py3/Dockerfile.cpu
- tensorflow/inference/docker/2.9/py3/cu112/Dockerfile.gpu
Add TF2.9 E3/SM Inference Dockerfiles 
> [tensorflow][build]: Add TF2.9 Inference Dockerfiles

- .release_images_template.yml
- release_images.yml
release TF2.9.1 inference images and PT1.11 E3/SM images
> release TF2.9.1 inference and PT1.11 E3/SM images

- test/dlc_tests/sanity/test_pre_release.py
Fix bug from https://github.com/aws/deep-learning-containers/commit/16afa88d995b6f6afcaca3c80cba3d251e72eace#diff-8c9ca2c09d29a6f9e48bf73c2a6e606318fb14fa55326b928964dd47c344c0eb
> Fix assert statements in TFS test

- release_images.yml
- tensorflow/buildspec.yml
> [build] TF2.9.0 Inference DLC

- available_images.md
- tensorflow/buildspec.yml
update available_images.md with TF2.9.0 inference
> update available_images.md with TF2.9.0 inference DLC

- release_images.yml
- release HF trcomp pytorch 1.9 images
> Release hf pytorch trcomp 1.9 images

- release_images.yml
- rerelease PT 1.9 inference images
> Release PT 1.9 inference images

- tensorflow/buildspec-2-6.yml
Increase the image_baseline_size for TF 2.6 for cve patching
> TF2.6 buildspec update

- release_images.yml
Re-release mxnet 1.9 training images to fix cve.
> Release mxnet 1.9 training for cve patching

- release_images.yml
Changing the release_images.yml file to release autogluon 0.4.2 to fix opencv vulnerability.
> Release autogluon 0.4 for cve patching 

- release_images.yml
Changes to release_images.yml file to release TF 2.6 training and inference for cve fix.
> Release TF 2.6 training and inference

- release_images.yml
> [Habana] Release Habana SynAI 1.4.1 PT and TF 

- release_images.yml
- remove training images for TF2.6 from release_images.yml
> remove training images for TF2.6 from release_images.yml

- release_images.yml
remove TF2.6 example image configuration
> remove TF2.6 example image configuration

- release_images.yml
Changes to release_images.yml file to release TF2.7 training DLC for cve fix.
> Release TF2.7 training 

- huggingface/tensorflow/buildspec-2-6.yml
Add buildspec-2-6.yml file in huggingface/tensorflow 
> Add buildspec-2-6.yml file for huggingface

- release_images.yml
> Release HF PT Neuron 1.10 images

- huggingface/tensorflow/buildspec-2-6.yml
- huggingface/tensorflow/buildspec.yml
Increase the image_baseline_size for HF TF 2.6
> Fix image_baseline_size for HF TF 2.6

- available_images.md
- Add release https://github.com/aws/deep-learning-containers/releases/tag/v1.0-hf-4.20.1-pt-1.10.2-inf-neuron-sdk1.19.1-py37 to available images
> Add HF PT Neuron 1.10.2 to available images markdown

- available_images.md
Add Habana SynAI1.4.1 to available_images.md
> Add Habana SynAI1.4.1 to available_images.md

- test/dlc_tests/sanity/test_pre_release.py
> Add test to block specific releases

- available_images.md
Add Triton 22.05 container to the docs.
> add triton 22.05 container to docs

- release_images.yml
> release trcomp TF2.6

- release_images.yml
Changes in release_images.yml to release HF TF 2.6 for opencv cve fix and anaconda removal.
> Re-release HF TF 2.6 

- release_images.yml
This is a release of Autogluon Training and Inference images to address CVE vulnerability issues with opencv-python.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under …
> Modified release images file for Autogluon 0.3.2 release

- test/dlc_tests/container_tests/bin/pytorch_tests/testTorchdata
> [pytorch] [test] update testTorchdata bash script

- release_images.yml
The presence of PT1.11.0 for CPU and GPU images caused issues with the release of HPU images. Removing that for the fix.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, …
> Remove Pt1.11 CPU GPU from release_images.yml

- available_images.md
Add Habana SynAI1.5 images to available_images.yml
> Add Habana SynAI1.5 images to available_images.yml

- pytorch/buildspec-1-10.yml
Modifying PT 1.10 buildspec to generate inference image RCs
> Modifying PT 1.10 buildspec to generate inference image RCs

- release_images.yml
> Release PT 1.11 sagemaker training images

- release_images.yml
Include changes to release PyTorch 1.10 inference images.
> Releasing PyTorch 1.10 inference images

- available_images.md
Adding the new region to available_images.md. Region name - Asia Pacific (Jakarta) and Airport code - CGK 
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
> Add CGK region to the available_images.md file

- release_images.yml
Changes to release HF PT 1.10 inference and training DLCs to fix CVEs.
> Release HF PT 1.10.2 inference and training

- available_images.md
- data/ignore_ids_safety_scan.json
Remove out of support images from available_images.md
> Remove out of support images from available_images.md

- available_images.md
> Update available images file with anaconda license

- release_images.yml
> Update release images for Tr Comp

- release_images.yml
> Add AG 0.4.3 to release images

- LICENSE
> Update license to include anaconda notice

- available_images.md
> Update AG 0.4.2 to AG 0.4.3 in available_images

- release_images.yml
> Add AG 0.5.2 to release images

- available_images.md
> Update available_images.md with AG 0.5.2

- dlc_developer_config.toml
- test/sagemaker_tests/mxnet/inference/conftest.py
- test/sagemaker_tests/mxnet/training/conftest.py
- test/sagemaker_tests/pytorch/inference/conftest.py
- test/sagemaker_tests/pytorch/training/conftest.py
- test/sagemaker_tests/tensorflow/inference/test/integration/local/conftest.py
- test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/conftest.py
- test/sagemaker_tests/tensorflow/tensorflow2_training/integration/conftest.py
Correct nightly fixture usage on SM tests as a follow up to PR #2090
> Correct nightly fixtures on SM tests

- pytorch/buildspec.yml
disable SM inference build for PT1.12
> disable SM inference build for PT1.12

- release_images.yml
release PT1.12 SageMaker training DLC
> release PT1.12 SageMaker training DLC

- release_images.yml
Re-release TF2.7 inference for multi gpu support, TF 2.8 inference for multi gpu support and cve fix and PT 1.11 for PyTorch DDP distribution update.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and …
> Re-release TF 2.7, TF 2.8 and PT 1.11

- available_images.md
1. Update only documentation for the latest release of Triton container v22.07
Triton DLC
- [] (If applicable) I've documented below the tests I've run on the DLC image
- [] (If applicable) I've reviewed the licenses of updated and new binaries and their dependencies to make sure all licenses are on the Apache Software Foundation Third Party License Policy …
> [Triton] | [Documentation] |  Update Triton DLC v22.07

- release_images.yml
Remove customer type in the release file for PT 1.19
> Minor change in release file

- release_images.yml
remove duplicate item in release_images.yml
> [release] update release_image.yml, remove duplicate

- release_images.yml
PR to update release_images.yml with release config for Neuron SDK 1.19.0
> deep-learning-containers: Release Neuron SDK 1.19.0

- dlc_developer_config.toml
- pytorch/inference/docker/1.12/py3/Dockerfile.graviton.cpu
- testspec.yml
When running sanity test through PR build there is no issue with setting the qemu for graviton, but when going through the pipelines, it fails on this. Removing and going to use a different approach for SageMaker testing with Graviton
By submitting this pull request, I confirm that my contribution is made under the …
> [tensorflow][pytorch][graviton][test] Sanity test fix

- dlc_developer_config.toml
- pytorch/buildspec-graviton.yml
- tensorflow/buildspec-graviton.yml
temporarily disable the SageMaker graviton builds for regular graviton releases.
> [pytorch][tensorflow][graviton][build] temp disable sm-graviton

- release_images.yml
There were mistakes in the release_images.yml file for the Graviton releases. this PR resolves them so releases can happen.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, …
> fixing type and version in release_images

- release/dlc_release_information.py
- release_images.yml
fixing release pipeline for Graviton
> [pytorch][tensorflow][graviton][release] graviton release fix

- release/dlc_release_information.py
- release_images.yml
Removing the graviton entries from release_images.yml
> [pytorch][tensorflow][graviton][cleanup] remove release_image entries for graviton

- available_images.md
Updating available_images with new Graviton images
> [pytorch][tensorflow][graviton]Add new graviton images to available_images

- dlc_developer_config.toml
- pytorch/buildspec.yml
- test/sagemaker_tests/pytorch/training/integration/sagemaker/test_mnist.py
- Added an option in PT SM Toolkit to use the native launcher via a hyperparameter call. This release would pick the latest version of PT SM toolkit https://pypi.org/project/sagemaker-pytorch-training/2.6.2/ 
The native launcher can be invoked using `hyperparameters={"sagemaker_toolkit_native_launcher_enabled": True}` in python SDK estimator call.
- Added 2 new tests for this functionality (cpu and gpu)
**Additionally, please run the …
> [Pytorch] | [build] | [test] | re-release PT 1.12 SM DLCs

- release_images.yml
Release PT-Trcomp PT1.11.0,HF4.21.1 GPU training images
> Release PT-Trcomp images

- release_images.yml
> Release file update for TF 2.8

- release_images.yml
re-release PT1.12 SM training images
> [Pytorch][release] re-release PT1.12 sm training images

- release_images.yml
re-release TF2.7 graviton cpu inference image
> [release][tensorflow][graviton] re-release TF2.7 graviton cpu inference

- available_images.md
Add trcomp images to available_images.yml
> Add trcomp images to available_images.yml

- available_images.md
> add eia container to avaiable_image list

- dlc_developer_config.toml
- tensorflow/buildspec-2-9.yml
- tensorflow/buildspec.yml
- tensorflow/inference/docker/2.10/py3/Dockerfile.cpu
- tensorflow/inference/docker/2.10/py3/cu112/Dockerfile.gpu
- test/dlc_tests/ec2/tensorflow/inference/test_tensorflow_inference.py
* Sagemaker dockerfiles for tensorflow 2.10
* use python3.9
* cuda11.2
> Add Tensorflow Serving dockerfiles for Tensorflow 2.10

- release_images.yml
Add TF 2.10 EC2 to release images yml
> Add TF 2.10 EC2 to release images

- release_images.yml
> Fix variable name for TF 2.10 release

- release_images.yml
> Remove example cpu image for TF 2.10 release

- available_images.md
> Update available_images with TF 2.10 EC2 release

- release_images.yml
> [Pytorch] Re-Release PT1.11

- .release_images_template.yml
- release_images.yml
Change release images for 1.10.2 re-release
> Change release images for 1.10.2 re-release

- release/dlc_release_information.py
- release_images.yml
> [Pytorch] PT1.10 Pip List Failure Fix

- dlc_developer_config.toml
- test/test_utils/security.py
Make the CVSS3 scoring allocation logic same as the scanners.
> Enhanced Scan Test consistency with scanners

- dlc_developer_config.toml
- test/dlc_tests/sanity/resources/allowlist1.json
- test/dlc_tests/sanity/resources/allowlist2.json
- test/dlc_tests/sanity/resources/allowlist_one_minus_two.json
- test/dlc_tests/sanity/resources/allowlist_summation_result.json
- test/dlc_tests/sanity/resources/allowlist_to_read.json
- test/dlc_tests/sanity/resources/allowlist_two_minus_one.json
Fix Unit tests related to Enhanced Scanning Class
> Fix Unit tests related to Enhanced Scanning Class

- test/dlc_tests/conftest.py
> Fix key pair gen

- dlc_developer_config.toml
- habana/pytorch/buildspec.yml
- habana/pytorch/training/docker/1.11/py3/synapseai1.5.0/Dockerfile.hpu
Previous PR https://github.com/aws/deep-learning-containers/pull/2259 erroneously upgraded protobuf to 3.20.2 from 3.19.4, even though there is a patch version 3.19.5 available to fix the same issue. Resetting minor version back to what it previously was. …
> [pytorch][build] Fix Habana PT 1.11 protobuf version

- release_images.yml
Add MX 1.9 EC2 and SM Training to release_images and remove TF 2.10
> [release] Add MX 1.9 EC2 and SM Training to release_images and remove TF 2.10

- release_images.yml
> [release] Add Habana PT 1.11 to release_images

- release_images.yml
Update release images for PT1.10 and TF2.7 Graviton patch release
> Pt110 tf27 graviton CVE release

- README.md
- data/ignore_ids_safety_scan.json
- dlc_developer_config.toml
- tensorflow/inference/docker/2.9/py3/Dockerfile.cpu
- tensorflow/inference/docker/2.9/py3/Dockerfile.graviton.cpu
- tensorflow/inference/docker/2.9/py3/cu112/Dockerfile.gpu
- tensorflow/training/docker/2.9/py3/Dockerfile.cpu
- tensorflow/training/docker/2.9/py3/cu112/Dockerfile.gpu
- test/dlc_tests/sanity/test_safety_check.py
> [OS Patch] TensorFlow 2.9

- release_images.yml
> [release][graviton] fix tf2.7 graviton release

- release_images.yml
> [release] Fix Habana PT 1.5 release configuration

- available_images.md
> Add DXB region to available_images.md file

- src/benchmark_metrics.py
> Add GPT-2 for TF2.9 Benchmark Metrics

- release_images.yml
> [release] Release PT 1.12.1 OS patches images

- available_images.md
> Add TF 2.10 SM DLC to available_images.md

- habana/tensorflow/buildspec-2-9-syai-1-6.yml
- pytorch/buildspec-1-11.yml
- tensorflow/buildspec-2-9.yml
> [OS Patch] Specfiles for habana-tf29, tf29, pt1.11 RC builds

- dlc_developer_config.toml
- tensorflow/buildspec-2-8.yml
- tensorflow/training/docker/2.8/py3/Dockerfile.cpu
- tensorflow/training/docker/2.8/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
- tensorflow/training/docker/2.8/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
- tensorflow/training/docker/2.8/py3/cu112/Dockerfile.ec2.gpu.os_scan_allowlist.json
- tensorflow/training/docker/2.8/py3/cu112/Dockerfile.gpu
- tensorflow/training/docker/2.8/py3/cu112/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
Updating the Tensorflow 2.8 point version from 2.8.0 to TF 2.8.3
> [Tensorflow 2.8.3] Updating TF 2.8 wheels for version 2.8.3

- available_images.md
Update available image TF210 DLC for training compiler in available images ReadMe
> Update available image ReadMe for training compiler

- dlc_developer_config.toml
- tensorflow/buildspec-2-7.yml
- tensorflow/training/docker/2.7/py3/Dockerfile.ec2.cpu
- tensorflow/training/docker/2.7/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
- tensorflow/training/docker/2.7/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
- tensorflow/training/docker/2.7/py3/cu112/Dockerfile.ec2.gpu
- tensorflow/training/docker/2.7/py3/cu112/Dockerfile.ec2.gpu.os_scan_allowlist.json
- tensorflow/training/docker/2.7/py3/cu112/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
Updating the Tensorflow 2.7 point version from 2.7.0 to TF 2.7.4
> [Tensorflow 2.7.4] Updating TF 2.7 wheels for version 2.7.4

- dlc_developer_config.toml
- huggingface/pytorch/buildspec.yml
- huggingface/pytorch/training/docker/1.10/py3/cu113/Dockerfile.gpu.os_scan_allowlist.json
- release_images.yml
> [OS patch] build HF PT1.10 training image

- release_images.yml
> [Release Spec] PT111 TF29 Habana-TF29

- release_images.yml
- tensorflow/buildspec-2-7.yml
> Release TF2.7.4 Training EC2+SM

- dlc_developer_config.toml
- huggingface/pytorch/training/docker/1.10/py3/cu113/Dockerfile.gpu
- release_images.yml
> [OS Patch] build HF PT 1.10 training image

- dlc_developer_config.toml
- tensorflow/buildspec-2-7.yml
> ReBuilding Example Image for TF2.7.4

- dlc_developer_config.toml
- test/dlc_tests/sanity/test_ecr_scan.py
- test/test_utils/security.py
The allowlist path for example images was not working correctly. This PR helps rectify that. The change was already tested on the PR2328. …
> [Test][ECREnhancedScan] Rectify the example image allowlist extraction

- dlc_developer_config.toml
- tensorflow/buildspec-2-8.yml
- tensorflow/inference/docker/2.8/py3/Dockerfile.cpu
- tensorflow/inference/docker/2.8/py3/cu112/Dockerfile.gpu
Testing security updates for TFS 2.8
> [TFS 2.8] Security updates for TFS 2.8.3

- dlc_developer_config.toml
- tensorflow/buildspec-2-9.yml
- tensorflow/inference/docker/2.9/py3/Dockerfile.cpu
- tensorflow/inference/docker/2.9/py3/cu112/Dockerfile.gpu
Testing security updates for TFS 2.9
> [TFS 2.9] Security updates for TFS 2.9.2

- autogluon/inference/docker/0.4/py3/Dockerfile.cpu
- autogluon/inference/docker/0.4/py3/Dockerfile.cpu.os_scan_allowlist.json
- autogluon/inference/docker/0.4/py3/cu112/Dockerfile.gpu
- autogluon/inference/docker/0.4/py3/cu112/Dockerfile.gpu.os_scan_allowlist.json
- autogluon/inference/docker/0.5/py3/Dockerfile.cpu
- autogluon/inference/docker/0.5/py3/Dockerfile.cpu.os_scan_allowlist.json
- autogluon/inference/docker/0.5/py3/cu112/Dockerfile.gpu
- autogluon/inference/docker/0.5/py3/cu112/Dockerfile.gpu.os_scan_allowlist.json
- autogluon/training/docker/0.4/py3/Dockerfile.cpu
- autogluon/training/docker/0.4/py3/Dockerfile.cpu.os_scan_allowlist.json
- autogluon/training/docker/0.4/py3/cu112/Dockerfile.gpu
- autogluon/training/docker/0.4/py3/cu112/Dockerfile.gpu.os_scan_allowlist.json
- autogluon/training/docker/0.5/py3/Dockerfile.cpu
- autogluon/training/docker/0.5/py3/Dockerfile.cpu.os_scan_allowlist.json
- autogluon/training/docker/0.5/py3/cu112/Dockerfile.gpu
- autogluon/training/docker/0.5/py3/cu112/Dockerfile.gpu.os_scan_allowlist.json
- data/ignore_ids_safety_scan.json
- dlc_developer_config.toml
- test/dlc_tests/sanity/test_safety_check.py
Adding exclusions until upstream dependencies are updated
> [autogluon][build] Updating scan configuration

- available_images.md
Add neuron images to `available_images.md`
> [NEURON][PT][TRAIN] - Release of trn1 DLC image.

- release_images.yml
> add tf 2.8 and tf 2.9 inference to release images

- autogluon/inference/docker/0.4/py3/Dockerfile.cpu
- autogluon/inference/docker/0.4/py3/cu112/Dockerfile.gpu
- autogluon/inference/docker/0.5/py3/Dockerfile.cpu
- autogluon/inference/docker/0.5/py3/cu112/Dockerfile.gpu
- autogluon/training/docker/0.4/py3/Dockerfile.cpu
- autogluon/training/docker/0.4/py3/cu112/Dockerfile.gpu
- autogluon/training/docker/0.5/py3/Dockerfile.cpu
- autogluon/training/docker/0.5/py3/cu112/Dockerfile.gpu
>  [autogluon][build] Updating sagemaker dependency handling

- release_images.yml
> [AutoGluon][Release] Release for AG.5 Training + Inference

- .release_images_template.yml
- release_images.yml
Release Images Update for AG 0.4.3, added 0.5.2 to the release templates for future reference
> [AutoGluon][Release] Release for AG 0.4.3 Training + Inference

- dlc_developer_config.toml
- test/dlc_tests/sanity/test_ecr_scan.py
- test/test_utils/__init__.py
*GitHub Issue #, if available:* 
Expand ECR Enhanced Scanning and make it easily usable for non dlc images by using ENV variables. The non dlc images do not have fw version in them and other things in the tag. This PR ensures that the code does not try to extract those for the non dlc images and allows all the ECR scans to run on the images as well. …
> Expand ECR Enhanced Scanning and make it easily usable for non dlc images

- dlc_developer_config.toml
- pytorch/buildspec-1-11.yml
- test/dlc_tests/sanity/test_safety_check.py
PR to create Pytorch 1.11 Inference images fix
> [build] Pytorch 1.11 Inference images fix

- data/common-ecr-scan-allowlist.json
- dlc_developer_config.toml
> [GRAVITON] minor package update

- release_images.yml
> [Graviton][SageMaker][Release] PT and TF Graviton SM

- release_images.yml
Issue #: #2322 
Fix tf eia vulnerabilities
> Add schema to release EIA tensorflow image

- release/dlc_release_information.py
Update docker start permission in support for qemu start
> [release][fix] Fix for graviton release information

- release_images.yml
Issue #2318 
Patch Pytorch 1.11 Inference images
> add schema to release pytorch 1.11

- pytorch/training/docker/1.11/py3/sdk2.3.0/Dockerfile.neuron
- pytorch/training/docker/1.11/py3/sdk2.4.0/Dockerfile.neuron
fix license for PT1.11 neuron DLC
> fix license for PT1.11 neuron DLC

- release_images.yml
Release PT1.11 with neuron sdkv2.4.0
> [release] neuron sdk v2.4 release

- release_images.yml
remove regular PT1.11 from release_images
> remove regular PT1.11 from release_images

- available_images.md
update available_images with neuron sdk v2.4.0
> update available_images with neuron sdk v2.4.0

- available_images.md
- Update DJL images in available images markdown
> Update available images for DJL Serving image

- release_images.yml
> Releasing patch for HF PT 1.11

- huggingface/pytorch/training/docker/1.11/py3/cu113/Dockerfile.trcomp.gpu.os_scan_allowlist.json
- release_images.yml
> Hf pt 111 allowlist update

- dlc_developer_config.toml
- huggingface/pytorch/training/docker/1.11/py3/cu113/Dockerfile.trcomp.gpu
> fix: Trcomp HF-pt 111 has broken package - sagemaker

- release_images.yml
Update release_images.yml for release PyTorch 1.13 for EC2
> [release][pytorch] Release PyTorch 1.13 EC2

- release_images.yml
- Update release imgs yaml file
> Remove training images from PT 1.13 release yaml

- test/test_utils/__init__.py
- Update canary logic for PT 1.13, which introduces py39 in pytorch containers
> Update python version for PT 1.13 canaries

- available_images.md
- release_images.yml
Post release cleanup.
* Add to Inference images to available_images.md
* remove images from release
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> [post-release] post work for PT1.13 inference release

- .release_images_template.yml
- release_images.yml
> feat: release PT-1.13 example image

- available_images.md
- Remove unsupported images from available images markdown file
> Remove unsupported images from available images markdown

- available_images.md
> doc: update pt-1.13 ec2 training images in markdown

- release_images.yml
Re-release PT 1.5.1 EIA images
Using same definition as here:
https://github.com/aws/deep-learning-containers/commit/64efb405ccc81e011090565fbffb80160457d7d5
> Release PT 1.5.1 EIA images

- test/test_utils/sagemaker.py
> Adding exception logging line to local tests.

- dlc_developer_config.toml
- pytorch/inference/docker/1.5.1/py38/Dockerfile.eia
> [pytorch][eia][build]Patch Pillow for pt 1.5.1 eia

- test/test_utils/__init__.py
> Temporarily reverting AMI to CUDA 11.

- release_images.yml
> Releasing patched MXNet images.

- test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference.py
- test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py
> Updating training test and fixing inference torchdata tests

- dlc_developer_config.toml
- pytorch/inference/docker/1.12/py3/Dockerfile.graviton.cpu
- test/test_utils/sagemaker.py
Patching vulnerability found in PyTorch Graviton image associated with the Pillow package <9.3.0.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> [pytorch][graviton][build] Patching pillow in pytorch graviton 1.12

- release_images.yml
> Releasing patched images for PT 1.12.

- release_images.yml
> Release MXNet SM images

- release_images.yml
> Release TF EIA images

- release_images.yml
Prep to release graviton images for TF 2.9.1 and PT 1.12.1. Modified release_images.yml file to add configurations for the release of the images. Both EC2 and Sagemaker images alike will be released based on these configurations.
By submitting this pull request, I confirm that my contribution is made under the terms …
> Update release config to release TF 2.9.1 and PT 1.12.1 graviton images

- release_images.yml
Updated the release image YAML to release the graviton images of PT 1.12.1 and TF 2.9.1.
> Releasing graviton images for PT 1.12 and TF 2.9.1

- tensorflow/training/docker/2.10/py3/Dockerfile.cpu
- tensorflow/training/docker/2.10/py3/cu112/Dockerfile.gpu
> Pinning version to isolate toolkit error

- tensorflow/training/docker/2.9/py3/Dockerfile.cpu
- tensorflow/training/docker/2.9/py3/cu112/Dockerfile.gpu
> TF 2.9 Pinning SM Toolkit version to isolate error.

- release_images.yml
Release Images File for the following release:
- EC2 Release 
- Inference and Training
- SM Release
- Inference
> TF2.11 EC2 Release for Training + Inference, SM Release for Inference

- release_images.yml
> [TensorFlow] Fix for TF2.11 Release

- available_images.md
> doc: remove eia images

- test/test_utils/ec2.py
- test/test_utils/sagemaker.py
Fix the `dpkg lock-frontend` error that sometimes arises when running `apt-get update` immediately after launching the EC2 instance …
> [test] Fix dpkg lock-frontend error when installing python

- dlc_developer_config.toml
- tensorflow/buildspec-2-10.yml
- tensorflow/training/buildspec-2-10.yml
- tensorflow/training/docker/2.10/py3/Dockerfile.cpu
- tensorflow/training/docker/2.10/py3/cu112/Dockerfile.gpu
Remove python kernel installed by sparkmagic 
> Remove python kernel installed by sparkmagic

- release_images.yml
release TF2.10.1 training  and PT 1.12 trcomp images
> [release][TF][PT] release TF2.10.1 training and PT 1.12 trcomp images

- available_images.md
> doc: PT-1.13 python version

- available_images.md
update available_images.md with PT1.12 trcomp DLC
> [PT][trcomp] update available_images.md with PT1.12 trcomp DLC

- .github/CODEOWNERS
> Remove regular frameworks from codeowners file

- dlc_developer_config.toml
- pytorch/buildspec-1-12.yml
- src/config.py
- src/start_testbuilds.py
- test/dlc_tests/sanity/quick_checks/test_dlc_developer_config.py
- test/sagemaker_tests/__init__.py
- test/sagemaker_tests/pytorch/training/__init__.py
- test/sagemaker_tests/pytorch/training/conftest.py
- test/sagemaker_tests/pytorch/training/integration/sagemaker/__init__.py
- test/sagemaker_tests/pytorch/training/integration/sagemaker/test_distributed_operations.py
- test/sagemaker_tests/pytorch/training/integration/sagemaker/test_pytorchddp.py
- test/sagemaker_tests/pytorch/training/integration/sagemaker/test_smdataparallel.py
- test/sagemaker_tests/tensorflow/tensorflow2_training/integration/sagemaker/test_smmodelparallel.py
- test/test_utils/__init__.py
- test/test_utils/sagemaker.py
> [test] Add p4de instance test on SM

- dlc_developer_config.toml
Remove all non-default values defined in dlc_developer_config.toml file
> Bug fix to cleanup dev config toml file

- dlc_developer_config.toml
- test/sagemaker_tests/tensorflow/inference/requirements.txt
https://github.com/pypa/packaging/pull/407
Packaging dropped support for "LegacyVersion" (https://github.com/pypa/packaging/pull/407) As a result SM tests have been failing. Pinning to a previous version should resolve the issue
By submitting this pull request, I confirm that my contribution is made under the terms …
> pinning packaging to 21.3 for sm tests

- available_images.md
> Delisting TF 2.6 Trcomp image

- release_images.yml
* Release of TF Inference 2.9.2 images (EC2 and SageMaker)
> [release][TF] release TF 2.9.2 Inference images

- release_images.yml
Release "Patched" PT 1.13.0 for EC2 and PT 1.13.0 SM "CPU only"
> [release][pytorch]  PT 1.13.0 patch release and PT 1.13.0 SM "cpu" release

- release_images.yml
> Added configurations to release PyTorch Inference 1.12

- release_images.yml
> [Release] MxNet 1.9 image release_images.yml changes

- release_images.yml
release PT1.13 EC2 Training DLC
> release PT1.13 EC2 Training DLC

- release_images.yml
> [release] Add PT 1.12.1 training DLCs to release

- release_images.yml
- Release DJL 0.20.0 containers
> Release DJL 0.20.0 containers

- release_images.yml
> tf 2.10.1 release images

- release_images.yml
> Updating release YAML to release AG 0.6.1

- release_images.yml
> Release mx1.8,tf1.15.5,tf2.8.0 for sdk2.5.0

- autogluon/training/docker/0.6/py3/Dockerfile.cpu
- autogluon/training/docker/0.6/py3/Dockerfile.cpu.os_scan_allowlist.json
- autogluon/training/docker/0.6/py3/cu113/Dockerfile.gpu
- autogluon/training/docker/0.6/py3/cu113/Dockerfile.gpu.os_scan_allowlist.json
> AG 0.6.1 Training Security Fixes

- release_images.yml
> Releasing Training AG 0.6.1

- available_images.md
> [NEURON][RELEASE] - Update the available images for sdk2.5.0

- release_images.yml
> [NEURON][PT] - Update the release images.

- release_images.yml
> Remove PT 1.12 non-neuron images

- available_images.md
Updated available container images
>  [autogluon][doc] AutoGluon 0.6.1 available images update

- tensorflow/buildspec-2-8.yml
> Modifying buildspec to build RCs

- available_images.md
> Add Neuron SDK 2.5.0 PT1.12 to available images

- release_images.yml
> Add schema to release tensorflow 2.8.4 images

- data/ignore_ids_safety_scan.json
- dlc_developer_config.toml
- pytorch/buildspec.yml
- pytorch/inference/docker/1.13/py3/Dockerfile.cpu
- pytorch/inference/docker/1.13/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
- pytorch/inference/docker/1.13/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
- pytorch/inference/docker/1.13/py3/cu117/Dockerfile.ec2.gpu.os_scan_allowlist.json
- pytorch/inference/docker/1.13/py3/cu117/Dockerfile.gpu
- pytorch/inference/docker/1.13/py3/cu117/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
> Re-release of PT 1.13.1

- release_images.yml
> Update config to release PyTorch 1.13.1

- dlc_developer_config.toml
- test/sagemaker_tests/pytorch/training/requirements.txt
> refactor: unpin sagemaker in test requirement

- dlc_developer_config.toml
- tensorflow/buildspec-2-9.yml
- tensorflow/inference/docker/2.9/py3/Dockerfile.cpu
- tensorflow/inference/docker/2.9/py3/cu112/Dockerfile.gpu
- test/dlc_tests/sanity/test_pre_release.py
> [Tensorflow] [Inference]TF 2.9.3 release

- release_images.yml
> [Tensorflow] 2.9.3 release images 

- available_images.md
Update list of available Triton container images
> [Triton] | [Documentation] Update Triton container available images

- release_images.yml
> Release PT 1.11 ec2 and sagemaker images

- test/dlc_tests/sanity/test_canary_integration.py
- test/test_utils/__init__.py
- Add inference canary logic; Add pull test for training/inference respectively
> Add inference specific canary logic

- dlc_developer_config.toml
- src/benchmark_metrics.py
- test/dlc_tests/benchmark/sagemaker/tensorflow/training/test_trcomp_performance.py
> [tensorflow] [2.11] [benchmark] fix issues with trcomp benchmarks

- available_images.md
> [Tensorflow] [Inference] updating available images for TF 2.9.3

- dlc_developer_config.toml
- pytorch/buildspec-1-11.yml
> Update PT 1.11 inference images

- dlc_developer_config.toml
- tensorflow/buildspec.yml
PR to fix Release Candidate Builds Failing due to invalid image size
**TensorflowExampleGpuCu112**
image_size:9288.288105010986     
image_size_baseline:7738 
**TensorflowSageMakerGpuPy39Cu112**
image_size_baseline:11000
image_size:11994.760071754456
By submitting this pull request, I confirm that my contribution is …
> [TensorFlow][2.11] Increase TF2.11 Build Image Baseline

- .release_images_template.yml
- release_images.yml
> Release PT-1.11.0, PT-1.12.1 training image

- release_images.yml
Release Images Update to Release TF2.11 SM Training
> [TensorFlow][Release] Release for TF2.11 SM Training

- dlc_developer_config.toml
- pytorch/buildspec.yml
- pytorch/inference/docker/1.13/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
- pytorch/inference/docker/1.13/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
- pytorch/inference/docker/1.13/py3/cu117/Dockerfile.ec2.gpu.os_scan_allowlist.json
- pytorch/inference/docker/1.13/py3/cu117/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
> [pytorch][test] Re-Release work PT 1.13 Inference EC2/SM

- release_images.yml
- Add DJL release definitions for image re-releases
> Add DJL release definitions

- available_images.md
Update Available Images with TF2.11  SM
> [TensorFlow] Updated Available images for TF2.11

- release_images.yml
Re-releaseing PT 1.13.1 EC2 (GPU/CPU) and PT 1.13.1 SM (CPU). This will also include the release of PT 1.13.1 SM (GPU).
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under …
> [pytorch][release] PT 1.13.1 EC2/SM CPU/GPU release

- release_images.yml
- release PT 1.11 inference images
> Update release images yml for PT 1.11 inference release

- dlc_developer_config.toml
- tensorflow/buildspec.yml
> Patch Tensorflow 2.11 images

- dlc_developer_config.toml
- pytorch/buildspec-1-12.yml
- pytorch/inference/docker/1.12/py3/Dockerfile.cpu
- pytorch/inference/docker/1.12/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
- pytorch/inference/docker/1.12/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
- pytorch/inference/docker/1.12/py3/cu113/Dockerfile.ec2.gpu.os_scan_allowlist.json
- pytorch/inference/docker/1.12/py3/cu113/Dockerfile.gpu
- pytorch/inference/docker/1.12/py3/cu113/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
- pytorch/inference/docker/1.12/py3/cu116/Dockerfile.ec2.gpu.os_scan_allowlist.json
- pytorch/inference/docker/1.12/py3/cu116/Dockerfile.gpu
- pytorch/inference/docker/1.12/py3/cu116/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
> Patch PyTorch 1.12 - add changes to initiate PR tests

- dlc_developer_config.toml
- tensorflow/training/docker/2.11/py3/Dockerfile.cpu
- tensorflow/training/docker/2.11/py3/cu112/Dockerfile.gpu
- test/dlc_tests/sanity/test_utility_installation.py
Updating TF2.11 DockerFile with the removal of a python kernel that is installed by sparkmagic that causes issues when importing tensorflow through SageMaker.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, …
> [TensorFlow] Removed Kernel Installed by Spark Magic in TF2.11

- available_images.md
- release_images.yml
Update release_images to re-release PT 1.12.1 Graviton
Update available_images for PT 1.13.1 x86_64 (updating EC2 and adding SM) …
> Update release_images and available_images

- dlc_developer_config.toml
- pytorch/inference/docker/1.12/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
- pytorch/inference/docker/1.12/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
- pytorch/inference/docker/1.12/py3/cu113/Dockerfile.ec2.gpu.os_scan_allowlist.json
- pytorch/inference/docker/1.12/py3/cu113/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
- pytorch/inference/docker/1.12/py3/cu116/Dockerfile.ec2.gpu.os_scan_allowlist.json
- pytorch/inference/docker/1.12/py3/cu116/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
> Updating PT 1.12 allowlists with vulnerability sets

- release_images.yml
> Adding release schema for TF 2.8

- release_images.yml
> Update configuration for re-release of PT 1.12

- release_images.yml
> [tensorflow][graviton] re-release TensorFlow 2.9.1 graviton for patching

- release_images.yml
Prepare release yaml for DJL release
> Add DJL 0.19.0 and 0.20.0 release definitions

- release_images.yml
Re-Release images for patching.
> [pytorch] Re-Release PyTorch 1.12.1-graviton and PyTorch 1.13.1

- dlc_developer_config.toml
- mxnet/inference/docker/1.9/py3/Dockerfile.cpu
- mxnet/inference/docker/1.9/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json
- mxnet/inference/docker/1.9/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
- mxnet/inference/docker/1.9/py3/cu112/Dockerfile.gpu
- test/test_utils/__init__.py
> [MxNet][Inference] Patch MxNet1.9 Inference DLCs

- release_images.yml
> 2.9.3 release images

- dlc_developer_config.toml
- tensorflow/buildspec-2-9.yml
- tensorflow/training/buildspec-2-9.yml
- test/dlc_tests/benchmark/sagemaker/tensorflow/training/test_trcomp_performance.py
> [TensorFlow][Training] TRComp TF2.9 Fix for Benchmark Tests

- release_images.yml
Release Schema update to release TF2.9.3
> [TensorFlow][Training] Release TF2.9.3

- dlc_developer_config.toml
- tensorflow/buildspec.yml
> Update buildspec and run PR tests for tensorflow 2.11

- dlc_developer_config.toml
- tensorflow/buildspec-2-8.yml
> Update buildspec and run PR test for tensorflow 2.8

- release_images.yml
Add definitions to release images of TF 2.11, TF 2.8 and PT 1.12.
> Update release image configuration

- README.md
Repo README currently references framework/buildspec.yml files. Update to include job type in path
> Update README to reflect new buildspec location

- test/sagemaker_tests/pytorch/training/conftest.py
> fix: add py39 version for sm

- dlc_developer_config.toml
- src/utils.py
- Remove changeset logic for running/executing tests
> [src] Remove changeset logic for test running

- available_images.md
> Release image

- release_images.yml
This change adds the release configurations required to release images of Tensorflow 2.8.4 and Tensorflow 2.11.
No test required for this change.
* When …
> [tensorflow]Adding configuration to release TF 2.8 and 2.11

- available_images.md
1. SM Triton version 22.12 is now GA, adding it to the list of available images …
> [Triton] | [Documentation] Add 22.12 to the list of available images

- release_images_inference.yml
Release MxNet 1.9 innference images …
> [MxNet][Inference] Release MxNet 1.9 innference images

- release_images_inference.yml
Fix indentation issues in release_images_inference.yml
By submitting this pull request, I confirm that my contribution is made under the …
> [MxNet] [Inference] Fix indentation issues in release_images_inference.yml

- release_images_training.yml
> chore: add trcomp release config

- release_images_inference.yml
Update release_images_inference.yml for EIA PT 1.5.1 and EIA TF 2.3.0. Both images have completed RC build and testing
PR Quick Checks on [76486d8](https://github.com/aws/deep-learning-containers/pull/2695/commits/76486d83472fd5570ab714371583d3f484b18556)
> [EIA] patch release

- release_images_training.yml
Configure release_images_training.yml to release AG 0.6.2 Training DLC images …
> [release] Configure release for AG 0.6.2 Training DLCs

- available_images.md
N/A
Update available_images for AutoGluon 0.6.2 release
> [autogluon][doc] AutoGluon 0.6.2 available images update

- release_images_inference.yml
Update release_images_inference.yml for re-release of PT 1.12.1 Graviton
Test dlc-pr-quick-checks [86f1f58](https://github.com/aws/deep-learning-containers/pull/2712/commits/86f1f5820427e1c2512c3f51f2b0ffc5fd06b30f)
> [graviton][release] re-release PT 1.12.1 Graviton

- release_images_inference.yml
PR to release images for Tensorflow Inference DLC v2.11.0 and PyTorch Inference DLC v1.12.1.
No test required for updating release image YAML file.
* When …
> Add schema definitions to release PT 1.12 and TF 2.11 images

- release_images_training.yml
release pt1.11/1.12/1.13 training images
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> release pt1.11/1.12/1.13 training images

- release_images_training.yml
release HF PT1.13
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I …
> release HF PT1.13
