available_images.md
update available images with HF PT1.13
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> update available images with HF PT1.13

release_images_inference.yml
Update release_images_inference.yml for PT 1.13.1 patch release
Quick PR check test on first commit
=> [pytorch][release] patch release PT 1.13.1

dlc_developer_config.toml, huggingface/pytorch/training/docker/1.11/py3/cu113/Dockerfile.trcomp.gpu, huggingface/pytorch/training/docker/1.11/py3/cu113/Dockerfile.trcomp.gpu.os_scan_allowlist.json
=> Trcomp 1.11 CVE

release_images_inference.yml
- Update inference release definition for DJL 0.21.0 images
- Remove definitions from previous releases
=> Release DJL 0.21.0 images

available_images.md
Change to add new region to list of available region
No test required.
By submitting this pull request, I confirm that my contribution is …
=> Add new region to list of DLC available regions

available_images.md
- update available images MD file with DJL 0.21.0 release
=> Update available images with DJL 0.21.0 release

release_images_inference.yml
- Re-release MX 1.9 DLCs for patching
=> Release MX 1.9 images

release_images_inference.yml
- Update release images yml file for PT1.11 inference release
=> [pt 1.11] Update release_images_inference.yml

release_images_inference.yml
- release HF PT 1.13 inference images
=> Release HF PT 1.13 inference images

available_images.md
- Update available images markdown file with HF PT 1.13 release
=> Update available images markdown with HF PT 1.13 release

eks_infrastructure/build_param.json
Updating EKS cluster to the latest version.
This commit is for testing initial update using PR context for MXNET cluster.
By submitting …
=> Update EKS cluster

release_images_inference.yml
- Add release definition for DJL fastertransformer release
=> [djlserving] Release fastertransformer container

available_images.md
- Add DJL 0.21 fastertransformer release to available images 
- No additional tests run, markdown change only
=> Add DJL fastertransformer release to available images

available_images.md
- Update available images for DJL cpu full release
- No tests run outside default quickchecks tests as this is a markdown file change
=> Update available images for DJL cpu full release

dlc_developer_config.toml, tensorflow/inference/docker/build_artifacts/sagemaker/python_service.py, tensorflow/inference/docker/build_artifacts/sagemaker/serve.py
[8b28154](https://github.com/aws/deep-learning-containers/pull/2765/commits/8b28154f11df74318f90e19814555e7c924143ee) tf 2.11
- Sanity Test
- EC2 test
- ECS test
- EKS test
- …
=> Pass TFS parameter for mme use case.

eks_infrastructure/build_param.json, eks_infrastructure/delete_cluster.sh
This PR creates new kubernetes clusters for MxNet, PyTorch and Tensorflow as part of a test deployment. 
Part of test deployment of clusters. …
=> Create new k8s clusters

eks_infrastructure/env_setup.sh
Remove condition and force installing aws-iam-authenticator. Required to to provide authentication to Kubernetes clusters.
N/A.
By …
=> Remove conditional installation of aws-iam-authenticator

test/dlc_tests/eks/eks_manifest_templates/kubeflow/install_kubeflow.sh
Fixing negation error when checking for the existence of the sudo command. …
=> Fix negation error

eks_infrastructure/build_param.json
create tf mainline eks cluster
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> create tf mainline eks cluster

release_images_inference.yml
This PR is to update the FasterTransformer DLC image and apply the tracker
=> [DLC][Inference][FasterTransformer][LMI] update the tracker

eks_infrastructure/build_param.json, test/test_utils/eks.py
Populate cluster build parameter and create new kubernetes clusters for mxnet, pytorch and tensorflow frameworks.
N/A
By submitting this …
=> Recreate k8s clusters for DLC frameworks

available_images.md
=> [Triton] | [Docs] | Add Triton v23.01 to docs

release_images_inference.yml
Release Autogluon Inference image v0.7.0.
N/A
By submitting this pull request, I confirm that my contribution is made under the terms of …
=> Release autogluon inference v0.7.0

eks_infrastructure/build_param.json, eks_infrastructure/build_param.template
Update build_param.json file.
N/A …
=> Updating build param json file

dlc_developer_config.toml, tensorflow/training/docker/2.11/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json, tensorflow/training/docker/2.11/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json, tensorflow/training/docker/2.11/py3/cu112/Dockerfile.ec2.gpu.os_scan_allowlist.json, tensorflow/training/docker/2.11/py3/cu112/Dockerfile.sagemaker.gpu.os_scan_allowlist.json, tensorflow/training/docker/2.11/py3/example/Dockerfile.gpu.example.os_scan_allowlist.json
Change the allowlist file to match the flagged cve.
By submitting this pull request, I confirm that my contribution is made under the …
=> Allowlist modification TF2.11

release_images_training.yml
=> Add PT1.13 training Neuron release

available_images.md
=> Update Neuron Pytorch training image URL

release_images_training.yml
This PR is to release Autogluon 0.7.0 for training DLC
By submitting this pull request, I confirm that my contribution is made under the …
=> Release Autogluon0.7 training

release_images_inference.yml
Release TF2.10.1 Inference DLCs
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> [Tensorflow] Release TF2.10.1 Inference DLCs

eks_infrastructure/build_param.json
=> add graviton support for eks

release_images_inference.yml
Release TF2.9.3 inference images …
=> [Tensorflow] Release TF2.9.3 inference images

release_images_inference.yml
Add release definition for HF TF 2.11 images
Run tests from quick checks (every commit)
=> Release HF TF 2.11 images

test/sagemaker_tests/autogluon/training/conftest.py
Add support for py39 version for autogluon training DLC in sagemaker test
By submitting this pull request, I confirm that my contribution …
=> [autogluon][test][sagemaker]Add support for py39 version in tests

release_images_inference.yml
- Re-release HF PT 1.13 images
- Run quick checks sanity tests (every commit)
=> Re-release HF PT 1.13 images

release_images_inference.yml
=> Add Neuron TF 115 to release images

release_images_training.yml
=> release TF2.12 ec2 DLC

available_images.md
=> update available_images.md with TF2.12 EC2 DLC

dlc_developer_config.toml, pytorch/inference/buildspec-1-13.yml, pytorch/inference/buildspec-graviton-1-12.yml, pytorch/inference/buildspec-graviton.yml, pytorch/inference/buildspec.yml, pytorch/inference/docker/2.0/py3/Dockerfile.cpu, pytorch/inference/docker/2.0/py3/Dockerfile.graviton.cpu, pytorch/inference/docker/2.0/py3/cu118/Dockerfile.gpu
Updating the following to the codebase for PT 2.0 Currency
* Add folder structure for PT 2.0 Inference
* Add PT 2.0 Dockerfile for x86_64 CPU
* Add PT 2.0 Dockerfile for x86_64 GPU
* Add PT 2.0 Dockerfile for Graviton
* Create buildspec for PT 1.13.1 x86_64 GPU/CPU for patching
* Create buildspec for PT 1.12.1 Graviton for patching
* Update main x86_64 CPU/GPU buildspec for PT 2.0
* Update main Graviton buildspec for PT 2.0
__NOTE:__ Much of the work are in PRs [2753](https://github.com/aws/deep-learning-containers/pull/2753) and [2737](https://github.com/aws/deep-learning-containers/pull/2737). This PR is created for …
=> [PyTorch][x86_64][graviton] PT 2.0 Currency addition

dlc_developer_config.toml, test/dlc_tests/sanity/test_pre_release.py
[PR-2742](https://github.com/aws/deep-learning-containers/pull/2742) has changes which breaks the pre_release_test for Inference DLCs. This PR is the fix.
=> [pytorch][inference] Fix pre release test for inference

dlc_developer_config.toml, test/dlc_tests/sanity/test_telemetry.py
=> pt2 ec2 sanity fix

dlc_developer_config.toml, pytorch/training/docker/2.0/py3/Dockerfile.cpu, pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu
=> temporarily remove fastai from pytorch DLC

dlc_developer_config.toml, test/dlc_tests/sanity/test_telemetry.py
=> Prevent possible telemetry instance hanging from timing out the sanity tests

release_images_inference.yml
updated release images to only have graviton
pt quick test on initial comit
=> [pytorch][graviton][release] complete PT 2.0.0 graviton release

release_images_inference.yml
Inference Release images file set to only release PT2.0.0 x86_64 (CPU/GPU)
PR Quick Check on initial commit
=> [pytorch][x86_64][release] Release x86_64 PT2.0.0 inference

available_images.md, test/test_utils/__init__.py
* Add PT 2.0 x86_64 EC2 (GPU/CPU/Graviton) to available image
* fix PT 2.0 x86_64 canary
PR quick checks on initial commit
=> add 2.0 to avail images and fix canary

release_images_inference.yml
Release TF Inference 2.11.1 images …
=> [Release][Tensorflow][Inference] Release TF Inference 2.11.1 images

release_images_training.yml
=> Release TF 2.11.1 training DLC

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/stale_pr.yml
New PR checker for Stale PR's, will close old PR's
- Manual Run on local branch
=> Stale PR Checker and Remover

dlc_developer_config.toml, pytorch/inference/buildspec-graviton.yml, pytorch/inference/buildspec.yml, test/sagemaker_tests/pytorch/inference/integration/local/test_serving.py
* testing for PT 2.0 SM images
* Fix issue with PT 2.0 SM Local Test (will need to be refactored later)
Commit: [e55803](https://github.com/aws/deep-learning-containers/pull/2836/commits/3e5580307ece1a13ab7766eece9424e4617d1607)
* Graviton Build
* Graviton EC2 tests
* Graviton EKS tests
* Graviton ECS tests
* Graviton SM Local tests
* Graviton SM Remote "Standard" tests
* Graviton Sanity tests
Commit: [3372c9e](https://github.com/aws/deep-learning-containers/pull/2836/commits/3372c9eb36396c68789f8ad604662ead2829dd9e)
* Build
* EC2 tests
* EKS tests
* ECS tests
* SM Local tests
* SM Remote "Standard" tests
* Sanity tests …
=> [PyTorch][SageMager][x86_64][Graviton] PT 2.0 SM currency

available_images.md
=> Add training EC2 DLCs to available image

dlc_developer_config.toml, src/config.py, src/image_builder.py, src/main.py
=> [NEURON][ALL][BUILD] Make sure enabling neuron doesn't also enable neuronx

dlc_developer_config.toml, tensorflow/inference/docker/1.15/py3/sdk2.8.0/Dockerfile.neuron.os_scan_allowlist.json, tensorflow/inference/docker/2.10/py3/sdk2.9.0/Dockerfile.neuron.os_scan_allowlist.json
=> [NEURON][TF][BUILD] - Whitelist more Neuron TF 2.10.1 vulnerabilities

release_images_inference.yml
=> Add Neuron Tensorflow 2.10.1 to release_images

dlc_developer_config.toml, huggingface/pytorch/inference/docker/1.13/py3/Dockerfile.cpu, test/sagemaker_tests/huggingface/inference/integration/__init__.py, test/sagemaker_tests/huggingface/inference/integration/sagemaker/test_ipex_inference.py, test/sagemaker_tests/huggingface/inference/resources/code/ipex_inference.py
This PR adds IPEx dependency to PyTorch HF DLC for inference.
- New IPEx test added - developer ran tests but commit history lost
=> [huggingface_pytorch_inference] Add IPEx dependency in pytorch inference.

release_images_inference.yml
**Note**: 
- Add release definition for HF TF 2.11.1 and HF PT 1.13
- Tests run on quick checks
=> Release HF TF2.11.1 and HF PT 1.13

available_images.md
=> Add TF 2.10 Neuron inference image to available_images

.release_images_template.yml, release_images_inference.yml
=> [BUILD][PT][NEURON] Add PT NeuronX release image to template

release_images_inference.yml
=> [BUILD][TF][NEURON] Add TF 2.10.1 NeuronX to releases

.release_images_template.yml, release_images_inference.yml
=> [BUILD] Remove newly released NeuronX images from release_images_inference.yml

release_images_inference.yml
**Note**: 
Release PT 2.0 SM/EC2 x86_64/Graviton
Quick PR checks on initial commit
=> [pytorch][release] Add PT 2.0 releases SM/EC2 x86_64/Graviton

release_images_inference.yml
**Note**: 
Fix 0.21.0 post release steps for DJL
Run tests from quickchecks
=> DJL 0.21.0 deepspeed 0.8.3 release

test/sagemaker_tests/pytorch/inference/conftest.py
**Note**: 
Need to add PY 3.10 to the release sagemaker tests. This is not seen during SM local, SM remote or Local Testing.
As the test getting updated is not a PR test, only the PR quicks checks is done on the initial commit.
=> [pytorch][release] Ddd PT 3.10 to release images test

release_images_inference.yml
**Note**: 
Release DJL 0.21.0 fastertransformer 5.3.0
Run quick checks tests (every commit)
=> release DJL 0.21.0 fastertransformer 5.3.0

available_images.md
update the container image to reflect the most recent update on the DeepSpeed DLC.
=> update container image

release_images_inference.yml
**Note**: 
- Release DJL CPU full 0.21.0 image
Run tests from quick checks (runs every commit)
=> Release DJL 0.21.0 cpu full

available_images.md
**Note**: 
Add TF inference 2.11.1 images to `available_images.yml`.  …
=> [Tensorflow] Update available_images.md for Tensorflow Inference

release_images_inference.yml
**Note**: 
Add PT 1.13.1 and PT 1.12.1 graviton (SM and EC2) to inference image release file.
PR quick checks on initial commit
=> add pt1.13.1 and pt1.12.1 graviton patch release

test/dlc_tests/eks/eks_manifest_templates/kubeflow/install_kubeflow.sh
**Note**: 
remove kubeflow namespace uninstallation step since it goes in never ending loop. We will keep the kubeflow namespace as is during uninstallation of older version of kubeflow. …
=> remove kubeflow namespace uninstallation step

available_images.md
=> Add PT-1.13.1 training EC2 to prior available images

eks_infrastructure/build_param.json, test/dlc_tests/eks/eks_manifest_templates/kubeflow/install_kubeflow.sh
**Note**: 
Upgrade mxnet pr cluster separately …
=> Upgrade mxnet pr cluster

eks_infrastructure/build_param.json, test/dlc_tests/eks/eks_manifest_templates/kubeflow/install_kubeflow.sh
**Note**: 
Upgrading KF manifest for pytorch and  tensorflow.
* When …
=> Upgrade manifest for pytorch and tensorflow

eks_infrastructure/build_param.json
**Note**: 
Create new EKS mxnet clusters and install new KF manifests. …
=> Create new EKS mxnet clusters

available_images.md
**Note**: 
Update HF TF version to 2.11.1 
=> Bump HF TF version to 2.11.1 in available images

.release_images_template.yml, release_images_training.yml
=> build: add release specs for PT2.0 tr

dlc_developer_config.toml, test/dlc_tests/conftest.py, test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py, test/test_utils/ec2.py
**Note**: 
1. add more verbose logs to ec2 test execution to help identify the test and image uri causing the hang
2. improve logger.info
**Additionally, please run the …
=> Add logs to ec2 test execution

release_images_inference.yml
**Note**: 
Executing patch release on x96_64 GPU  for issue found in TorchVision regarding fastrcnn model
PR quick check tests on initial commit.
=> [pytorch] PT 2.0 GPU patch release

available_images.md
=> [Doc] | [Triton] | Upgrade doc to mention Triton v23.02 and v23.03

release_images_inference.yml
**Note**: 
Add TFS 2.9.1 Graviton to inference release images
PR Quick tests on initial commit
=> [tensorflow][release] TFS 2.9.1 Graviton patch-release

available_images.md
=> doc: update the image list for PT2.0 training

dlc_developer_config.toml, test/test_utils/__init__.py
**Note**: 
Fix parse_canary method for TF2.12 images to use `py310` instead of `py39`
* …
=> [Tensorflow][Test] Fix parse_canary method for TF2.12 images

available_images.md, release_images_training.yml
=> Add Pytorch Training with Neuron SDK 2.9.1 to available images

release_images_inference.yml
**Note**: 
- Add DJL 0.22.1 neuronx sdk 2.9.0
- Run quick checks yaml test
=> Add DJL neuron release yaml config

src/requirements.txt, test/requirements.txt, test/sagemaker_tests/autogluon/inference/requirements.txt, test/sagemaker_tests/autogluon/training/requirements.txt, test/sagemaker_tests/huggingface/inference/requirements.txt, test/sagemaker_tests/huggingface_pytorch/training/requirements.txt, test/sagemaker_tests/huggingface_tensorflow/training/requirements.txt, test/sagemaker_tests/mxnet/inference/requirements.txt, test/sagemaker_tests/mxnet/training/requirements.txt, test/sagemaker_tests/pytorch/inference/requirements.txt, test/sagemaker_tests/pytorch/training/requirements.txt, test/sagemaker_tests/tensorflow/inference/requirements.txt, test/sagemaker_tests/tensorflow/tensorflow1_training/requirements.txt, test/sagemaker_tests/tensorflow/tensorflow2_training/requirements.txt
**Note**: 
Bug in invoke https://github.com/pyinvoke/invoke/issues/935 that will be fixed in fabric 3.1 release, until then, we need to down pin it. 
fabric issue https://github.com/fabric/fabric/issues/2263
**NOTE: If you are creating a PR for a new framework version, please ensure success of the standard, rc, and efa sagemaker remote tests by updating …
=> pin invoke version

release_images_inference.yml
=> Add NeuronX TF 2.10.1 release with SDK 2.9.0

release_images_inference.yml
**Note**: 
- Add DJL 0.22.1 fastertransformer release and 0.21.0
=> Add DJL FasterTransformer release definitions

release_images_inference.yml
**Note**: 
- Add release definitions for DJL cpu full
=> Add DJL cpu full release definitions

release_images_training.yml
**Note**: 
Release HF Training trn1 PT Neuronx images
* When …
=> Release HF Training trn1 PT Neuronx images

release_images_inference.yml
=> [NEURON][TF][PT] Add NeuronX SDK 2.10.0 inference images to release

available_images.md
**Note**: 
This changes the "Instance" column name for Neuron Containers to "Supported EC2 Instance Types" and adds this column to
the Huggingface Neuron inference container table. …
=> [MISC] Change wording for Neuron supported instance type column

release_images_inference.yml
**Note**: 
Release Huggingface Pytorch Neuronx Inference (trn1/inf2) images
* When …
=> Release Huggingface Pytorch Neuronx Inference (trn1/inf2) images

available_images.md, release_images_training.yml
=> Add latest PT NeuronX Training image to available_images.md

dlc_developer_config.toml, test/sagemaker_tests/huggingface_tensorflow/training/integration/conftest.py, test/sagemaker_tests/pytorch/training/conftest.py, test/sagemaker_tests/tensorflow/tensorflow2_training/integration/conftest.py
**Note**: 
Bug fixes (as detailed in code-review-comments below) on PT, TF, and HF-TF SM tests. …
=> [test] Fix SM Local test parametrization

dlc_developer_config.toml, pytorch/training/docker/2.0/py3/Dockerfile.cpu, pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu
=> PyTorch(Studio) - Add ipykernel to dockerfiles

available_images.md
**Note**: 
Add HF Inference NeuronX containers to available images
* …
=> Add HF Inference NeuronX containers to available images

release_images_inference.yml
**Note**: 
Releasing PyTorch 1.12.1 Inference image. Updated the release schema.
N/A
* …
=> Release pytorch 1.12.1 inference images

release_images_inference.yml
**Note**: 
Patch Relese PT 2.0 graviton
PR Quick checks on initial commit
=> [pytorch][release] patch release PT2.0 graviton

release_images_training.yml
**Note**: 
Re-Release PyTorch 2.0 SM
=> [PyTorch][Training] Re-Release PT2.0 Training SM

test/sagemaker_tests/pytorch/training/requirements.txt
**Note**: 
Pin SM version for PT training release
=> [PyTorch][Training] Pin SM Test for PT training

release_images_inference.yml
**Note**: 
Tensorflow ec2 image release
By …
=> Tensorflow ec2 image release

release_images_inference.yml
=> [PT][NEURON][RELEASE] Add Neuron PT inference image for SDK 2.10.0 to release

release_images_inference.yml
=> [TF][NEURON][RELEASE] Add Neuron TF2.10.1 inference image for SDK2.10.0

available_images.md, release_images_inference.yml
=> [PT][NEURON][INFERENCE][DOC] Add Pytorch 1.13.1 Neuron SDK 2.10.0 image to available_images.md

release_images_inference.yml
**Note**: 
- Add DJL definitions to release images yml
=> Add DJL 0.22.1 Neuron SDK 2.10.0 release definitions

release_images_inference.yml
**Note**: 
TF 2.12.1 Sagemaker Release
By …
=> TF 2.12.1 Sagemaker Release

test/sagemaker_tests/tensorflow/inference/requirements.txt
=> [Test][Tensorflow] Pin SM version for SM tests

available_images.md
**Note**: 
Update TF2.12 SM images in available images
* When …
=> Update TF2.12 SM images in available images

dlc_developer_config.toml, huggingface/pytorch/inference/buildspec.yml, huggingface/pytorch/training/buildspec-1-13.yml
=> [HuggingFace] Update Transformers version to 4.28.1 for PyTorch 1.13 Training and Inference DLCs

release_images_training.yml
**Note**: 
Add Hugging Face PT 2.0 Training DLC with Transformers 4.28.1 to release_images_training.yml …
=> [release] Add HF Training PT 2.0 transformers 4.28.1 to release images

release_images_inference.yml
**Note**: 
Patch Release of PT 2.0.0 with TS 0.8.0
PR Quick Checks on initial commit.
=> [pytorch][release] Patch release PT 2.0 with TS 0.8.0

release_images_inference.yml
**Note**: 
- Add release definitions for HF PT 2.0 images
- Run automated quick checks test (every commit)
=> Release HF PT 2.0 inference images

test/sagemaker_tests/huggingface/inference/conftest.py
**Note**: 
- SM regional tests fail because they rely on this option - updating this to remediate regional test failure
=> Update SM tests for HF to support py310

release_images_inference.yml
**Note**: 
- Release HF PT 2.0 TGI containers
- Run quick checks tests on each commit
=> Release HF TGI containers

release_images_inference.yml
=> Add NeuronX Pytorch inference image update to release_images_inference

available_images.md
=> Add Huggingface TGI 0.6.0 to available images

test/dlc_tests/sanity/quick_checks/test_buildspecs.py, test/dlc_tests/sanity/quick_checks/test_yml_config.py
**Note**: 
Prevent infinite loop when finding repo path in quick checks tests `test_release_images_inference_yml` and `test_release_images_training_yml`
Tested locally and on CI
**NOTE: If you are creating a PR for a new framework version, please ensure success of the standard, rc, and efa sagemaker remote tests by updating the dlc_developer_config.toml …
=> [test] Prevent infinite loop when finding repo path

release_images_inference.yml
**Note**: 
Update release images yaml to release PT 2.0.1 Inference x86/Graviton
Quick PR tests on initial commit.
=> [pytorch][release] release PT 2.0.1 Inference x86/graviton

release_images_inference.yml
**Note**: 
- Add HF PT TGI 0.8.2 release definition
- quick checks sanity test (every commit)
=> Add HF PT TGI 0.8.2 release definition

.github/CODEOWNERS, available_images.md
**Note**: 
- Update available images with HF PT 2.0 TGI 0.8.2
- Add dlc-lmi-reviewers to codeowners to allow them to update available images md file
=> Update HF TGI DLC version

release_images_inference.yml
Add V4.5 DeepSpeed 0.9.2 upgrade on this container
=> [DLC] Add LMI V4.5: DeepSpeed container update

release_images_inference.yml
Patch image for djl-serving FasterTransformers.
=> [djlserving] patch fastertransformers 0.22.1 image

release_images_inference.yml
**Note**: 
- Release PT 1.13 images
- quick checks, each commit
=> Release PT 1.13 EC2 and SM

available_images.md, dlc_developer_config.toml, test/sagemaker_tests/__init__.py, test/sagemaker_tests/autogluon/inference/conftest.py, test/sagemaker_tests/autogluon/training/conftest.py, test/sagemaker_tests/huggingface/inference/conftest.py, test/sagemaker_tests/huggingface_pytorch/training/conftest.py, test/sagemaker_tests/huggingface_tensorflow/training/integration/__init__.py, test/sagemaker_tests/mxnet/inference/integration/__init__.py, test/sagemaker_tests/mxnet/training/integration/__init__.py, test/sagemaker_tests/pytorch/inference/conftest.py, test/sagemaker_tests/pytorch/training/conftest.py, test/sagemaker_tests/pytorch/training/utils/image_utils.py, test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/conftest.py, test/sagemaker_tests/tensorflow/tensorflow1_training/integration/__init__.py, test/sagemaker_tests/tensorflow/tensorflow2_training/integration/__init__.py, test/test_utils/__init__.py, test/test_utils/imageutils.py
**Note**: 
Add il-central-1 to "NO_P*_REGION` lists in all sagemaker test configs.
=> [test][sagemaker] Add instance exception for il-central-1

dlc_developer_config.toml, test/sagemaker_tests/pytorch/inference/integration/sagemaker/test_mnist.py, test/sagemaker_tests/pytorch/inference/integration/sagemaker/test_mnist_inductor.py
=> [PyTorch][Inference] Add wait to check CloudWatch logs

available_images.md
=> [Update Available Images] PT2.0.1

release_images_inference.yml
=> [Release][Inference] PyTorch 2.0.1

release_images_inference.yml
CVE patching for djl-serving lmi containers
=> [djl-serving] cve patching lmi containers

autogluon/build_artifacts/inference/config.properties, autogluon/build_artifacts/inference/torchserve-entrypoint.py, autogluon/inference/buildspec.yml, autogluon/inference/docker/0.7/py3/Dockerfile.cpu, autogluon/inference/docker/0.7/py3/cu117/Dockerfile.gpu, test/dlc_tests/sanity/test_dlc_labels.py
=> [autogluon][build] AutoGluon 0.7.0 inference containers v2 - change to torch-serve

release_images_inference.yml
CVE patch for CPU DJL 0.21.0 LMI container
=> [djl-serving] cve patch on 0.21.0 cpu lmi container

dlc_developer_config.toml, test/dlc_tests/sanity/test_pre_release.py
**Note**: 
Regex solution for getting truncated image tag.
* When …
=> [Test] Regex solution for getting image tag

autogluon/inference/docker/0.7/py3/Dockerfile.cpu, autogluon/inference/docker/0.7/py3/cu117/Dockerfile.gpu, dlc_developer_config.toml
=> [autogluon][build] AutoGluon 0.7.0 inference containers v2 - fixes

release_images_inference.yml
**Note**: 
release autogluon v0.7 inference DLC …
=> release autogluon v0.7 inference DLC

release_images_inference.yml
=> [djl] Update djl deepspeed images for cve patches

release_images_inference.yml
=> [djl] Update djl cpu images for cves

release_images_inference.yml
=> [djl] Update djl neuronx images for cves

release_images_inference.yml
=> [djl] Update djl fastertransformer containers for cves

release_images_inference.yml, test/test_utils/__init__.py
=> [HuggingFace] Release HF PT1.13

test/sagemaker_tests/huggingface/inference/requirements.txt
=> [Huggingface][Release] Update Sagemaker Version for HF Release

test/sagemaker_tests/huggingface/inference/requirements.txt
=> Update sagemaker version for HF Release

pytorch/inference/buildspec-1-13.yml, pytorch/inference/buildspec-eia.yml, pytorch/inference/buildspec-graviton.yml, pytorch/inference/buildspec.yml
=> remove SM_TOOLKIT_VERSION arg from ec2 image build.

release_images_inference.yml, release_images_training.yml
=> [RELEASE] Release Pytorch Neuron(x) images

release_images_inference.yml
=> [RELEASE] Add Neuron(x) Tensorflow images for release and split Pytorch devices

release_images_inference.yml
Release for DJL 0.23.0 DeepSpeed 0.9.5 cu118 container
=> [djl-serving] Release DJL 0.23.0 DeepSpeed 0.9.5 container

release_images_inference.yml
=> [djl-serving] Release DJL 0.23.0 FasterTransformers container

release_images_training.yml
**Note**: 
TF 2.13 DLC Release
Quick PR checks on initial commit
=> [Tensorflow][Training][Release] TF 2.13 Training Release

release_images_inference.yml, release_images_training.yml
=> [AutoGluon] Release 0.8.2

available_images.md
=> [djl-serving] Deprecate DJL Serving 0.20.0 image

available_images.md, release_images_inference.yml, release_images_training.yml
=> [AutoGluon]0.8.2 post release

available_images.md
SageMaker Triton v23.05 container is not generally available across all supported regions, updating the documentaion t
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, …
=> [Documentation] | [Triton] Update documentation for Triton v23.05 release

autogluon/inference/docker/0.7/py3/Dockerfile.cpu, autogluon/inference/docker/0.7/py3/cu117/Dockerfile.gpu, autogluon/training/docker/0.7/py3/Dockerfile.cpu, autogluon/training/docker/0.7/py3/cu117/Dockerfile.gpu, dlc_developer_config.toml
=> [AutoGluon] 0.7.0 image patching

release_images_inference.yml, release_images_training.yml
=> [AutoGluon] 0.7 patch release

release_images_inference.yml, release_images_training.yml
=> [PYTORCH][NEURON][RELEASE] Add Pytorch SDK 212 images to release_images.yml

eks_infrastructure/build_param.json
**Note**: 
setting operation to patch EKS cluster
Quick PR check on initial commit.
=> [eks] eks-patching

dlc_developer_config.toml, huggingface/tensorflow/inference/docker/2.11/py3/Dockerfile.cpu, huggingface/tensorflow/inference/docker/2.11/py3/cu112/Dockerfile.gpu, huggingface/tensorflow/inference/docker/2.11/py3/cu112/Dockerfile.gpu.os_scan_allowlist.json
**Note**: 
Updating MMS and sagemaker-huggingface-inference-toolkit to latest versions
On Commit [6d93b28](https://github.com/aws/deep-learning-containers/pull/3212/commits/6d93b2833708ed1e3517698e149d082bf4b435b2)
* Sanity tests
* SM local tests
* SM remote tests
=> [huggingface][tensorflow][inference] patch update for HF TFS 2.11

eks_infrastructure/build_param.json
=> update eks cluster name

release_images_inference.yml
**Note**: 
* Patch release for HuggingFace TFS 2.11
* New release of TFS 2.13 EC2
Quick PR checks on initial commit.
=> [release] patch release HF TFS 2.11 and TFS 2.13 EC2 release

release_images_inference.yml
=> [djl-serving] Release DJL 0.23.0 DeepSpeed 0.9.5 patch

release_images_inference.yml
**Note**: 
Noticed `customer_type` variable missing for release. adding for release
PR quick checks on initial commit.
=> [release][tensorflow][inference] Release Attempt Two

release_images_inference.yml
=> [djl-serving] Release patch for TNX DLC 0.23.0 DJL

available_images.md
**Note**: 
Update Available images with TFS 2.13.0 
PR Quick checks on initial commit
=> [post release][tensorflow][inference] Update Available images

release_images_inference.yml
=> [hf-tgi] Release TGI 0.9.3

available_images.md
=> [djl-serving] Update available images for TNX 0.23.0 and TGI 0.9.3

dlc_developer_config.toml, tensorflow/inference/buildspec.yml, tensorflow/inference/docker/2.13/py3/Dockerfile.cpu, tensorflow/inference/docker/2.13/py3/cu118/Dockerfile.gpu
**Note**: 
TFS SM currency
On Commit: [f16f91f](https://github.com/aws/deep-learning-containers/pull/3233/commits/f16f91f623710bde9eb7313867e70ffae8982797)
* Sanity Tests
* EC2 Tests
* ECS Tests
* EKS Tests
* SM Local Tests
* SM Remote Tests
=> [tensorflow][inference][sagemaker] TFS 2.13 SM currency

release_images_inference.yml
=> [djl-serving] Patch djl-cpu-full 0.23.0

available_images.md
**Note**: 
Update Available Images to Include TF 2.13 SM Training DLC
PR Quick Checks on initial commit
=> [tensorflow][post-release] Update Available images for TF 2.13 SM Training

release_images_inference.yml
=> [djl-serving] CVE patch DJL-CPU-full 22.1 and 21

release_images_inference.yml
=> [djl-serving] CVE patch DJL-NueronX 0.22.1

release_images_inference.yml
=> [djl-serving] CVE patch DJL-DeepSpeed 0.23.0/0.22.1/0.21.0

release_images_inference.yml
**Note**: 
- Release PT 2.0.1 images with sagemaker pt inference toolkit 2.0.16
=> Re-release PT 2.0.1 inference images

dlc_developer_config.toml, tensorflow/inference/buildspec-2-12-graviton.yml, tensorflow/inference/docker/2.13/py3/Dockerfile.graviton.cpu, test/sagemaker_tests/tensorflow/inference/test/integration/sagemaker/test_tfs.py
**Note**: 
Adding TFS 2.13 for Graviton
Commit: [b0e431e](https://github.com/aws/deep-learning-containers/pull/3256/commits/b0e431eca183950033586aa390cd5d756833cabb)
* Sanity Tests
* EC2 Tests
* ECS Tests
* EKS Tests
* SM Local Tests
* SM Remote Tests
Commit: [2e981dd](https://github.com/aws/deep-learning-containers/pull/3256/commits/2e981ddf8f9401f22f478e6b79c6a07603c7d775)
* SM RC Tests
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, …
=> [tensorflow][inference][graviton] Add Graviton TFS 2.13

available_images.md
**Note**: 
Update Available images with new TFS 2.13 Graviton EC2 and SM Docker images
PR Quick tests on initial commit
=> [tensorflow][inference][graviton] Update available images

.release_templates/stabilityai_release_images.yml, release_images_inference.yml
**Note**: 
- Add SAI PT 2.0.1 SGM 0.1.0 inference images to release yaml
- Create a template file for future reference
- Running tests from quick_checks CI
=> Add stabilityai_pytorch release image definition

available_images.md
**Note**: 
- Add stabilityai images to available images markdown
=> Update available images markdown file with SAI release

available_images.md
=> [Documentation] | [Triton] | Update Triton documentation with v23.06

pytorch/training/buildspec.yml
**Note**: 
Turning off the EC2 image builds for the SM pytorch2.0.1 release due to issues with the build and test pipeline.
**Additionally, please run the sagemaker local …
=> Turning off the EC2 image builds for the SM pytorch2.0.1 release

available_images.md
=> fix il-central-1 account number

release_images_training.yml
=> Updating release images file for PyTorch 2.0.1

available_images.md
=> Updating available images for PyTorch SM DLC 2.0.1

release_images_training.yml
=> [Release] EC2 PT2.0.1 CUDA121 Supporting P5 EC2 instance

available_images.md
=> [Available Images] P5 EC2 image PT2.0.1 CUDA12.1

release_images_inference.yml
=> Add Neuron 2.13.2 Tensorflow images to release_images

release_images_inference.yml
**Note**: 
Related PRs:
x86: https://github.com/aws/deep-learning-containers/pull/3304
graviton: https://github.com/aws/deep-learning-containers/pull/3316
=> [PyTorch] [SM, EC2] Add release image definitions for PT 2.0.1 inference torchserve upgrade

release_images_inference.yml
**Note**: 
- [X ] I have run builds/tests on commit <INSERT COMMIT ID> for my changes.
* …
=> Release TGI 1.0.3

dlc_developer_config.toml, pytorch/inference/buildspec-1-13-neuron.yml, pytorch/inference/buildspec-1-13-neuronx.yml, pytorch/inference/buildspec-neuron.yml, pytorch/inference/buildspec-neuronx.yml, pytorch/inference/docker/1.13/py3/sdk2.13.2/Dockerfile.neuron, pytorch/inference/docker/1.13/py3/sdk2.13.2/Dockerfile.neuron.os_scan_allowlist.json, pytorch/inference/docker/1.13/py3/sdk2.13.2/Dockerfile.neuronx, pytorch/inference/docker/1.13/py3/sdk2.13.2/Dockerfile.neuronx.os_scan_allowlist.json, pytorch/training/buildspec-1-13-neuronx.yml, pytorch/training/buildspec-neuronx.yml, pytorch/training/docker/1.13/py3/sdk2.13.2/Dockerfile.neuronx, pytorch/training/docker/1.13/py3/sdk2.13.2/Dockerfile.neuronx.os_scan_allowlist.json, test/dlc_tests/sanity/test_pre_release.py, test/test_utils/__init__.py
=> [BUILD][NEURON][NEURONX][PYTORCH] Add Pytorch inf/training images for release 2.13.2

release_images_inference.yml, release_images_training.yml
=> Add Neuron 2.13.2 Pytorch images to release_images

release_images_inference.yml
=> Update release_images_inference.yml with pytorch neuron 2.13.2

release_images_inference.yml
**Note**: 
Remove Neuron TF Images to Fix Release Pipeline
=> [Tensorflow][Neuron] Remove TF2.10.1 Neuron Images from Release Images

release_images_training.yml
=> [Release PT2.0 CUDA121] EC2 GPU training

available_images.md
=> [PT20 CUDA121] Update available image

available_images.md
=> [Documentation] |[Triton] | Update available images with Triton v23.07 release

pytorch/training/buildspec.yml
**Note**: 
Building EC2 and SM DLC together timeouts on P4d test CodeBuild, so releasing 1 by 1 …
=> [PT2.0 CUDA118] Just build ec2 images

pytorch/training/buildspec.yml
=> [PT2.0 CUDA118] Build SM DLC

release_images_training.yml
=> [Release] PT2.0 CUDA118 EC2 and SM

dlc_developer_config.toml, stabilityai/pytorch/inference/docker/2.0/py3/cu118/Dockerfile.gpu
**Note**: 
- Update libwebp6 in SAI images
=> Upgrade libwebp6 in SAI images

release_images_training.yml
**Note**: 
- release images with TE v0.12
=> Release PT 2.0 CU121 images

dlc_developer_config.toml, test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py, test/dlc_tests/ec2/test_efa.py, test/test_utils/ec2.py
**Note**: 
PT 2.0.1 testing to rectify failures on pipeline
* When …
=> [PyTorch][Test] PT 2.0.1 Cu118 testing fast follow

release_images_training.yml
**Note**: 
PT2.0.1 Cu11.8 GPU SM Training release …
=> [Pytorch][Release] PT2.0.1 Cu11.8 GPU SM Training release

dlc_developer_config.toml, pytorch/inference/buildspec-1-13-neuron.yml, pytorch/inference/buildspec-1-13-neuronx.yml, pytorch/inference/buildspec-neuron.yml, pytorch/inference/buildspec-neuronx.yml, pytorch/inference/docker/1.13/py3/sdk2.14.1/Dockerfile.neuron, pytorch/inference/docker/1.13/py3/sdk2.14.1/Dockerfile.neuron.os_scan_allowlist.json, pytorch/inference/docker/1.13/py3/sdk2.14.1/Dockerfile.neuronx, pytorch/inference/docker/1.13/py3/sdk2.14.1/Dockerfile.neuronx.os_scan_allowlist.json, pytorch/training/buildspec-1-13-neuronx.yml, pytorch/training/buildspec-neuronx.yml, pytorch/training/docker/1.13/py3/sdk2.14.1/Dockerfile.neuronx, pytorch/training/docker/1.13/py3/sdk2.14.1/Dockerfile.neuronx.os_scan_allowlist.json
=> [BUILD][PYTORCH][NEURON][NEURONX] Add Pytorch Neuron(x) 2.14.1 images

dlc_developer_config.toml, tensorflow/inference/buildspec-2-10-neuron.yml, tensorflow/inference/buildspec-2-10-neuronx.yml, tensorflow/inference/buildspec-neuron.yml, tensorflow/inference/buildspec-neuronx.yml, tensorflow/inference/docker/1.15/py3/sdk2.8.0/Dockerfile.neuron, tensorflow/inference/docker/1.15/py3/sdk2.8.0/Dockerfile.neuron.os_scan_allowlist.json, tensorflow/inference/docker/2.10/py3/sdk2.14.1/Dockerfile.neuron, tensorflow/inference/docker/2.10/py3/sdk2.14.1/Dockerfile.neuron.os_scan_allowlist.json, tensorflow/inference/docker/2.10/py3/sdk2.14.1/Dockerfile.neuronx, tensorflow/inference/docker/2.10/py3/sdk2.14.1/Dockerfile.neuronx.os_scan_allowlist.json
=> [BUILD][TENSORFLOW][NEURON][NEURONX] Add Tensorflow Neuron(x) 2.14.1 images

dlc_developer_config.toml, pytorch/inference/docker/1.13/py3/sdk2.14.1/Dockerfile.neuron
=> [BUILD][PYTORCH][NEURON][INFERENCE] Add numpy to explicit install for PT Neuron 2.14.1 inference image

release_images_inference.yml
=> Add Tensorflow Neuron 2.14.1 inference images to release

release_images_inference.yml
=> release TGI v1.1.0

release_images_inference.yml, release_images_training.yml
=> Add PT Neuron(x) 2.14.1 to release_images

available_images.md, release_images_inference.yml, release_images_training.yml
=> Remove Neuron released images from ymls and update available_images

pytorch/training/buildspec.yml
=> build EC2 GPU cu118 PT 2.0 training images

dlc_developer_config.toml, test/dlc_tests/sanity/test_health_check.py
**Note**: 
Skip test_healthcheck_local_efa for inference images
on commit: [1e5bbeb](https://github.com/aws/deep-learning-containers/pull/3375/commits/1e5bbeb704e87850c6385279cf659b7dac4736c5)
* Sanity Tests
* EC2 tests
* ECS Tests
* EKS Tests
* SM Local Tests
* SM Remote tests
=> [pytorch] patch run for PT 2.0.1 Inference

release_images_inference.yml
**Note**: 
Update release_images_inference.yml to patch release PT 2.0.1 Inference for x86 and graviton.
PR Checks on initial commit.
=> [pytorch][release] PT 2.0.1 INF patch release

release_images_inference.yml
=> [djl-serving] Release DJL 0.24.0 neuronx container

release_images_inference.yml
=> Release Pytorch Neuron 2.14.1 inference

eks_infrastructure/build_param.json
**Note**: 
Delete MAINLINE and PR EKS Clusters
=> [MXNET][EKS] Remove MXNet EKS Clusters

release_images_training.yml
**Note**: 
- Address issue with canary tagging due to v2 release
=> Re-release cu118 ec2 images

release_images_training.yml
**Note**: 
Empty release images training yml file
=> Empty release images yml file

pytorch/inference/docker/2.1/py3/Dockerfile.cpu, pytorch/inference/docker/2.1/py3/Dockerfile.graviton.cpu, pytorch/inference/docker/2.1/py3/cu118/Dockerfile.gpu, test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference.py
**Note**: 
- Fix license file path from 2.0 to 2.1
- Re-enable torchdata tests because they created the v0.7.0 release tag
=> [PyTorch][Inference] Minor fixes for PT 2.1 inference

release_images_inference.yml
=> [PyTorch][Inference][x86_64][EC2,SM] PT 2.1 Release Images

release_images_inference.yml
=> [djl-serving] Release DJL 0.24.0 deepspeed container

release_images_inference.yml
=> [djl-serving] Release DJL 0.24.0 fastettransformer container

release_images_inference.yml
=> [djl-serving] Release DJL 0.24.0 CPU container

available_images.md
Adds 0.24.0 and deprecates 0.21.0
**Note**:  …
=> [djl-serving] Update available images for DJL 0.24.0

available_images.md
**Note**: 
- Update `available_images.md` file for PT2.1 EC2 Currency release
=> [PyTorch][Inference][Training][EC2] update available_images.md

release_images_inference.yml
=> [djl-serving] Patch 0.24.0 neuronx container

pytorch/inference/docker/2.1/py3/Dockerfile.cpu, pytorch/inference/docker/2.1/py3/Dockerfile.graviton.cpu, pytorch/inference/docker/2.1/py3/cu118/Dockerfile.gpu
=> [PyTorch][Inference] fix urllib3 version pin

release_images_inference.yml
=> [PyTorch][Inference][Graviton] release graviton PT 2.1

available_images.md
=> [TGI] Update available images for TGI 1.1.0

available_images.md
=> Add PT2.1 graviton to available images + minor fixes

release_images_training.yml
**Note**: 
Add PT 2.0 SM Training DLCs to release_images_training.yml
=> [release] Add PT 2.0.1 SM Training to release_images

available_images.md
**Note**: 
- Simple doc upgrade for Triton 
-  …
=> Update docs to reflect Triton v23.08

.github/CODEOWNERS
**Note**: 
- allow owning team to directly review huggingface and stabilityai container changes
=> Update codeowners for SAI and HF

release_images_training.yml
=> Release SDK 2.15.0 NeuronX Pytorch training image

test/dlc_tests/ec2/test_efa.py
**Note**: 
Skipping EFA healthcheck for PT2.1 SM DLC
=> [PyTorch][Sagemaker][Training] skip efa healthcheck for pt2.1

release_images_inference.yml
=> Release HF PT neuronx 1.13.1

release_images_training.yml
=> Release SM DLC PT2.0.1 CUDA121

release_images_inference.yml
**Note**: 
Patch for the djl-serving 0.24.0-pytorch-inf2 image.
* …
=> [djl-serving] patch for djl-pytorch-inf2

release_images_inference.yml
=> Add Pytorch Neuron(X) SDK 2.15.0 images to release

pytorch/training/buildspec-2-0-sm.yml
**Note**: 
- Resetting the buildspec to default images
=> Reset PT2 SM Training Buildspec to build default images

available_images.md
=> update HF PT neuronx training/inference image doc

eks_infrastructure/build_param.json, test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference.py
**Note**: 
- Upgrade nodegroups on PT and TF
=> Update EKS nodegroups for PT and TF

release_images_inference.yml
**Note**: 
- Add PT 2.0.1 inference images
- Remove older images from yaml file
=> Add PT 2.0.1 to inference release yml

test/test_utils/__init__.py
=> remove habana dependency from test initialization

release_images_training.yml
=> release TF2.12 and TF2.13 SM images

release_buildspec.yml
**Note**: 
Install `src/requirements` in release buildspec as it eventually uses the `src` packages. …
=> Release buildspec install requirements

release_images_inference.yml
=> Add Tensorflow SDK 2.15.1 images to release_images

release_images_inference.yml
**Note**: 
Need to update release yaml for `huggingface-tensorflow-inference`
Already ran in previous PR, this is just to release those images to prod: https://github.com/aws/deep-learning-containers/pull/3517
=> fix: Adding HF TF release images

test/dlc_tests/conftest.py
=> Updating availability zones to reflect capacity changes

test/test_utils/__init__.py
=> Fix to test configuration to allow for searching for deprecated AMI's.

test/sagemaker_tests/pytorch/training/conftest.py
=> Adding list to track regional availability of p5 instances.

dlc_developer_config.toml, test/sagemaker_tests/pytorch/training/conftest.py, test/sagemaker_tests/pytorch/training/integration/sagemaker/test_distributed_operations.py, test/sagemaker_tests/pytorch/training/integration/sagemaker/test_smdataparallel.py
=> Fix broken tests

dlc_developer_config.toml, src/requirements.txt, test/requirements.txt
**Note**: 
Current builds fail due to the older `boto3` version, giving error:
```
ImportError: cannot import name 'is_s3express_bucket' from 'botocore.utils' 
```
Using later boto3 version helps fix the issue.
**NOTE: If you are creating a PR for a new framework version, please ensure success of the standard, rc, and efa sagemaker remote tests by …
=> [Build][Test] Check build issues

dlc_developer_config.toml, pytorch/training/docker/2.1/py3/cu121/Dockerfile.gpu, test/sagemaker_tests/pytorch/training/integration/local/test_smppy_local.py, test/sagemaker_tests/pytorch/training/integration/sagemaker/test_smppy.py
=> profiler for  pt2.1

release_images_inference.yml
**Note**: 
Patching the deepspeed images from djl for 0.25.0, 0.24.0, and 0.23.0
* When …
=> [djl-serving] Patch 0.25.0-0.23.0 LMI DLC images

available_images.md
**Note**: 
Updating to remove table that may potentially mislead at the request of Tony.
* …
=> TGI Available Images Update

.github/CODEOWNERS, release_images_inference.yml
First release of SM Triton v23.10 CPU and GPU containers using the DLC system
**Note**: 
* When …
=> Add release config for Triton v23.10

release_images_inference.yml
**Note**: 
Patch 0.23, 0.24, and 0.25 TransformersNeuronx containers for CVEs
* When …
=> [djl-serving] patch djl 0.23, 0.24, and 0.25 TNX containers

release_images_inference.yml
**Note**: 
Patch 0.24 FasterTransformer container …
=> [djl-serving] patch djl 0.24 FasterTransformer containers

release_images_inference.yml
**Note**: 
Fix neuronx-cc version to pinned to solve backwards compatibility issue for compiled models …
=> [djl-serving] patch djl 0.24 TNX containers

dlc_developer_config.toml, release_images_training.yml
**Note**: 
Release TensorFlow 2.12 and 2.13 Sagemaker Images
=> Re-Release TF2.12 & TF2.13 Sagemaker Images 

.github/CODEOWNERS
**Note**: 
From codeowners docs - https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
```
```
Modifying codeowners file to remove conflict of 1p algos/conda
=> 1P Code Owner Change

release_images_training.yml
=> Release PT 1.13 training sagemaker

release_images_training.yml
=> remove gpu from release config

dlc_developer_config.toml, release_images_inference.yml, stabilityai/pytorch/inference/buildspec.yml, stabilityai/pytorch/inference/docker/2.0/py3/cu118/Dockerfile.sagemaker.gpu, test/sagemaker_tests/pytorch/inference/integration/local/test_serving.py, test/sagemaker_tests/pytorch/inference/requirements.txt, test/test_utils/__init__.py
**Note**: 
Fixing build failures that resulted from https://github.com/aws/deep-learning-containers/pull/3284.
Addressing vulnerabilities of SAI inference image. …
=> SAI Vulnerability Fixes

release_images_training.yml
=> Patch huggingface pytorch training 2.0

available_images.md
=> Update doc for Triton

data/ignore_ids_safety_scan.json, huggingface/pytorch/inference/docker/2.0/py3/cu118/Dockerfile.gpu.os_scan_allowlist.json, release_images_inference.yml
=> Release HF PT 2.0 images

test/sagemaker_tests/huggingface/inference/integration/local/test_serving.py, test/sagemaker_tests/huggingface/inference/requirements.txt
=> Fix broken inference test

release_images_inference.yml
=> Fix release_images_inference.yml

release_images_inference.yml
=> Release Triton v23.12

available_images.md
=> Update Triton v23.12

release_images_inference.yml
=> [djl-serving] patch djl 0.24, 0.25 and release 0.26 TNX containers

release_images_inference.yml, release_images_training.yml
=> Fix release_images ymls

release_images_inference.yml
=> [djl-serving] 0.26.0 deepspeed image

release_images_inference.yml
=> [djl-serving] correct the typo for python

release_images_inference.yml
=> [djl-serving] 0.26.0 trt llm release

release_images_inference.yml
=> [djl-serving] 0.26.0 cpu image release

available_images.md
=> [doc][djl-serving] update doc with 0.26.0 release images

release_images_inference.yml
=> [djl-serving] patch 0.24 fastertransformer containers

release_images_inference.yml
=> [djl-serving] patch 0.24, 0.25, 0.26 deepspeed dlc images

available_images.md
=> TGI NeuronX Available Image

dlc_developer_config.toml, src/utils.py
**Note**: 
Pin safety to < 3 to prevent any breakages. 
* When …
=> [Build] Pin safety version

release_images_inference.yml
=> [djl-serving] patch 0.24 and 0.25 cpu images

release_images_inference.yml
=> [djl-serving] patch 0.24 and 0.25 neuronx containers

release_images_inference.yml
**Note**: 
Release TF 2.12.1 Inference Images …
=> Release TF 2.12.1 Inference Images

test/sagemaker_tests/huggingface/inference/conftest.py
=> Add G5 filter list for HF inference tests

dlc_developer_config.toml, src/autopr_caller.py, src/image_transfer.py
**Note**: 
Add Exception to Image Transfer and base_repo to PR caller for AutoPatching
* …
=> Add Exception to Image Transfer and base_repo to PR caller for AutoPatching

.github/CODEOWNERS, data/ignore_ids_safety_scan.json, huggingface/pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu.os_scan_allowlist.json
=> Temp ignore new vulnerabilities to release HF PT 2.0 images

huggingface/pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu, huggingface/pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu.os_scan_allowlist.json
=> Update HF PT training ignore and dockerfile

huggingface/pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu
=> Update awscli for HF PT training

test/test_utils/sagemaker.py
=> Update test instances for HF PT Training

huggingface/pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu.os_scan_allowlist.json
=> Add temp ignore for HF PT training 2.0

release_images_inference.yml
**Note**: 
Release PyTorch Images
By …
=> Release PyTorch Images

release_images_inference.yml
=> [djl-serving] patch 0.26.0 deepspeed dlc

release_images_inference.yml
=> [djl-serving] 0.26 trtllm dlc patch release

release_images_inference.yml
=> [djl-serving] 0.26.0 tnx dlc patch release

release_images_inference.yml
=> [djl-serving] 0.26.0 cpu dlc patch release

huggingface/pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu.os_scan_allowlist.json
=> ignore another pillow high vuln

huggingface/pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu.os_scan_allowlist.json
=> Yet another pillow high vuln

dlc_developer_config.toml, huggingface/pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu, huggingface/pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu.os_scan_allowlist.json
=> fix pyarrow critical vuln

testspec.yml
=> enable test notification system

release_images_inference.yml
=> Update Triton v24.01

autogluon/inference/docker/1.0/py3/Dockerfile.cpu.os_scan_allowlist.json, autogluon/inference/docker/1.0/py3/cu118/Dockerfile.gpu.os_scan_allowlist.json, autogluon/training/docker/1.0/py3/Dockerfile.cpu.os_scan_allowlist.json, autogluon/training/docker/1.0/py3/cu118/Dockerfile.gpu.os_scan_allowlist.json, dlc_developer_config.toml
**Note**: 
- [ x] `sagemaker_remote_tests = true`
- [ x] `sagemaker_local_tests = true`
* …
=> [AutoGluon-1.0] Address new Linux risks detected

test/dlc_tests/conftest.py
=> Allowed availability zones to include us-east-1d

release_images_training.yml
=> [AutoGluon] Fix typo in training release images

test/sagemaker_tests/autogluon/inference/conftest.py, test/sagemaker_tests/autogluon/training/conftest.py
=> [AutoGluon] Added python 3.10 support in test

available_images.md, release_images_inference.yml, release_images_training.yml
**Note**: 
- [] I have run builds/tests on commit <INSERT COMMIT ID> for my changes.
* …
=> [AutoGluon] Post AutoGluon 1.0.0 Release Clean Up

dlc_developer_config.toml, tensorflow/inference/docker/2.14/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json, tensorflow/inference/docker/2.14/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json, tensorflow/inference/docker/2.14/py3/cu118/Dockerfile.ec2.gpu.os_scan_allowlist.json, tensorflow/inference/docker/2.14/py3/cu118/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
**Note**: 
Fix enhanced scan test failures caused by scan allowlist not being up-to-date. …
=> [tensorflow] Add TF 2.14 inference enhanced scan allowlist

src/start_testbuilds.py
**Note**: 
Fix a bug in start_testbuilds.py that caused SM integ test jobs to always run on all PRs …
=> [test] Fix bug that caused SM CI test jobs to always run

test/dlc_tests/conftest.py
=> [test] Fix EC2 p3dn AZ selection

release_images_inference.yml
=> release pt2.2 inference ec2 dlc

pytorch/training/docker/2.2/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json, pytorch/training/docker/2.2/py3/cu121/Dockerfile.ec2.gpu.os_scan_allowlist.json
=> fix allowlist description for PT2.2.0 Training DLC EC2

tensorflow/inference/docker/2.14/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json, tensorflow/inference/docker/2.14/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json, tensorflow/inference/docker/2.14/py3/cu118/Dockerfile.ec2.gpu.os_scan_allowlist.json, tensorflow/inference/docker/2.14/py3/cu118/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
**Note**: 
Formatting change on the scan report is causing tests to fail.
* When creating …
=> [tensorflow] Fix TF 2.14 inference allowlist

tensorflow/inference/buildspec-2-13-ec2.yml, tensorflow/inference/buildspec-2-13-sm.yml, tensorflow/training/buildspec-2-13-ec2.yml, tensorflow/training/buildspec-2-13-sm.yml
**Note**: 
Create EC2 and SM specific buildspecs for TF 2.13
* When …
=> [tensorflow] Create EC2 and SM specific buildspecs for TF 2.13

release_images_inference.yml
=> release hf pt 1.13.1-transformer4.36.2-sdk2.16.1

release_images_inference.yml, release_images_training.yml
=> release pt 2.2 ec2 training  dlc

release_images_training.yml
**Note**: 
Add specs for TF 2.14 Training DLCs to release_images_training.yml
* When …
=> [release] Add TF 2.14.1 Training DLCs to release_images

release_images_inference.yml
=> Add TF Neuron(X) 2.17 release to release_images_inference.yml

release_images_inference.yml
**Note**: 
Add TF 2.14 inference DLC release configs to release_images_inference.yml
* …
=> [release] Add TF 2.14 configs to release_images_inference

pytorch/training/docker/2.1/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json
=> Updating CVE json

test/sagemaker_tests/pytorch/training/integration/sagemaker/test_smdataparallel.py
=> Skip smddp/smdmp integration test

release_images_training.yml
=> Release PT2.2.0 SM Training DLC

available_images.md
=> Update PT 2.2.0 SM Training DLC available_images.md

test/sagemaker_tests/pytorch/training/integration/sagemaker/test_pytorchddp.py
=> Updating pytorchddp test

release_images_training.yml
**Note**: 
Patch PT 2.2 training EC2
<details>
</details> …
=> Re-release PT 2.2 ec2 images

release_images_training.yml
**Note**: 
Release PT2.0.1 Cu121 SM GPU images with SM Profiler
<details> …
=> Release PT2.0.1 Cu121 SM GPU images with SM Profiler

release_images_training.yml
**Note**: 
Release PT2.0.1 SM GPU Cu118 images
<details> …
=> Release PT2.0.1 SM GPU Cu118 images

release_images_training.yml
**Note**: 
<details>
</details>
<details> …
=> Set huggingface_pytorch disable_sm_tag to True for neuronx training

release_images_inference.yml
**Note**: 
Add configs for TF 2.14 graviton to release images inference
<details> …
=> [release] Add TF 2.14 graviton to release images inference

available_images.md
**Note**: 
Add TF 2.14 Graviton DLCs to available images
<details> …
=> [doc] Add TF 2.14 Graviton DLCs to available images

release_images_inference.yml
**Note**: 
<details>
</details>
<details> …
=> [djl-serving] 0.27.0 deepspeed image

release_images_training.yml
**Note**: 
Re-release TF2.14 Images
=> [TensorFlow] Re-Release TF2.14 EC2+SM Training Images

release_images_inference.yml
**Note**: 
<details>
</details>
<details> …
=> [djl-serving] 0.27.0 trtllm dlc force release

release_images_inference.yml
**Note**: 
<details>
</details>
<details> …
=> [djl-serving] 0.27.0 deepspeed patch image

release_images_inference.yml
**Note**: 
<details>
</details>
<details> …
=> Release PT 2.2.1 graviton images

release_images_inference.yml
**Note**: 
<details>
</details>
<details> …
=> [djl-serving] 0.27.0 trtllm dlc patch release

available_images.md
**Note**: 
<details>
</details>
<details> …
=> Add PT 2.2.1 Graviton images to available_images.md

release_images_inference.yml
**Note**: 
Trigger release for 2.18.1
<details>
</details> …
=> [djl-serving] add 0.27.0 neuron 2.18.1 container

release_images_inference.yml
**Note**: 
<details>
</details>
<details> …
=> [djl-serving] 0.27.0 cpu dlc release

release_images_inference.yml
**Note**: 
<details>
</details>
<details> …
=> [djl-serving] 0.27.0 cpu dlc release update to py38

huggingface/pytorch/training/docker/1.13/py3/sdk2.15.0/Dockerfile.neuronx
**Note**: 
<details>
</details>
<details> …
=> patching hf pt training neuronx for cve

release_images_inference.yml
**Note**: 
<details>
</details>
<details> …
=> Release PyTorch 2.1 Graviton Autopatch

release_images_inference.yml
**Note**: 
Patch for 0.27.0 Neuron LMI 2.18.1 SDK image.
<details> …
=> [djl] patch Neuron LMI 2.18.1

release_images_inference.yml
**Note**: 
<details>
</details>
<details> …
=> patch trt-llm 0.26.0

dlc_developer_config.toml, pytorch/inference/buildspec.yml, test/dlc_tests/benchmark/ec2/pytorch/inference/test_performance_pytorch_inference.py, test/dlc_tests/benchmark/ec2/pytorch/training/test_performance_pytorch_training.py, test/dlc_tests/benchmark/ec2/tensorflow/inference/test_performance_tensorflow_inference.py, test/dlc_tests/container_tests/bin/benchmark/tf1_serving_perf.py, test/dlc_tests/container_tests/bin/benchmark/tf2_serving_perf.py, test/dlc_tests/ec2/mxnet/inference/test_mxnet_inference.py, test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference.py, test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference_inductor.py, test/dlc_tests/ec2/pytorch/training/common_cases.py, test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py, test/dlc_tests/ec2/smclarify_cases.py, test/dlc_tests/ec2/tensorflow/inference/test_tensorflow_inference.py, test/dlc_tests/ec2/tensorflow/training/test_tensorflow_training.py, test/dlc_tests/ec2/test_efa.py, test/dlc_tests/ec2/test_smclarify.py, test/dlc_tests/ec2/test_smdebug.py, test/dlc_tests/sanity/test_health_check.py, test/dlc_tests/sanity/test_telemetry.py, test/test_utils/__init__.py, test/test_utils/ec2.py
**Note**: 
- [1ed7122](https://github.com/aws/deep-learning-containers/pull/3881/commits/1ed7122fbbdc3a0e3d2dd60bdd339051f6e8bc3a) Passing all tests (ec2, ecs, eks, sanity, benchmark, sm remote, sm local, sm rc, sm benchmark, sm efa)
- PT 2.2 Inference EC2
- PT 2.2 Inference SM
- PT 2.2 Training SM
- TF 2.14 Inference SM
- TF 2.14 Training SM
- [e84eeda](https://github.com/aws/deep-learning-containers/pull/3881/commits/e84eeda45d78fd6fa58fb99fdffbcc4ed1342197) Passing all tests (ec2, ecs, eks, sanity, benchmark, sm remote, sm local, …
=> Fix `nvidia-docker` run to use `--runtime=nvidia --gpus all`.

release_images_inference.yml, release_images_training.yml
**Note**: 
Add TF2.13 images to release yml
<details>
</details> …
=> Add TF2.13 images to release yml

dlc_developer_config.toml, tensorflow/inference/buildspec-graviton.yml, tensorflow/inference/docker/2.14/py3/Dockerfile.ec2.graviton.cpu.core_packages.json, tensorflow/inference/docker/2.14/py3/Dockerfile.ec2.graviton.cpu.py_scan_allowlist.json, tensorflow/inference/docker/2.14/py3/Dockerfile.sagemaker.graviton.cpu.core_packages.json, tensorflow/inference/docker/2.14/py3/Dockerfile.sagemaker.graviton.cpu.py_scan_allowlist.json
**Note**: 
<details>
</details>
<details> …
=> Onboard TF 2.14 Graviton image to Autopatch

release_images_inference.yml
**Note**: 
Patch release for 0.27.0 deepspeed container for djl-serving
<details> …
=> [djl-serving] 0.27.0 deepspeed patch release

release_images_inference.yml
Release Pytorch 2.1.2 NeuronX Huggingface inference image.
**Note**: 
<details> …
=> release HF Pytorch2.1.2 NeuronX

release_images_inference.yml
**Note**: 
Patch release for the 0.27.0 LMI cpu container
<details> …
=> [djl-serving] 0.27.0 cpu patch release

release_images_inference.yml, release_images_patches.yml, release_images_training.yml, test/dlc_tests/sanity/quick_checks/test_yml_config.py
**Note**: 
- Add new release yaml file for patches. Do not allow force release for this file. If force release is needed, move the spec back over to its corresponding training or inference file.
- This file is meant to be touched very infrequently - only for additions or out of support removals
- Test that quick checks test does not allow force release ([cba4458](https://github.com/aws/deep-learning-containers/pull/3915/commits/cba4458e9803fd57a9e76da3d5e570a9aa95748c))
**NOTE: By default, docker builds are disabled. In order to …
=> Add patch release yaml file

release_images_training.yml
**Note**: 
<details>
</details>
<details> …
=> Revert: force release HF Pytorch training image

data/ecr_scan_vulnerabilities.json, dlc_developer_config.toml
**Note**: 
- Update file to patch uncategorized vulns
- run build and sanity test in [7de6d1a](https://github.com/aws/deep-learning-containers/pull/3943/commits/7de6d1ad6f14972fafda48f2e5a5917bcb9ff6f2) …
=> Patch uncategorized packages

release_images_inference.yml
**Note**: 
Patch for trtllm 0.27.0 LMI container
<details> …
=> [djl-serving] 0.27.0 trtllm patch release

data/ecr_scan_vulnerabilities.json
**Note**: 
Add Urllib3 for upstream handling to ecr data
Checked that JSON file is valid. Will run on the pipelines to see the impact.
<details> …
=> Add Urllib3 for upstream handling to ecr data

.github/PULL_REQUEST_TEMPLATE.md
**Note**: 
Move "-c" option to the end to fix functionality
<details>
`python src/prepare_dlc_dev_environment.py -bc </path/to/buildspec.yml> -p origin`
- Enable specific tests for a buildspec or set of buildspecs - also commits and pushes changes to …
=> Update pull request documentation to separate commit/push options

release_images_patches.yml
=> Add PT 2.3 Graviton to release_images_patches

available_images.md, release_images_inference.yml, release_images_training.yml
We support AutoGluon v1.1.1, but cannot support v1.1 actively anymore.
**Note**: 
<details>
- Enable specific tests for a buildspec or set of buildspecs - also commits and …
=> [AutoGluon]Update Notes for v1.1.1

available_images.md
=> Add PT 2.3 Graviton to available_images

tensorflow/inference/docker/2.16/py3/Dockerfile.ec2.graviton.cpu.os_scan_allowlist.json, tensorflow/inference/docker/2.16/py3/Dockerfile.sagemaker.graviton.cpu.os_scan_allowlist.json
=> [Graviton][TF] Fix os scan allowlist

tensorflow/inference/docker/2.16/py3/Dockerfile.ec2.graviton.cpu.os_scan_allowlist.json, tensorflow/inference/docker/2.16/py3/Dockerfile.sagemaker.graviton.cpu.os_scan_allowlist.json
=> [Graviton][TF][Inf] fix os allowlist

test/dlc_tests/ec2/test_gdrcopy.py
**Note**: 
Clean up unused imports
<details>
`python …
=> Clean up unused imports in gdrcopy test

available_images.md
=> update available images tf 216 inf

huggingface/pytorch/inference/docker/1.13/py3/Dockerfile.cpu, huggingface/pytorch/inference/docker/1.13/py3/cu117/Dockerfile.gpu, huggingface/pytorch/inference/docker/1.13/py3/sdk2.16.1/Dockerfile.neuronx, huggingface/pytorch/training/docker/1.13/py3/cu117/Dockerfile.gpu, huggingface/pytorch/training/docker/2.1/py3/cu121/Dockerfile.gpu
=> chore: empty commit to trigger build to upgrade git

available_images.md
=> Remove TF 2.13 from available_images

release_images_inference.yml
=> [djl-serving] 0.29.0 lmi release

release_images_inference.yml
Release Triton v24.05
<details>
`python src/prepare_dlc_dev_environment.py -b </path/to/buildspec.yml> -t …
=> Release Triton v24.05

dlc_developer_config.toml, huggingface/pytorch/inference/docker/2.1/py3/Dockerfile.cpu, huggingface/pytorch/inference/docker/2.1/py3/Dockerfile.cpu.os_scan_allowlist.json
=> Patch 2024 07 24

autogluon/inference/docker/1.1/py3/Dockerfile.cpu.os_scan_allowlist.json, autogluon/inference/docker/1.1/py3/Dockerfile.cpu.py_scan_allowlist.json, autogluon/inference/docker/1.1/py3/cu121/Dockerfile.gpu.os_scan_allowlist.json, autogluon/inference/docker/1.1/py3/cu121/Dockerfile.gpu.py_scan_allowlist.json, autogluon/training/docker/1.1/py3/Dockerfile.cpu.os_scan_allowlist.json, autogluon/training/docker/1.1/py3/Dockerfile.cpu.py_scan_allowlist.json, autogluon/training/docker/1.1/py3/cu121/Dockerfile.gpu.os_scan_allowlist.json, autogluon/training/docker/1.1/py3/cu121/Dockerfile.gpu.py_scan_allowlist.json, dlc_developer_config.toml
https://github.com/autogluon/autogluon/issues/4330
**Note**: 
This PR is to re-build AutoGluon 1.1.1 training images (CPU) to resolve `mpi4py` error which breaks AG TS and AG Multimodal.
<details>
Assuming your remote is called `origin` (you can find out more with `git remote …
=> Patch AutoGluon 1.1.1 Training Images

dlc_developer_config.toml, huggingface/pytorch/training/docker/2.1/py3/cu121/Dockerfile.gpu, huggingface/pytorch/training/docker/2.1/py3/cu121/Dockerfile.gpu.os_scan_allowlist.json, huggingface/pytorch/training/docker/2.1/py3/cu121/Dockerfile.gpu.py_scan_allowlist.json
**Note**: 
* Upgrade Setuptools
* Ignore Torch, Transformer and Linux vulnerabilities.
* Pinning Ninja in order to pass `pip check`
<details>
- Run default builds and tests for a …
=> 2024 07 31 hf pt train

release_images_inference.yml
**Note**: 
Release DJL 0.29.0 - LMI NeuronX
<details>
`python …
=> [djl-serving] 0.29.0 tnx release

release_images_inference.yml
=> [0.29.0] djl cpu release

release_images_inference.yml
=> [djl-serving] 0.29.0 tensorrt llm release

release_images_inference.yml
=> [djl-serving] 0.29.0 tensorrt llm patch release

dlc_developer_config.toml, tensorflow/training/docker/2.16/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json, tensorflow/training/docker/2.16/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json, tensorflow/training/docker/2.16/py3/cu123/Dockerfile.ec2.gpu.os_scan_allowlist.json, tensorflow/training/docker/2.16/py3/cu123/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
**Note**: 
TF2.16 handling pipeline tests
[a0e3956](https://github.com/aws/deep-learning-containers/pull/4132/commits/a0e39563bafd84609d57b41863971c7d378a55fa)
<details>
- Run default …
=> [Build][Test] TF2.16 handling pipeline tests

pytorch/training/docker/2.1/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json, pytorch/training/docker/2.1/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json, pytorch/training/docker/2.1/py3/cu121/Dockerfile.ec2.gpu.os_scan_allowlist.json, pytorch/training/docker/2.1/py3/cu121/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
=> Fix PT 2.1 Training Vulnerbilities

dlc_developer_config.toml, pytorch/training/docker/2.1/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json, pytorch/training/docker/2.1/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json, pytorch/training/docker/2.1/py3/cu121/Dockerfile.ec2.gpu.os_scan_allowlist.json, pytorch/training/docker/2.1/py3/cu121/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
**Note**: 
- [4813204](https://github.com/aws/deep-learning-containers/pull/4142/commits/481320415b19f110cb98f4776b620dcacebab200) EC2 DLC passed sanity test
- [e5f2c70](https://github.com/aws/deep-learning-containers/pull/4142/commits/e5f2c7027f7fb620b4b3fd9b3df394a00653c1cb) SM DLC passed santy test
<details>
<summary>Confused on how to run tests? Try …
=> Fix PT 2.1 Duplicate CVE

dlc_developer_config.toml, tensorflow/training/docker/2.16/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json, tensorflow/training/docker/2.16/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json, tensorflow/training/docker/2.16/py3/cu123/Dockerfile.ec2.gpu.os_scan_allowlist.json, tensorflow/training/docker/2.16/py3/cu123/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
**Note**: 
TF2.16 image handling tests for pipelines
[55a56d9](https://github.com/aws/deep-learning-containers/pull/4144/commits/55a56d9bc2a209efa10fae72f2ab4af1d23345fc)
<details>
- Run …
=> TF2.16 image handling sanity tests for pipelines

release_images_patches.yml
**Note**: 
Release TF2.16 Training SM/EC2 images
<details>
`python …
=> Release TF2.16 Training SM/EC2 images

data/ignore_ids_safety_scan.json, huggingface/pytorch/inference/docker/1.13/py3/sdk2.16.1/Dockerfile.neuronx.os_scan_allowlist.json, huggingface/pytorch/inference/docker/1.13/py3/sdk2.16.1/Dockerfile.neuronx.py_scan_allowlist.json
**Note**: 
- Allowlisting unaddressed HIGH vulnerabilities to unblock deployment
<details>
- Run default builds and tests for a particular buildspec - also commits and pushes changes to …
=> fix: allowlist HIGH vulnerabilities to fix HF PT inference neuronx buildRC pipeline

available_images.md
**Note**: 
Add TF2.16.2 training images to available images
<details> …
=> Add TF2.16.2 training images to available images

release_images_inference.yml
=> [djl-serving] 0.29.0 lmi patch release

release_images_inference.yml
=> [djl-serving] 0.29.0 tnx patch release

release_images_inference.yml
=> [djl-serving] 0.28.0 tensorrt llm patch release

release_images_inference.yml
=> [djl-serving] 0.28.0 lmi patch release

release_images_inference.yml
=> [djl-serving] 0.28.0 tnx patch release

release_images_inference.yml
**Note**: 
Patch vLLM bug for llama3.1 405B fp8 in lmi gpu containers
<details> …
=> [djl-serving] 0.29.0 lmi patch

huggingface/pytorch/inference/docker/1.13/py3/sdk2.16.1/Dockerfile.neuronx.os_scan_allowlist.json
**Note**: 
Temporarily ignoring CVE-2024-42154 since no upstream patch available to unblock the pipeline
<details>
- Run default builds and tests for a particular buildspec - also commits …
=> Ignore CVE-2024-42154 to unblock the pipeline

release_images_inference.yml, release_images_training.yml
**Note**: 
Add release config for the two PRs merged:
[[HuggingFace][Neuronx] Inference - Optimum Neuron 0.0.24 - Neuron sdk 2.19.1 - Transformers to 4.41.1](https://github.com/aws/deep-learning-containers/pull/4150)
[[Huggingface][Neuronx] Training - update for Optimum-Neuron 0.0.24 - Neuron sdk 2.19.1 - Transformers to 4.41.1](https://github.com/aws/deep-learning-containers/pull/4149)
**NOTE: By default, docker builds are disabled. In order to build your container, please update dlc_developer_config.toml and specify the framework …
=> chore: add release config for new HF Neuronx images

dlc_developer_config.toml, huggingface/pytorch/inference/docker/1.13/py3/sdk2.16.1/Dockerfile.neuronx.os_scan_allowlist.json
=> Ignore CVE-2024-39495 to unblock pipeline

huggingface/pytorch/training/docker/2.1/py3/sdk2.19.1/Dockerfile.neuronx.os_scan_allowlist.json
**Note**: 
Add a newly found vulnerability from test run https://us-west-2.console.aws.amazon.com/codesuite/codepipeline/pipelines/BuildRCPipeline-huggingface-pytorch-training-latest-neuronx/view?region=us-west-2
<details>
Assuming your remote is called `origin` (you can find …
=> chore: ignore safety scan from a non-critical vulnerability

huggingface/pytorch/inference/docker/2.1/py3/sdk2.19.1/Dockerfile.neuronx.os_scan_allowlist.json
=> chore: update safety scan ignore list for HF inference neuronx

dlc_developer_config.toml, test/test_utils/__init__.py
**Note**: 
- Use pip list instead of pkg_resources to get the package json output
- Simplifies execution by running one shell command in container
- pkg resources working set flags vendor packages that are not importable and is also deprecated https://setuptools.pypa.io/en/latest/pkg_resources.html
Purpose: unblock sanity tests across images that have upgraded setuptools
- Test PT 2.3 inf sm ([c696f7c](https://github.com/aws/deep-learning-containers/pull/4179/commits/c696f7c10ed15e397d02b2c7e31fc8eb51b8e5aa))
**NOTE: By default, …
=>  Use pip list instead of pkg_resources to get package json output 

data/common-ecr-scan-allowlist.json
**Note**: 
Disputed CVE on pip for all versions - https://nvd.nist.gov/vuln/detail/CVE-2018-20225
Allowlisting to unblock builds
=> Add pip disputed vulnerability to common allowlist

test/test_utils/security.py
**Note**: 
Handle diff in filepath for ECR Scans
<details>
`python …
=> [Test] Handle diff in filepath for ECR Scans

eks_infrastructure/build_param.json
**Note**: 
- Modify build params to create mainline
=> Update build params on EKS infra

eks_infrastructure/build_param.json
**Note**: 
- Deploy necessary graviton infra
=> Setup Graviton EKS infrastructure

huggingface/pytorch/inference/docker/1.13/py3/sdk2.16.1/Dockerfile.neuronx.os_scan_allowlist.json
**Note**: 
add CVE-2024-36978 and CVE-2024-39487 to os_scan_allowlist.json
<details> …
=> chore: add CVE-2024-36978 and CVE-2024-39487 to os_scan_allowlist.json

release_images_inference.yml
=> [djl-serving] 0.28.0 tensorrt-llm patch

dlc_developer_config.toml, huggingface/pytorch/inference/docker/1.13/py3/sdk2.16.1/Dockerfile.neuronx.os_scan_allowlist.json
=> Patch 2024 08 28

test/dlc_tests/sanity/test_canary_integration.py
**Note**: 
Update pull test to remove image after pull for DCs
=> Remove image after pull test to avoid resource constraints

dlc_developer_config.toml, src/patch_helper.py
=> Increase Autopatch Size check from 0.5MB to 0.7MB

test/sagemaker_tests/pytorch/training/resources/gpt2/requirements.txt
This reverts commit bed46e8e3e8608aa5a44245775544f44e2781e8f.
**Note**: 
- Revert transformers bump due to PT 1.13 SMDMP requires transformer 4.21.0 for GPT2 tests.
<details>
- Run default …
=> Revert "Bump transformers (#3817)"

test/dlc_tests/sanity/test_canary_integration.py
**Note**: 
- pull test only runs in PR and doesn't have functional benefit - removing tests to avoid confusion
=> Remove canary pullable tests

huggingface/pytorch/inference/docker/2.1/py3/sdk2.19.1/Dockerfile.neuronx, huggingface/pytorch/inference/docker/2.1/py3/sdk2.19.1/Dockerfile.neuronx.os_scan_allowlist.json
=> chore: patch libgssapi-krb5-2 CVE-2024-37371 for HF neuronx training image

release_images_patches.yml
=> Remove TF 2.14 EC2 Training from Autorelease

huggingface/pytorch/training/docker/2.1/py3/sdk2.19.1/Dockerfile.neuronx, huggingface/pytorch/training/docker/2.1/py3/sdk2.19.1/Dockerfile.neuronx.os_scan_allowlist.json
=> chore: patch neuronx training image CVE-2024-37371

huggingface/pytorch/inference/docker/1.13/py3/Dockerfile.cpu, huggingface/pytorch/inference/docker/1.13/py3/Dockerfile.cpu.os_scan_allowlist.json, huggingface/pytorch/inference/docker/1.13/py3/cu117/Dockerfile.gpu, huggingface/pytorch/inference/docker/2.1/py3/Dockerfile.cpu, huggingface/pytorch/inference/docker/2.1/py3/Dockerfile.cpu.os_scan_allowlist.json, huggingface/pytorch/inference/docker/2.1/py3/Dockerfile.gpu.os_scan_allowlist.json, huggingface/pytorch/inference/docker/2.1/py3/cu118/Dockerfile.gpu, huggingface/pytorch/training/docker/2.1/py3/cu121/Dockerfile.gpu, huggingface/pytorch/training/docker/2.1/py3/cu121/Dockerfile.gpu.os_scan_allowlist.json, huggingface/pytorch/training/docker/2.1/py3/sdk2.19.1/Dockerfile.neuronx.os_scan_allowlist.json
**Note**: 
Adding a lot of the vulnerabilities to ignore list as they are not showing up in JumpStart 1P's scan results. Also patch the affected images.
<details>
- Run default builds and …
=> chore: patch multiple HF-pytorch CVEs

release_images_patches.yml
**Note**: 
Release PT113 Inf SM Images
<details>
`python …
=> Release PT113 Inf SM Images

pytorch/inference/docker/2.4/py3/Dockerfile.ec2.graviton.cpu.os_scan_allowlist.json, pytorch/inference/docker/2.4/py3/Dockerfile.sagemaker.graviton.cpu.os_scan_allowlist.json, pytorch/inference/docker/2.4/py3/cu124/Dockerfile.ec2.graviton.gpu.os_scan_allowlist.json
=> [PyTorch][Inference][Graviton] Add linux vulns to allowlist

pytorch/inference/docker/2.4/py3/Dockerfile.ec2.graviton.cpu.os_scan_allowlist.json, pytorch/inference/docker/2.4/py3/Dockerfile.sagemaker.graviton.cpu.os_scan_allowlist.json, pytorch/inference/docker/2.4/py3/cu124/Dockerfile.ec2.graviton.gpu.os_scan_allowlist.json
=> [PyTorch][Inference][Graviton] Remove trailing commas

dlc_developer_config.toml, test/test_utils/__init__.py
**Note**: 
Temporary commit for canary test failures
[0588bfa](https://github.com/aws/deep-learning-containers/pull/4251/commits/0588bfaaba6a288066f76c3a93813dc9df24c465)
<details>
- Run …
=> [Test] Troubleshoot canary test failures

pytorch/inference/docker/2.3/py3/cu121/Dockerfile.gpu, release_images_patches.yml, src/autopr_caller.py
**Note**: 
- Add back PT 2.1/2.2 graviton images
- Comment out SQS feature
- Remove extraneous code comment from PT 2.3 image
=> Cleanup: Add back images to patches, comment out autoPR queue calls

pytorch/inference/docker/2.4/py3/cu124/Dockerfile.graviton.gpu, release_images_patches.yml
**Note**: 
- Update license file for graviton GPU
- Add back images to release image patches
=> Update GPU graviton license file, add back PT 1.13/2.1/2.2 inf ec2

pytorch/training/docker/2.4/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json, pytorch/training/docker/2.4/py3/cu124/Dockerfile.ec2.gpu.os_scan_allowlist.json
=> fix PT 2.4 EC2 Training CVE

available_images.md
=> Update PT 2.4 Training Available Images

release_images_patches.yml
**Note**: 
- Add back PT 2.3 inference ec2, PT 2.3 inference graviton ec2, PT 2.3 inference graviton SM
- Add back TF 2.14 training ec2
- Add back TF 2.16 training ec2
=> Add more images back to release yaml file

release_images_inference.yml
=> Release PyTorch 2.4 Inf EC2 DLC

release_images_patches.yml
=> Add PT 2.4 Graviton EC2 CPU to release_images_patches

dlc_developer_config.toml, huggingface/pytorch/training/docker/1.13/py3/cu117/Dockerfile.gpu, huggingface/pytorch/training/docker/1.13/py3/cu117/Dockerfile.gpu.os_scan_allowlist.json
**Note**: 
Update expat to latest to patch critical vulnerability in image
<details> …
=>  Update expat for pytorch training 1.13 cu117 

release_images_inference.yml
=> [djl] cpu image patches for 0.26.0, 0.27.0, 0.28.0, 0.29.0

release_images_inference.yml
=> [djl] deepspeed image patches for 0.26.0, 0.27.0

release_images_inference.yml
=> [djl] lmi patches for 0.28.0, 0.29.0

release_images_inference.yml
=> [djl] neuronx patch releases for 0.26.0, 0.27.0, 0.28.0, 0.29.0

release_images_inference.yml
=> [djl] fix typo in numbering for neuron path 0.29.0

release_images_patches.yml
=> Add PyTorch 2.4 Inference on SageMaker to release.yml

available_images.md
=> Remove TF 2.14 from available_images

available_images.md
**Note**: 
- Add https://github.com/aws/deep-learning-containers/releases/tag/v1.0-pt-graviton-sagemaker-2.4.0-inf-cpu-py311
- Add https://github.com/aws/deep-learning-containers/releases/tag/v1.1-pt-graviton-ec2-2.4.0-inf-cpu-py311
- Add https://github.com/aws/deep-learning-containers/releases/tag/v1.0-pt-graviton-ec2-2.4.0-inf-gpu-py311
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, …
=> Update PT 2.4 graviton available images

pytorch/inference/docker/2.4/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json, pytorch/inference/docker/2.4/py3/cu124/Dockerfile.ec2.gpu.os_scan_allowlist.json, pytorch/training/docker/2.4/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json, pytorch/training/docker/2.4/py3/cu124/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
=> Fix PT 2.4 inf ec2 / tr sm allowlist

huggingface/pytorch/inference/docker/2.1/py3/sdk2.19.1/Dockerfile.neuronx
=> patch apparmor vulnerability

available_images.md
=> Add PT2.4 Inference on EC2 and SageMaker

dlc_developer_config.toml, pytorch/inference/buildspec-2-4-sm.yml, pytorch/inference/docker/2.4/py3/Dockerfile.sagemaker.cpu.core_packages.json, pytorch/inference/docker/2.4/py3/cu124/Dockerfile.ec2.gpu.core_packages.json, pytorch/inference/docker/2.4/py3/cu124/Dockerfile.sagemaker.gpu.core_packages.json
**Note**: 
[2e5081d](https://github.com/aws/deep-learning-containers/pull/4328/commits/2e5081d5aa3739125acd6e6db3b89657f0b80157)
- passed all ec2 and sm tests
<details>
- Run default …
=> Add Autopatch for PT2.4 SageMaker Inference

huggingface/pytorch/inference/docker/1.13/py3/Dockerfile.cpu, huggingface/pytorch/inference/docker/1.13/py3/cu117/Dockerfile.gpu
=> chore: fix vulns on hf pt inference 1.13

tensorflow/inference/docker/build_artifacts/sagemaker/serve.py
=> fix recursive error.

huggingface/pytorch/inference/docker/2.1/py3/sdk2.19.1/Dockerfile.neuronx
=> patch libarchive13 for HF PT Inference neuronx

release_images_patches.yml
**Note**: 
Unblock TF 2.16 release image patches
=> Re-enable TF 2.16 SM images

dlc_developer_config.toml, huggingface/pytorch/inference/docker/2.1/py3/sdk2.19.1/Dockerfile.neuronx
**Note**: 
fix: patch HF PT Inference neuronx latest
<details>
`python …
=> fix: patch HF PT Inference neuronx latest

release_images_inference.yml
=> [djl] patch release for tensorrtllm 0.28.0 container

pytorch/training/docker/2.0/py3/Dockerfile.cpu, pytorch/training/docker/2.0/py3/cu118/Dockerfile.gpu
**Note**: 
Cleanup - Remove references to sifting for out-of-support PT 2.0
=> Removing sifting references

release_images_inference.yml
**Note**: 
Add image release config for the new neuronx DLC 0.0.25.
<details> …
=> chore: add neuronx 0.0.25 release config

dlc_developer_config.toml, tensorflow/inference/buildspec-2-16-graviton.yml
**Note**: 
- Re-enable autopatch
=>  Re-enable TF 2.16 graviton autopatch 

dlc_developer_config.toml, tensorflow/inference/buildspec-2-16-sm.yml, tensorflow/inference/docker/build_artifacts/sagemaker/python_service.py, tensorflow/inference/docker/build_artifacts/sagemaker/serve.py
**Note**: 
- All tests (ec2, eks, ecs, sanity, sm local, sm remote) passed on [5fe5b85](https://github.com/aws/deep-learning-containers/pull/4397/commits/5fe5b8531d32f5da6b213a409b076bbe5698ef01)
<details>
Assuming your remote is called `origin` (you can find out more with …
=> [Tensorflow][Inference][Sagemaker] Move gevent monkey patching fix for recursion error

available_images.md
**Note**: 
Add ca-west-1 to available images
=> Add ca-west-1 to available image regions

dlc_developer_config.toml, tensorflow/inference/buildspec-2-16-sm.yml, tensorflow/inference/docker/build_artifacts/sagemaker/serve.py
**Note**: 
- All tests (ec2, eks, ecs, sanity, sm local, sm remote) passed on [45c0631](https://github.com/aws/deep-learning-containers/pull/4400/commits/45c06318914154cf9c5f744a52abe940610fe974)
<details>
Assuming your remote is called `origin` (you can find out more with …
=> Re-enable TF 2.16 inference SM autopatch

pytorch/inference/buildspec-2-4-ec2.yml, pytorch/inference/buildspec-graviton-2-4-ec2.yml
=> [PyTorch][Inference][EC2] Re-enable autopatch for PT 2.4 Inference EC2 images

release_images_patches.yml
=> [PyTorch][Inference][EC2][SAGEMAKER] Add images to release images yml

.github/CODEOWNERS
=> Update SMDDP codeowner team

release_images_training.yml
=> release: add huggingface training 2.3.0 release config

available_images.md
=> [PyTorch][Inference][SageMaker][EC2] Add images to available images.

release_images_inference.yml
=> [djl][trtllm] adding lmi-trt inference images for patch/release

pytorch/training/docker/2.5/py3/Dockerfile.cpu, pytorch/training/docker/2.5/py3/cu124/Dockerfile.gpu
=> update license file for PT 2.5

pytorch/inference/buildspec-arm64.yml, tensorflow/inference/buildspec-arm64.yml
=> [PyTorch][TensorFlow][Inference] Add dummy arm64 buildspec files

release_images_patches.yml
=> Add PT 2.5 Training EC2 to release.yml

release_images_inference.yml
=> [lmi] patch release for lmi 0.28.0-0.30.0, release for lmi 0.31.0

release_images_inference.yml
=> [djl-serving] release lmi 0.30.0 neuron dlc

available_images.md
=> Update available_images.md with PT 2.4 training DLC

dlc_developer_config.toml, pytorch/training/docker/2.4/py3/Dockerfile.cpu, pytorch/training/docker/2.4/py3/cu124/Dockerfile.gpu
**Note**: 
- Passed sanity and security tests [4ee9c54](https://github.com/aws/deep-learning-containers/pull/4432/commits/4ee9c54c08c0b1c82f99de579d08b80513f6d6b4)
<details>
- Run default …
=> Pin numpy<2 for PT 2.4 training SM

release_images_inference.yml
=> [djl-serving] 0.31.0 lmi image

release_images_inference.yml
=> [djl-serving] 0.31.0 lmi image release

release_images_inference.yml
=> [djl-serving] patch neuron 0.30.0 neuron dlc

release_images_inference.yml
=> [djl-serving] 0.31.0 lmi image patch release

release_images_patches.yml
=> [PyTorch][Inference] Add PT 2.5 ARM64 to release_images

test/test_utils/sagemaker.py
**Note**: 
- Update sm local test to g5
=> Update default SM local gpu instance type

release_images_training.yml
**Note**: 
update release config for new HF Neuronx images
<details>
`python …
=> chore: update release config for new HF Neuronx images

test/dlc_tests/conftest.py
=> Skip torchdata test for >PT 2.1.1 with cu118

available_images.md
**Note**: 
\+ formatting fix + minor improvements for consistency
=> Update available_images.md with PT 2.5 ARM64 DLCs and name change info

available_images.md, dlc_developer_config.toml, test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference.py
**Note**: 
- Added tests `test_ec2_pytorch_inference_graviton_gpu_deep_canary` and `test_ec2_pytorch_inference_arm64_gpu_deep_canary `
- Tests `test_ec2_pytorch_inference_arm64_cpu_deep_canary` and `test_ec2_pytorch_inference_arm64_gpu_deep_canary ` passed on [3feea56](https://github.com/aws/deep-learning-containers/pull/4455/commits/3feea566fe93bdf089cdbf1d8992e1784e5c868e) with `arm64_mode = true`, `deep_canary_mode = true`, and `build_frameworks = ["pytorch"]`.
- Tests with `graviton_mode = true` passed on …
=> [PyTorch][Inference][ARM64] Add GPU deep canary tests + minor fixes

release_images_inference.yml
=> [djl] patch update for 0.27.0 deepspeed container

dlc_developer_config.toml, huggingface/pytorch/inference/docker/2.1/py3/Dockerfile.cpu
=> Patch huggingface pytorch inference 2.1.0 linux-libc-dev

test/sagemaker_tests/huggingface/inference/conftest.py
=> add python 3.11 support to HF INF conftest file

dlc_developer_config.toml, huggingface/pytorch/training/docker/2.1/py3/sdk2.19.1/Dockerfile.neuronx
=>  Patch libgstreamer1.0-0 and libgstreamer-plugins-base1.0-0 CVEs 

release_images_inference.yml
=> [djl] patch releases for djl-lmi container v28-v31

dlc_developer_config.toml, test/dlc_tests/sanity/quick_checks/test_dlc_developer_config.py
**Note**: 
- Remove mxnet builds from dev config
=> Remove mxnet builds from dev config

pytorch/training/buildspec-arm64.yml
=> add dummy buildspec for PT arm64 training

release_images_inference.yml
=> [djl] neuronx patch releases for 0.28.0, 0.29.0,0.30.0

release_images_inference.yml
=> [djl] cpu patches for 0.28.0 - 0.31.0

dlc_developer_config.toml, src/patch_helper.py
**Note**: 
- `dlc-pr-pytorch-inference` autopatch build succeeded on [6a64c58](https://github.com/aws/deep-learning-containers/pull/4491/commits/6a64c5891d78983bfd53dfdacaa2f006e963d29c)
- `dlc-pr-pytorch-arm64-inference` autopatch build succeeded on [17b2bd1](https://github.com/aws/deep-learning-containers/pull/4491/commits/17b2bd1772c68bf7357c4e6ae33137653fe3cae6)
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and …
=> Add a tag for the latest released image SHA for autopatch images

dlc_developer_config.toml, huggingface/pytorch/inference/docker/2.3/py3/Dockerfile.cpu
=> [huggingface_pytorch] [inference] [2.3] Update libmysofa1

release_images_inference.yml
=> [djl][tensorrt] patch releases for 0.29.0 and 0.31.0

release_images_patches.yml
=> Comment out arm64/graviton entries from release_images_patches

release_images_patches.yml
=> Add x86 TFS 2.18 inference images to release

release_images_patches.yml
=> Add tf2.18 training images to release

available_images.md
=> Add tf2.18 to available images

release_images_inference.yml
=> [djl][lmi] patch release of 0.29.0

available_images.md, release_images_patches.yml
**Note**: 
- Remove PT 2.2 from available images and yaml file
=> PT 2.2 end of support

release_images_patches.yml
=> Uncomment PT 2.3 graviton release

release_images_inference.yml
=> [lmi] add v14 container for lmi

release_images_inference.yml
=> [lmi][fix] fix python version for release pipeline

release_images_patches.yml
=> Restore the rest of graviton/arm64 pipelines

release_images_patches.yml, test/dlc_tests/sanity/test_ecr_scan.py
=> Add Tensorflow 2.18 Inference arm64 Image to Release

available_images.md
=> Add arm64 TF2.18 Inf to available images

dlc_developer_config.toml, pytorch/inference/buildspec-2-6-sm.yml, pytorch/inference/docker/2.6/py3/cu124/Dockerfile.gpu, pytorch/inference/docker/build_artifacts/start_cuda_compat.sh, pytorch/inference/docker/build_artifacts/torchserve-entrypoint.py
**Note**: 
- [cdd5371](https://github.com/aws/deep-learning-containers/pull/4563/commits/cdd5371e162f9b92cca9727653583b16fbcf01ce) Passed ec2, eks, ecs, security, sanity, sm remote, sm local tests.
<details>
Assuming your remote is called `origin` (you can find out more with …
=> Patch cuda compat mounting on PT 2.6 Inference SM

dlc_developer_config.toml, tensorflow/training/buildspec-2-18-sm.yml, tensorflow/training/docker/2.18/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json, tensorflow/training/docker/2.18/py3/cu125/Dockerfile.gpu, tensorflow/training/docker/2.18/py3/cu125/Dockerfile.sagemaker.gpu.os_scan_allowlist.json, tensorflow/training/docker/build_artifacts/dockerd-entrypoint.py, tensorflow/training/docker/build_artifacts/start_cuda_compat.sh
**Note**: 
- [94f5dd5](https://github.com/aws/deep-learning-containers/pull/4562/commits/94f5dd5804a7c0fce1c7ad539a785d95b6d18690) Passed ec2, eks, ecs, sanity, security, sm remote, sm local tests
- Allowlist needed changes due to node packages that comes with jupyter kernel but this is removed. No vulnerable node package exists but their metadata remains which triggered the enhance scan vulnerabilities.
**NOTE: By default, docker builds are disabled. In order to build your container, please update dlc_developer_config.toml and …
=> Patch cuda compat mounting on TF 2.18 Training SM

release_images_patches.yml
=> Release PyTorch 2.6 Inf SM DLC

test/sagemaker_tests/pytorch/inference/conftest.py, test/test_utils/__init__.py, test/test_utils/sagemaker.py
=> add Python 312 support

release_images_patches.yml
=> Add PT 2.6 ARM64 Inference to release

miscellaneous_dockerfiles/Dockerfile.autopatch, miscellaneous_scripts/dockerfile_patch_script.sh
=> fix start_host_with_right_name not found

tensorflow/inference/buildspec-2-16-sm.yml, tensorflow/inference/buildspec-2-18-sm.yml
=> Onboard TF 2.16/2.18 Infrence SM to autopatch

available_images.md
=> Add PT 2.6 ARM64 Inference to available_images

test/test_utils/__init__.py
=> Fix canary python version

available_images.md
=> Add PT2.6 Inf images to available images

eks_infrastructure/build_param.json
=> Create EKS Cluster v1.32 MAINLINE with gpu nodegroup g5 instance

release_images_inference.yml
=> updating disable_sm_tag for HF pytorch 2.3.0

release_images_inference.yml
=> [fix][djl] Add cuda_version to TRT-LLM patch release

release_images_patches.yml
=> Add PT2.6 Training to Release

test/test_utils/__init__.py
=> hotfix for canary failures

dlc_developer_config.toml, pytorch/inference/buildspec-arm64-2-6-ec2.yml, test/test_utils/__init__.py
**Note**: 
- All tests passed on [af7ee39](https://github.com/aws/deep-learning-containers/pull/4621/commits/af7ee3952bf79e3f84a719286fe10cc96b290b5c)
=> Onboard PT 2.6 ARM64 Inference EC2 to autopatch

test/sagemaker_tests/pytorch/training/conftest.py
=> Add py312 to sagemaker tests

available_images.md
=> Add PT2.6 Training to Available Images

dlc_developer_config.toml, test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference.py, test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py, test/dlc_tests/ec2/tensorflow/inference/test_tensorflow_inference.py, test/test_utils/__init__.py
**Note**: 
- [b70b07c](https://github.com/aws/deep-learning-containers/pull/4629/commits/b70b07cf7b1a611149708fb21ddbb96839fe7ebc) Passed deep canary tests for PT/TF inf/tr
<details>
- Run …
=> Replace single framework Neuron DLAMI with base Neuron DLAMI

dlc_developer_config.toml, test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference.py, test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py, test/dlc_tests/ec2/tensorflow/inference/test_tensorflow_inference.py, test/test_utils/__init__.py
**Note**: 
- [931e434](https://github.com/aws/deep-learning-containers/pull/4632/commits/931e434b794e5ca3b5d51fccaf39c27a410b7d70) Deep canary passed for TF/PT inf/tr
<details>
- Run …
=> Upgrade Neuron Base DLAMI from UL20 to UL22

dlc_developer_config.toml, huggingface/pytorch/training/docker/2.1/py3/sdk2.20.0/Dockerfile.neuronx
**Note**: 
chore: patch cves related to emacs, certifi, and and golang
- Integ + security tests run
<details>
- Run default builds and tests for a particular buildspec - also commits and …
=> chore: patch cves related to emacs, certifi, and and golang

release_images_inference.yml
=> [djl-serving] 0.32.0 lmi image patch release

release_images_inference.yml
=> [djl-serving] 0.32.0 lmi image patch release fix os version

release_images_inference.yml
=> [djl-serving] 0.32.0 lmi image patch release fix python version

pytorch/training/buildspec-2-5-sm.yml
=> Re-enable autopatch for 2.5 SM Training

pytorch/training/docker/2.3/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json, pytorch/training/docker/2.3/py3/cu121/Dockerfile.sagemaker.gpu.os_scan_allowlist.json, pytorch/training/docker/2.4/py3/cu124/Dockerfile.ec2.gpu.os_scan_allowlist.json, pytorch/training/docker/2.5/py3/cu124/Dockerfile.ec2.gpu.os_scan_allowlist.json, src/patch_helper.py
=> Fix critical CVE for go/lib

pytorch/training/docker/2.3/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json, pytorch/training/docker/2.3/py3/cu121/Dockerfile.ec2.gpu.os_scan_allowlist.json, pytorch/training/docker/2.5/py3/Dockerfile.sagemaker.cpu.core_packages.json, pytorch/training/docker/2.5/py3/cu124/Dockerfile.sagemaker.gpu.core_packages.json
=> Fix CVE for PT 2.3 training EC2 and PT 2.5 Training SM autopatch version specifier

pytorch/inference/docker/2.5/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json, pytorch/inference/docker/2.5/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json, pytorch/inference/docker/2.5/py3/cu124/Dockerfile.ec2.gpu.os_scan_allowlist.json, pytorch/inference/docker/2.5/py3/cu124/Dockerfile.sagemaker.gpu.os_scan_allowlist.json, pytorch/training/docker/2.5/py3/Dockerfile.sagemaker.cpu.core_packages.json, pytorch/training/docker/2.5/py3/cu124/Dockerfile.sagemaker.gpu.core_packages.json
=> Patch PT 2.5 DLC

pytorch/inference/docker/2.3/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json, pytorch/training/docker/2.3/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json, pytorch/training/docker/2.3/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json, pytorch/training/docker/2.4/py3/cu124/Dockerfile.ec2.gpu.os_scan_allowlist.json, pytorch/training/docker/2.4/py3/cu124/Dockerfile.sagemaker.gpu.os_scan_allowlist.json, pytorch/training/docker/2.5/py3/cu124/Dockerfile.ec2.gpu.os_scan_allowlist.json, pytorch/training/docker/2.5/py3/cu124/Dockerfile.sagemaker.gpu.os_scan_allowlist.json, pytorch/training/docker/2.6/py3/cu126/Dockerfile.ec2.gpu.os_scan_allowlist.json, pytorch/training/docker/2.6/py3/cu126/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
=> Patch CVE for go/stdlib, torch, cross-spawn and golang.org/x/crypto

release_images_inference.yml
=> patch release for lmi trt container

release_images_inference.yml
=> lmi v14 patch

dlc_developer_config.toml, huggingface/pytorch/training/docker/2.3/py3/cu121/Dockerfile.gpu
**Note**: 
* Pinning cmake to ensure build works.
<details>
`python …
=> Patching Huggingface Pytorch Training 2.3.0

dlc_developer_config.toml, huggingface/pytorch/training/docker/2.5/py3/cu124/Dockerfile.gpu
=> Huggingface pytorch training latest

release_images_inference.yml, test/sagemaker_tests/huggingface/inference/conftest.py
=> add cuda version for gpu

dlc_developer_config.toml, huggingface/pytorch/inference/docker/2.3/py3/Dockerfile.cpu, huggingface/pytorch/inference/docker/2.3/py3/cu121/Dockerfile.gpu, huggingface/pytorch/inference/docker/2.6/py3/Dockerfile.cpu, huggingface/pytorch/inference/docker/2.6/py3/cu124/Dockerfile.gpu
=> Patch 2025 04 02 hf pt inference

release_images_training.yml
=> chore: releasing huggingface pytorch training version

examples/dlc-llama-3-finetuning-and-hosting-with-agent/README.md
**Note**: 
Add Llama fine tuning and hosting using DLCs
<details>
`python …
=> Add Llama fine tuning and hosting using DLCs

release_images_inference.yml
=> [lmi] add release definition for lmi v15

release_images_inference.yml
https://t.corp.amazon.com/SMAlgo-11092
Setting force_release to True so that we can release 4 patches for the hf_pt_inference_neuronx image. It's currently under blocked days right now, preventing us from doing a release to resolve our CVE sev2 until tomorrow. Staged image that will be released [isenLink](https://tiny.amazon.com/27izi7n9/IsenLink) shows 0 vulnerabilities 
Verified here https://code.amazon.com/packages/DLContainersReleaseLogic/blobs/851198a8968036427c932b16ac35214aa305d4c6/--/scripts/publish_dlc_images#L161,L162 that this will force the release successfully.
Will fast follow to turn this off after this is successfully released
**NOTE: By default, docker builds are disabled. In order to build your container, please update dlc_developer_config.toml and specify the framework …
=> force_release hf pt inference neuronx

release_images_inference.yml
=> [lmi] patch release for djl-lmi 0.31.0

test/dlc_tests/ec2/test_transformerengine.py
=> Cleanup: remove TE skip test fixture

release_images_inference.yml
=> [lmi] fix python version in lmi 0.31.0 release definition

release_images_patches.yml
=> disable Graviton/ARM64 release

available_images.md
=> Deprecating PT 2.3

test/test_utils/ec2.py
=> Filter out G4 for EFA

test/dlc_tests/ec2/mxnet/inference/test_mxnet_inference.py, test/dlc_tests/sanity/test_pre_release.py, test/test_utils/__init__.py
=> Remove NEURON_UBUNTU_18_BASE_DLAMI_US_WEST_2

release_images_patches.yml
=> Enable one arm64 release pipeline to verify infra change

release_images_patches.yml
=> Enable arm64 release pipeline and remove PT2.3

pytorch/training/docker/2.5/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json, pytorch/training/docker/2.5/py3/cu124/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
=> Add libxml2 to allowlist which is already the latest version

data/common-ecr-scan-allowlist.json, pytorch/training/docker/2.5/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json, pytorch/training/docker/2.5/py3/cu124/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
=> Allowlist libxml2 as not remidation provided

autogluon/inference/docker/1.3/py3/Dockerfile.cpu.py_scan_allowlist.json, autogluon/inference/docker/1.3/py3/cu124/Dockerfile.gpu.py_scan_allowlist.json, autogluon/training/docker/1.3/py3/Dockerfile.cpu.py_scan_allowlist.json, autogluon/training/docker/1.3/py3/cu124/Dockerfile.gpu.py_scan_allowlist.json, dlc_developer_config.toml
=> [AutoGluon] Fix vulnerability for AutoGluon v1.3

release_images_inference.yml, release_images_training.yml
**Note**: 
Updating YAML files to release AutoGluon v1.3 image
<details> …
=> [AutoGluon] Release AutoGluon 1.3

test/dlc_tests/ec2/test_gdrcopy.py, test/test_utils/__init__.py
=> Skip gdrcopy tests for PT2.4-2.6 training

test/dlc_tests/ec2/pytorch/training/common_cases.py, test/dlc_tests/ec2/pytorch/training/test_pytorch_training_2_4.py, test/dlc_tests/ec2/pytorch/training/test_pytorch_training_2_5.py, test/dlc_tests/ec2/pytorch/training/test_pytorch_training_2_6.py
=> skip gdrcopy test for pt training

release_images_patches.yml
=> Release PT 2.7 arm64 training

available_images.md
=> Add PT 2.7 arm64 training to available_images

dlc_developer_config.toml, test/dlc_tests/conftest.py, test/test_utils/ec2.py
=> Fix "No Space left on device" issue in sagemaker_local_test

src/image.py
=> fix to_build logic

vllm/buildspec.yml
=> Add dummy vllm buildspec file

test/testrunner.py
=> skip non sanity/security mainline test for vllm/base image

pytorch/inference/docker/2.4/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json, pytorch/inference/docker/2.4/py3/Dockerfile.ec2.graviton.cpu.os_scan_allowlist.json, pytorch/inference/docker/2.4/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json, pytorch/inference/docker/2.4/py3/Dockerfile.sagemaker.graviton.cpu.os_scan_allowlist.json, pytorch/inference/docker/2.4/py3/cu124/Dockerfile.ec2.gpu.os_scan_allowlist.json, pytorch/inference/docker/2.4/py3/cu124/Dockerfile.ec2.graviton.gpu.os_scan_allowlist.json, pytorch/inference/docker/2.4/py3/cu124/Dockerfile.sagemaker.gpu.os_scan_allowlist.json, pytorch/inference/docker/2.5/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json, pytorch/inference/docker/2.5/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json, pytorch/inference/docker/2.5/py3/cu124/Dockerfile.ec2.gpu.os_scan_allowlist.json, pytorch/inference/docker/2.5/py3/cu124/Dockerfile.sagemaker.gpu.os_scan_allowlist.json, pytorch/training/docker/2.4/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json, pytorch/training/docker/2.4/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json, pytorch/training/docker/2.4/py3/cu124/Dockerfile.ec2.gpu.os_scan_allowlist.json, pytorch/training/docker/2.4/py3/cu124/Dockerfile.sagemaker.gpu.os_scan_allowlist.json, pytorch/training/docker/2.5/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json, pytorch/training/docker/2.5/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json, pytorch/training/docker/2.5/py3/cu124/Dockerfile.ec2.gpu.os_scan_allowlist.json, pytorch/training/docker/2.5/py3/cu124/Dockerfile.sagemaker.gpu.os_scan_allowlist.json
=> Allowlist new torch CVE(same CVE, but different cvss score)

release_images_general.yml
=> add release_images_general.yml

dlc_developer_config.toml, vllm/buildspec.yml, vllm/x86_64/build_artifacts/dockerd_entrypoint.sh, vllm/x86_64/gpu/cu124/Dockerfile
**Note**: 
- [c007f62](https://github.com/aws/deep-learning-containers/pull/4876/commits/c007f62d0dd6a08298eecbefcdedfbdc0190189c) Build success.
- Telemetry command run
```
docker run --runtime nvidia --gpus all     -v ~/.cache/huggingface:/root/.cache/huggingface     -e TEST_MODE="1"     --env "HUGGING_FACE_HUB_TOKEN={hf tocken}"     -p 8000:8000     --ipc=host    de8abb6e5917     --model mistralai/Mistral-7B-v0.1
```
- Results
```
docker exec bedff436b1b7 bash -c "cat /tmp/test_request.txt" …
```
=> Add telemetry to vllm entrypoint

pytorch/inference/docker/2.5/py3/Dockerfile.ec2.arm64.cpu.os_scan_allowlist.json, pytorch/inference/docker/2.5/py3/Dockerfile.sagemaker.arm64.cpu.os_scan_allowlist.json, pytorch/inference/docker/2.5/py3/cu124/Dockerfile.ec2.arm64.gpu.os_scan_allowlist.json, pytorch/inference/docker/2.5/py3/cu124/Dockerfile.sagemaker.arm64.gpu.os_scan_allowlist.json
=> Allowlist torch for PT2.5 arm64

test/sagemaker_tests/__init__.py
=> Skip ap-northeast-2 for TF tests due to instability

dlc_developer_config.toml, pytorch/training/docker/2.7/py3/cu128/Dockerfile.ec2.arm64.gpu.core_packages.json
=> Fix core packages file

base/x86_64/gpu/cu128/Dockerfile, dlc_developer_config.toml, release_images_general.yml, scripts/install_cuda.sh, scripts/install_efa.sh, test/dlc_tests/sanity/test_pre_release.py, vllm/buildspec.yml, vllm/x86_64/gpu/Dockerfile
=> update EFA to 1.41.0 vllm to 0.9.0.1

release_images_inference.yml
=> [djl-serving] 0.32.0 and 0.33.0 lmi image patch release

dlc_developer_config.toml, test/dlc_tests/ec2/pytorch/inference/test_pytorch_inference.py, test/dlc_tests/ec2/tensorflow/inference/test_tensorflow_inference.py
=> Increase instance type size for graviton/arm64 cpu deep canaries

release_images_inference.yml
=> [trtllm-0.33.0] Update release_images_inference.yml with trtllm version for djl-serving 0.33.0 release

release_images_inference.yml
=> [trtllm] Update release_images_inference.yml to remove rc1 from TensorRT version

dlc_developer_config.toml, tensorflow/inference/buildspec-2-19-sm.yml, tensorflow/inference/docker/2.19/py3/Dockerfile.sagemaker.cpu.core_packages.json, tensorflow/inference/docker/2.19/py3/cu122/Dockerfile.sagemaker.gpu.core_packages.json
**Note**: 
Tensorflow 2.19 Inference Autopatch- 
[dad7df0](https://github.com/aws/deep-learning-containers/pull/4983/commits/d50469f971de4286e3377870bb7bbc925fc5e2ba) - passed ec2, ecs, eks, sanity, security, sagemaker_local, sagemaker tests
[07cd2fc](https://github.com/aws/deep-learning-containers/pull/4983/commits/07cd2fc86cc22d490fa021f6d14ae77193d0a35b) - passed ec2 benchmark,ec2_heavy_instance, sagemaker_efa, sagemaker_rc, sagemaker_benchmark tests  
**NOTE: By default, docker builds are disabled. In order to build your …
=> Onboarding Tensorflow 2.19 Inference onto autopatch

available_images.md
… prior list
**Note**: 
<details>
`python src/prepare_dlc_dev_environment.py …
=> Tensorflow_Training_2.19 Available images update 

release_images_general.yml
=> vllm 0.9.2 release

release_images_general.yml, release_images_patches.yml
=> Onboard images to public registry release

pytorch/inference/docker/2.5/py3/cu124/Dockerfile.gpu, pytorch/inference/docker/2.6/py3/cu124/Dockerfile.gpu
=> Fix gpu build

release_images_patches.yml
=> Add TF2.19_ARM to release_image_patches

pytorch/training/docker/2.5/py3/Dockerfile.ec2.cpu.core_packages.json, pytorch/training/docker/2.5/py3/Dockerfile.sagemaker.cpu.core_packages.json, pytorch/training/docker/2.5/py3/cu124/Dockerfile.ec2.gpu.core_packages.json, pytorch/training/docker/2.5/py3/cu124/Dockerfile.sagemaker.gpu.core_packages.json, pytorch/training/docker/2.6/py3/Dockerfile.ec2.cpu.core_packages.json, pytorch/training/docker/2.6/py3/Dockerfile.sagemaker.cpu.core_packages.json, pytorch/training/docker/2.6/py3/cu126/Dockerfile.ec2.gpu.core_packages.json, pytorch/training/docker/2.6/py3/cu126/Dockerfile.sagemaker.gpu.core_packages.json, pytorch/training/docker/2.7/py3/Dockerfile.ec2.cpu.core_packages.json, pytorch/training/docker/2.7/py3/Dockerfile.sagemaker.cpu.core_packages.json, pytorch/training/docker/2.7/py3/cu128/Dockerfile.ec2.gpu.core_packages.json, pytorch/training/docker/2.7/py3/cu128/Dockerfile.sagemaker.gpu.core_packages.json
=> fix security test failure

pytorch/training/docker/2.7/py3/Dockerfile.ec2.cpu.core_packages.json, pytorch/training/docker/2.7/py3/Dockerfile.sagemaker.cpu.core_packages.json, pytorch/training/docker/2.7/py3/cu128/Dockerfile.ec2.gpu.core_packages.json, pytorch/training/docker/2.7/py3/cu128/Dockerfile.sagemaker.gpu.core_packages.json
=> address Pt2.7 security test

vllm/CHANGELOG.md
=> add vLLM 0.9.2 changelog

pytorch/training/docker/2.7/py3/cu128/Dockerfile.gpu
=> Fix Pytorch 2.7 GPU Dockerfile nccl path

dlc_developer_config.toml, test/sagemaker_tests/huggingface_pytorch/training/requirements.txt
=> fix pytest pin

release_images_inference.yml
=> [djl] patch release for 0.32.0 TRT-LLM DLC

dlc_developer_config.toml, miscellaneous_scripts/dockerfile_patch_script.sh, pytorch/inference/buildspec-2-5-ec2.yml, pytorch/inference/buildspec-2-5-sm.yml, pytorch/inference/buildspec-2-6-ec2.yml, pytorch/inference/buildspec-2-6-sm.yml, pytorch/inference/docker/2.5/py3/Dockerfile.ec2.cpu.core_packages.json, pytorch/inference/docker/2.5/py3/Dockerfile.sagemaker.cpu.core_packages.json, pytorch/inference/docker/2.5/py3/cu124/Dockerfile.ec2.gpu.core_packages.json, pytorch/inference/docker/2.5/py3/cu124/Dockerfile.sagemaker.gpu.core_packages.json, pytorch/inference/docker/2.6/py3/cu124/Dockerfile.ec2.gpu.core_packages.json, pytorch/inference/docker/2.6/py3/cu124/Dockerfile.sagemaker.gpu.core_packages.json
**Note**: 
- [8814ffd](https://github.com/aws/deep-learning-containers/pull/5068/commits/8814ffd7b3c07f09a8bff5bb1e1bee7d8d6523cb) PT2.5 INF SM passed tests.
- [706b82c](https://github.com/aws/deep-learning-containers/pull/5068/commits/706b82c399643ec05dd31f1303096383eb192aad) PT2.5 INF EC2 passed tests.
- [5bba212](https://github.com/aws/deep-learning-containers/pull/5068/commits/5bba212352d0582a6b4f042c97da38ab3cb9f76b) PT2.6 INF EC2 passed tests.
- [8bb9970](https://github.com/aws/deep-learning-containers/pull/5068/commits/8bb9970 …
=> Onboard PT INF to autopatch

release/dlc_release_information.py
=> Add --ignore-installed to lmi v2 pipdeptree install

dlc_developer_config.toml, pytorch/training/buildspec-2-4-ec2.yml, pytorch/training/docker/2.4/py3/Dockerfile.cpu, pytorch/training/docker/2.4/py3/Dockerfile.ec2.cpu.core_packages.json, pytorch/training/docker/2.4/py3/Dockerfile.ec2.cpu.os_scan_allowlist.json, pytorch/training/docker/2.4/py3/Dockerfile.sagemaker.cpu.os_scan_allowlist.json, pytorch/training/docker/2.4/py3/cu124/Dockerfile.ec2.gpu.core_packages.json, pytorch/training/docker/2.4/py3/cu124/Dockerfile.ec2.gpu.os_scan_allowlist.json, pytorch/training/docker/2.4/py3/cu124/Dockerfile.gpu, pytorch/training/docker/2.4/py3/cu124/Dockerfile.sagemaker.gpu.os_scan_allowlist.json, release_images_patches.yml, release_images_training.yml
=> update EFA version for pytorch 2.4 training

dlc_developer_config.toml, release_images_general.yml, vllm/CHANGELOG.md, vllm/buildspec.yml, vllm/x86_64/gpu/Dockerfile
=> update vllm to v0.10.0

release_images_inference.yml, release_images_training.yml
=> AutoGluon 1.4.0 DLC Release

test/testrunner.py
=> disable vllm EKS test on mainline pipeline

dlc_developer_config.toml, huggingface/pytorch/training/docker/2.1/py3/sdk2.20.0/Dockerfile.neuronx.os_scan_allowlist.json
=> adding CVE-2024-48063 for pytorch training neuronx 2.1.2

pytorch/training/docker/2.7/py3/Dockerfile.sagemaker.cpu.core_packages.json, pytorch/training/docker/2.7/py3/cu128/Dockerfile.sagemaker.gpu.core_packages.json
=> fix package_version_regression for PT27 Sagemaker

test/sagemaker_tests/pytorch/training/integration/sagemaker/test_distributed_operations.py, test/sagemaker_tests/pytorch/training/integration/sagemaker/test_gdrcopy.py
=> Skipping sagemaker gdrcopy and efa tests

release_images_general.yml, vllm/CHANGELOG.md, vllm/buildspec.yml, vllm/x86_64/gpu/Dockerfile
update vllm to v0.10.1.1
<details>
`python …
=> update vllm to v0.10.1.1

dlc_developer_config.toml, src/image.py
**Note**:
- [f7138b8](https://github.com/aws/deep-learning-containers/pull/5233/commits/f7138b80744d1d0adf8ba5b5370b6722cc5f1fb8) Build without cache. (There is one success build before under the same PR [b96b4fa](https://github.com/aws/deep-learning-containers/pull/5233/commits/b96b4fa244b37d824b5adf36498b22a888e151f1))
- [28fa162](https://github.com/aws/deep-learning-containers/pull/5233/commits/28fa1622bb7b5b85ea96febe75682610c294d9ed) Build with cache.
By default, docker image builds and tests are disabled. Two ways to run builds …
=> Build vllm to check CVEs

release_images_general.yml
**Note**:
Successful RC run - 
https://tiny.amazon.com/1hp9b3rkg/IsenLink
<details>
- Run default builds and tests for a particular …
=> add vllm arm64 to release

release_images_inference.yml
=> [djl-serving] Add 0.34.0 lmi image release
